### ISSUE TITLE
tool failure with "Exception: ValueError('Upper bound 1000000 cannot be less than init 2828223.4')"

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmpy#1064]

**Comment by schaedeli** [comment]
Hi, the run_modelsearch() tool returns the modelsearch_dirX with empty folders for each candidate_model to be generated, but no files in the folders. 

Here is the file metadata.json
```
{
    "pharmpy_version": "0.75.0",
    "tool_name": "modelsearch",
    "stats": {
        "start_time": "2022-08-29T15:10:05.697935+02:00"
    },
    "tool_options": {
        "search_space": "PERIPHERALS(1..2);ELIMINATION([MM,MIX-FO-MM])",
        "algorithm": "reduced_stepwise",
        "iiv_strategy": "no_add",
        "rank_type": "bic",
        "cutoff": null,
        "model": "<Pharmpy model object run1>"
    },
    "common_options": {
        "dispatcher": "pharmpy.workflows.dispatchers.local_dask",
        "database": {
            "class": "LocalDirectoryToolDatabase",
            "toolname": "modelsearch",
            "path": "C:\\Users\\Public\\ADaMO\\Phase_1\\Model_2\\modelsearch_fss\\modelsearch_dir2"
        }
    }
}
```

**Comment by stellabelin** [comment]
Hi! From the metadata-file it looks okay, how did the .lst/.ext-file look like after run1? Also, rereading this I see that another error it failed on is `NotADirectoryError` for the stderr-dir, but maybe the errors occurred pretty much simultaneously, the main issue could still be the upper bound error. Could you possibly send me the run1.mod + its result files? Dataset is not necessary.

**Comment by schaedeli** [comment]
Hi, please see attached the latest error messages and the run1.ctl and .lst.
Please let me know if this helps.
Kind Regards
Franziska


[image: image.png]


*Franziska Schaedeli Stark, PhD*Senior Pharmacometrician
Senior Principal Scientist
Pharmaceutical Sciences - Predictive Modeling & Data Analytics (PS-PMDA)
Roche Pharma Research & Early Development (pRED)

Roche Innovation Center Basel

F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124
Bldg 1 - Floor 7

4070 Basel

Phone:  +41 61 688 5819
Mob +41 79 773 12 61
mailto: ***@***.***

**Comment by stellabelin** [comment]
Hi! Would it be possible to rerun this? I think I'll need the full error stack to understand this error (this is automatically printed since pharmr 0.76.5), so if you could rerun and then send the full error message it could give me a better understanding of where this error happens.

**Comment by joaoabr** [comment]
Hi. With Pharmpy version 0.83.0, the MM models crashed but run_amd finished up to the very end. With Pharmpy version 0.85.0 the tool crashes with an identical error as before - see below.  Can you help?

```
txt> res <- run_amd(
txt+     dataset_path,
txt+     modeltype='pk_iv',
txt+     # search_space='PERIPHERALS(1)',
txt+     # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
txt+     cl_init= CL,
txt+     vc_init= V,
txt+     allometric_variable="WGT"
txt+     # mat_init=0.1,
txt+     # occasion='VISI'
txt+ )

```
```
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py:367: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
2022-11-18 23:47:14,081 - distributed.worker - WARNING - Compute Failed
Key:       ELIMINATION(MIX-FO-add_iivs-copy-update_inits-run0-9d663ebd-b757-4c5e-aa3e-2a6e565f83e0
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f7c62fe9af0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f7c60927700>, (<function _add_iiv_to_func at 0x7f7c61ebd430>, 'absorption_delay', (<function _apply_transformation at 0x7f7c61e8dc10>, ('ELIMINATION', 'MIX-FO-MM'), <function set_mixed_mm_fo_elimination at 0x7f7ca3dcd790>, (<function update_initial_estimates at 0x7f7c61e0da60>, (<function _copy at 0x7f7c61ebd0d0>, 'modelsearch_run2', (('ELIMINATION', 'MIX-FO-MM'),), <Pharmpy model object start>))))))
kwargs:    {}
Exception: "ValueError('Upper bound 1000000.0 cannot be less than init 2828223.4')"

<Client: 'inproc://172.17.0.8/336/1' processes=6 threads=36, memory=46.99 GiB>
<Client: 'inproc://172.17.0.8/336/25' processes=6 threads=36, memory=46.99 GiB>
ValueError: Upper bound 1000000.0 cannot be less than init 2828223.4
Full stack:
ValueErrorUpper bound 1000000.0 cannot be less than init 2828223.4c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 185, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 282, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 178, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 206, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 71, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 52, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3122, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2291, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2154, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py\", line 93, in task\n    return execute_model(model, context)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py\", line 27, in execute_model\n    database.store_model(model)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/baseclass.py\", line 301, in store_model\n    return txn.store_model()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/local_directory.py\", line 246, in store_model\n    write_model(model, str(model_path / (model.name + model.filename_extension)), force=True)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py\", line 169, in write_model\n    model.update_source(path=path, force=force)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 159, in update_source\n    update_parameters(self, self.internals._old_parameters, self._parameters)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/update.py\", line 88, in update_parameters\n    theta_number = get_next_theta(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/update.py\", line 200, in get_next_theta\n    thetas = theta_record.parameters(next_theta)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/records/theta_record.py\", line 86, in parameters\n    new_par = Parameter.create(name, init, lower, upper, fix)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/parameters.py\", line 78, in create\n    raise ValueError(f'Upper bound {upper} cannot be less than init {init}')\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 185, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 282, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 178, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 206, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 71, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 52, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3122, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2291, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2154, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py", line 93, in task
    return execute_model(model, context)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py", line 27, in execute_model
    database.store_model(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/baseclass.py", line 301, in store_model
    return txn.store_model()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/local_directory.py", line 246, in store_model
    write_model(model, str(model_path / (model.name + model.filename_extension)), force=True)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py", line 169, in write_model
    model.update_source(path=path, force=force)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 159, in update_source
    update_parameters(self, self.internals._old_parameters, self._parameters)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/update.py", line 88, in update_parameters
    theta_number = get_next_theta(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/update.py", line 200, in get_next_theta
    thetas = theta_record.parameters(next_theta)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/records/theta_record.py", line 86, in parameters
    new_par = Parameter.create(name, init, lower, upper, fix)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/parameters.py", line 78, in create
    raise ValueError(f'Upper bound {upper} cannot be less than init {init}')
ValueError: Upper bound 1000000.0 cannot be less than init 2828223.4

pharmr version: 0.85.0
'0.85.0'
```

**Comment by stellabelin** [comment]
Hi! Thank you for reporting. Would it be possible to send the full AMD-directory (dataset is not needed).

**Comment by joaoabr** [comment]
done

**Comment by zrinkaduvnjak** [comment]
Hi!

I was running a full AMD tool with PharmPy version 0.85.0 and I had a similar issue:
**ValueError: Upper bound 1000000.0 cannot be less than init 6.223690000000001e+55**

Error:
2022-11-24 12:28:19,207 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-8401bcbd-0585-4f90-8a79-1b4c3d144a78
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f8a1117bee0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f8a1139e490>, (<function _add_iiv_to_func at 0x7f8a10cd4f70>, 'absorption_delay', (<function _apply_transformation at 0x7f8a10cd4d30>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7f8a540471f0>, n=1), (<function update_initial_estimates at 0x7f8a120f10d0>, (<function _copy at 0x7f8a10cd44c0>, 'modelsearch_run107', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7f8a10cd4ca0>, <Pharmpy model object modelsearch_run35>, <Pharmpy model object modelsearch_run50>)))))))
kwargs:    {}
Exception: "ValueError('Upper bound 1000000.0 cannot be less than init 6.223690000000001e+55')"

<Client: 'inproc://172.17.0.17/334/1' processes=3 threads=9, memory=46.99 GiB>
<Client: 'inproc://172.17.0.17/334/16' processes=3 threads=9, memory=46.99 GiB>
ValueError: Upper bound 1000000.0 cannot be less than init 6.223690000000001e+55
Full stack:
ValueErrorUpper bound 1000000.0 cannot be less than init 6.223690000000001e+55c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 185, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 282, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 178, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 206, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 71, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 52, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3122, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2291, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2154, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py\", line 93, in task\n    return execute_model(model, context)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py\", line 33, in execute_model\n    model_with_correct_datapath = database.retrieve_model(model.name)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/baseclass.py\", line 325, in retrieve_model\n    return sn.retrieve_model()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/local_directory.py\", line 303, in retrieve_model\n    model = Model.create_model(path)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py\", line 435, in create_model\n    model = model_module.parse_code(code, path, **kwargs)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 270, in parse_code\n    parameters = parse_parameters(control_stream)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py\", line 36, in parse_parameters\n    thetas = theta_record.parameters(next_theta, seen_labels={p.name for p in params})\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/records/theta_record.py\", line 86, in parameters\n    new_par = Parameter.create(name, init, lower, upper, fix)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/parameters.py\", line 78, in create\n    raise ValueError(f'Upper bound {upper} cannot be less than init {init}')\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 185, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 282, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 178, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 206, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 71, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 52, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3122, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2291, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2154, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py", line 93, in task
    return execute_model(model, context)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py", line 33, in execute_model
    model_with_correct_datapath = database.retrieve_model(model.name)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/baseclass.py", line 325, in retrieve_model
    return sn.retrieve_model()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/local_directory.py", line 303, in retrieve_model
    model = Model.create_model(path)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py", line 435, in create_model
    model = model_module.parse_code(code, path, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 270, in parse_code
    parameters = parse_parameters(control_stream)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py", line 36, in parse_parameters
    thetas = theta_record.parameters(next_theta, seen_labels={p.name for p in params})
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/records/theta_record.py", line 86, in parameters
    new_par = Parameter.create(name, init, lower, upper, fix)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/parameters.py", line 78, in create
    raise ValueError(f'Upper bound {upper} cannot be less than init {init}')
ValueError: Upper bound 1000000.0 cannot be less than init 6.223690000000001e+55

pharmr version: 0.85.0
'0.85.0'
Pharmpy version: 0.85.0




It crashed during model_search. Initial estimates and boundary for KM inside created model seem to be off:
![image](https://user-images.githubusercontent.com/118992449/203831665-0cc95726-cfb9-4063-ad8c-3dce85ad3bee.png)



It is interesting that when I didn't specify initial parameter estimates in the run_amd() call, all the subtools finished smoothly.

Full AMD directory and a dataset will be uploaded to the Box.


Best,

Zrinka

**Comment by stellabelin** [comment]
Hi! I just checked the files uploaded to box and it seems like the `models`-directory in `modelsearch` either doesn't exist (example2.zip) or is incomplete (in amd_dir1.zip, only three models without .lst-files). From the error it looks that it happens to candidate 107, meaning there should be more models, was it the case in the original run that these files were not created/copied?

**Comment by zrinkaduvnjak** [comment]
Hi!
We tried to reproduce the error from example2.zip (error from my previous comment), however, we were not able to - this time amd tool was running smoothly. We also don't have access to the files in modelsearch directory (this is not due to pharmr).

Regarding the example1, where modelsearch file is incomplete (only three models without .lst-files), files were not created at all (directories look the same after reproduction of the error, so this should be due to pharmr)

**Comment by stellabelin** [comment]
Hi! Thanks for looking into this! I've looked at example1 and saw that the parameter that has a very high initial estimate is the KM-parameter (which Pharmpy creates to be DV_max * 2), so I was wondering if this dataset have high values for DV?

**Comment by stellabelin** [comment]
And could you say what the biggest and smallest DV values are of the dataset? If we need to scale?

**Comment by zrinkaduvnjak** [comment]
Hi! Yes - the highest DV value is 1414111.7, and the lowest is 82.5. If a recall correctly, one of the colleagues solved the issue by converting DV to other units.

**Comment by stellabelin** [comment]
There is now a cap on the initial estimate of KM, but the other error messages are hard to say since much of the underlying code have been changed (e.g. making models immutable I think could make these types of errors less likely). I will close this since much of the underlying code has changed and we haven't seen this type of error since, but please reopen if this is still a problem!
