### ISSUE TITLE
modeling$fit

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#110]
Issue on windows when trying to fit models:

```
pharmpy$plugins$nonmem$conf$parameter_names <- c('abbr', 'comment', 'basic')
model1 <- pharmpy$Model(here::here('run1.mod'))
modeling$fit(model1)

```

gives the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 513, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 337, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\synchronize.py", line 104, in __getstate__
    h = context.get_spawning_popen().duplicate_for_child(sl.handle)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 99, in duplicate_for_child
    return reduction.duplicate(handle, self.sentinel)
  File "C:\Users\<person>\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied

```

**Comment by rikardn** [comment]
Fixed by f13e15227c7b9c419833a700bd801070db80bef1 and 249c84b221d3026cbc77e7660ed21d4289575931. Fix will be in the version after 0.17.0
