### ISSUE TITLE
Another regression in the PsN system tests for frem

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1154]
```
2022-09-12T13:25:12.0700204Z Traceback (most recent call last):
2022-09-12T13:25:12.0701180Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/bin/pharmpy", line 8, in <module>
2022-09-12T13:25:12.0701763Z     sys.exit(run())
2022-09-12T13:25:12.0702758Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/__main__.py", line 8, in run
2022-09-12T13:25:12.0703426Z     main(args)
2022-09-12T13:25:12.0704785Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/cli.py", line 1995, in main
2022-09-12T13:25:12.0705251Z     args.func(args)
2022-09-12T13:25:12.0705865Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/cli.py", line 696, in results_frem
2022-09-12T13:25:12.0706305Z     res = psn_frem_results(
2022-09-12T13:25:12.0706987Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/tools/frem/results.py", line 1023, in psn_frem_results
2022-09-12T13:25:12.0707498Z     psn_reorder_base_model_inits(model1b, path)
2022-09-12T13:25:12.0708212Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/tools/frem/results.py", line 946, in psn_reorder_base_model_inits
2022-09-12T13:25:12.0709023Z     p.init = values[i]
2022-09-12T13:25:12.0709413Z AttributeError: can't set attribute
```

**Comment by rikardn** [comment]
This has been fixed.
