### ISSUE TITLE
scm regression in PsN system tests

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1155]
```
2022-09-12T13:49:14.0376467Z Traceback (most recent call last):
2022-09-12T13:49:14.0376875Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/bin/pharmpy", line 8, in <module>
2022-09-12T13:49:14.0377239Z     sys.exit(run())
2022-09-12T13:49:14.0378045Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/__main__.py", line 8, in run
2022-09-12T13:49:14.0378446Z     main(args)
2022-09-12T13:49:14.0379021Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/cli.py", line 1995, in main
2022-09-12T13:49:14.0379414Z     args.func(args)
2022-09-12T13:49:14.0380011Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/cli.py", line 735, in results_scm
2022-09-12T13:49:14.0380460Z     res = psn_scm_results(args.psn_dir)
2022-09-12T13:49:14.0381148Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/tools/scm/results.py", line 677, in psn_scm_results
2022-09-12T13:49:14.0382065Z     res.ofv_summary = ofv_summary_dataframe(res.steps, final_included=True, iterations=True)
2022-09-12T13:49:14.0382846Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pharmpy/tools/scm/results.py", line 80, in ofv_summary_dataframe
2022-09-12T13:49:14.0383477Z     final = steps[~steps['selected']].loc[last_stepnum, :, :, :].copy()
2022-09-12T13:49:14.0384176Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 961, in __getitem__
2022-09-12T13:49:14.0384633Z     return self._getitem_tuple(key)
2022-09-12T13:49:14.0385290Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1140, in _getitem_tuple
2022-09-12T13:49:14.0385865Z     return self._getitem_lowerdim(tup)
2022-09-12T13:49:14.0386522Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 843, in _getitem_lowerdim
2022-09-12T13:49:14.0386999Z     return self._getitem_nested_tuple(tup)
2022-09-12T13:49:14.0387670Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 914, in _getitem_nested_tuple
2022-09-12T13:49:14.0388178Z     return self._handle_lowerdim_multi_index_axis0(tup)
2022-09-12T13:49:14.0388917Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1166, in _handle_lowerdim_multi_index_axis0
2022-09-12T13:49:14.0389369Z     raise ek
2022-09-12T13:49:14.0390029Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1160, in _handle_lowerdim_multi_index_axis0
2022-09-12T13:49:14.0390517Z     return self._get_label(tup, axis=axis)
2022-09-12T13:49:14.0391163Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1153, in _get_label
2022-09-12T13:49:14.0391623Z     return self.obj.xs(label, axis=axis)
2022-09-12T13:49:14.0392255Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/generic.py", line 3857, in xs
2022-09-12T13:49:14.0392729Z     loc, new_index = index._get_loc_level(key, level=0)
2022-09-12T13:49:14.0393417Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 3080, in _get_loc_level
2022-09-12T13:49:14.0393908Z     loc_level = self._get_level_indexer(k, level=i)
2022-09-12T13:49:14.0394594Z   File "/usr/local/share/perl/5.30.0/PsN_5_3_0/pyvenv/lib/python3.8/site-packages/pandas/core/indexes/multi.py", line 3249, in _get_level_indexer
2022-09-12T13:49:14.0395040Z     raise KeyError(key)
2022-09-12T13:49:14.0395306Z KeyError: 2
```

**Comment by rikardn** [comment]
This should no longer be a problem
