### ISSUE TITLE
AttributeError('peripheral_compartments')

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1173]
The following piece of code leads to the error below during modelsearch (dataset12). Using Pharmpy 0.76.5.

```
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    cl_init= CL,
    vc_init= V
)
```
```

2022-09-18 03:38:28,744 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-copy-update_inits-run0-5c2ad10b-3743-46f7-b16a-fda443e0a67b
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7efbf84a6ca0>, (<function _add_iiv_to_func at 0x7efbfa604af0>, 'absorption_delay', (<function _apply_transformation at 0x7efbfa6048b0>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7efc4b007040>, n=1), (<function update_initial_estimates at 0x7efc087b7ee0>, (<function _copy at 0x7efbfa604a60>, 'modelsearch_candidate4', (('PERIPHERALS', 1),), <Pharmpy model object modelsearch_candidate1>))))))
kwargs:    {}
Exception: "AttributeError('peripheral_compartments')"

<Client: 'inproc://172.17.0.22/334/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.22/334/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.22/334/19' processes=1 threads=12, memory=31.24 GiB>
AttributeError: peripheral_compartments
Full stack:
AttributeErrorperipheral_compartmentsc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 212, in _run_modelsearch\n    res_modelsearch = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 222, in _apply_transformation\n    func(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py\", line 1289, in set_peripheral_compartments\n    per = len(model.statements.ode_system.peripheral_compartments)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py\", line 189, in __getattr__\n    raise AttributeError(key)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 212, in _run_modelsearch
    res_modelsearch = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 222, in _apply_transformation
    func(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py", line 1289, in set_peripheral_compartments
    per = len(model.statements.ode_system.peripheral_compartments)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py", line 189, in __getattr__
    raise AttributeError(key)
AttributeError: peripheral_compartments

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5


```

**Comment by joaoabr** [comment]
Identical error with a different dataset (dataset 16):

```
res <- run_amd(
     dataset_path,
     modeltype='pk_oral',
     cl_init= CL,
     vc_init= V,
     mat_init= MAT,
     categorical = "STUD",
     continuous = c("BW","ALB")
     )
```

```

/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate62: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate59: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate63: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate56: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate31: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate32: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate33: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate44: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate21: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate36: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate37: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate34: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate35: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate47: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate22: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate43: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2022-09-17 20:32:23,036 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-c7a6772d-89b7-4764-bb8a-4007003282f5
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f66ce0f1d30>, (<function _add_iiv_to_func at 0x7f66dcde7d30>, 'absorption_delay', (<function _apply_transformation at 0x7f66dcde7af0>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7f672c879040>, n=1), (<function update_initial_estimates at 0x7f66df95ce50>, (<function _copy at 0x7f66dcde7ca0>, 'modelsearch_candidate105', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7f66dcde78b0>, <Pharmpy model object modelsearch_candidate33>, <Pharmpy model object modelsearch_candidate44>)))))))
kwargs:    {}
Exception: "AttributeError('peripheral_compartments')"

<Client: 'inproc://172.17.0.16/334/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.16/334/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.16/334/19' processes=1 threads=12, memory=31.24 GiB>
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate23: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
AttributeError: peripheral_compartments
Full stack:
AttributeErrorperipheral_compartmentsc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 212, in _run_modelsearch\n    res_modelsearch = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 222, in _apply_transformation\n    func(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py\", line 1289, in set_peripheral_compartments\n    per = len(model.statements.ode_system.peripheral_compartments)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py\", line 189, in __getattr__\n    raise AttributeError(key)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 212, in _run_modelsearch
    res_modelsearch = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 222, in _apply_transformation
    func(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py", line 1289, in set_peripheral_compartments
    per = len(model.statements.ode_system.peripheral_compartments)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py", line 189, in __getattr__
    raise AttributeError(key)
AttributeError: peripheral_compartments

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5
```

**Comment by joaoabr** [comment]
Identical error with a different dataset (dataset 1):

```
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    cl_init= CL,
    vc_init= V,
    occasion='VISI'
)
```

```
2022-09-18 00:55:09,366 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-copy-update_inits-run0-18be2b59-5659-4b18-8bef-e5385362f688
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f6166f07040>, (<function _add_iiv_to_func at 0x7f61659a35e0>, 'absorption_delay', (<function _apply_transformation at 0x7f61659a3ee0>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7f61a8f7e040>, n=1), (<function update_initial_estimates at 0x7f6166f0f790>, (<function _copy at 0x7f61659a3dc0>, 'modelsearch_candidate4', (('PERIPHERALS', 1),), <Pharmpy model object modelsearch_candidate1>))))))
kwargs:    {}
Exception: "AttributeError('peripheral_compartments')"

<Client: 'inproc://172.17.0.2/335/1' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.2/335/10' processes=1 threads=12, memory=31.24 GiB>
<Client: 'inproc://172.17.0.2/335/19' processes=1 threads=12, memory=31.24 GiB>
AttributeError: peripheral_compartments
Full stack:
AttributeErrorperipheral_compartmentsc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 212, in _run_modelsearch\n    res_modelsearch = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 170, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3052, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2226, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2089, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py\", line 222, in _apply_transformation\n    func(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py\", line 1289, in set_peripheral_compartments\n    per = len(model.statements.ode_system.peripheral_compartments)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py\", line 189, in __getattr__\n    raise AttributeError(key)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 212, in _run_modelsearch
    res_modelsearch = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 170, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3052, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelsearch/algorithms.py", line 222, in _apply_transformation
    func(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/odes.py", line 1289, in set_peripheral_compartments
    per = len(model.statements.ode_system.peripheral_compartments)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/statements.py", line 189, in __getattr__
    raise AttributeError(key)
AttributeError: peripheral_compartments

pharmr version: 0.76.5
'0.76.5'
Pharmpy version: 0.76.5
```

**Comment by stellabelin** [comment]
Hi! Thanks for reporting. I cannot recreate it with our tests. Does it happen if you set the search space to `'PERIPHERALS(1)'`? Could you post the start model of the AMD tool, i.e. the model Pharmpy created? It should be in the AMD-directory

**Comment by stellabelin** [comment]
Hi! I think I've identified a potential cause, I've made a fix here: ebfafb45faddefb287b6e43cff1501197d496428, which will be in the next release (which we plan on making soon).

**Comment by joaoabr** [comment]
indeed, if I use 'PERIPHERALS(1)' the issue does not happen.

**Comment by stellabelin** [comment]
@joaoabr, does it work now? Can I close the issue?

**Comment by joaoabr** [comment]
Yes, it works with version 0.78.0. Thanks!

**Comment by stellabelin** [comment]
Great, closing the issue!
