### ISSUE TITLE
Please check base_model.mod file to make sure ID, TIME, CWRES are in $TABLE.

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1201]
After running with dataset4 (27SEP2022):
```
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    cl_init= CL,
    vc_init= V
)
```

the following error appears:
```
<Client: 'inproc://172.17.0.6/334/29' processes=1 threads=12, memory=31.24 GiB>
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate2: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate1: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate3: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate6: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate8: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate7: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate10: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate9: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate12: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: modelsearch_candidate11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: iivsearch_no_of_etas_candidate1: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: iivsearch_no_of_etas_candidate3: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: iivsearch_no_of_etas_candidate2: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:22: UserWarning: iivsearch_block_structure_candidate1: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
ValueError: Please check base_model.mod file to make sure ID, TIME, CWRES are in $TABLE.
Full stack:
ValueErrorPlease check base_model.mod file to make sure ID, TIME, CWRES are in $TABLE.c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 145, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 230, in _run_ruvsearch\n    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 163, in run_tool\n    wf = tool.create_workflow(*args, **tool_options)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 67, in create_workflow\n    _check_input(model, groups, p_value, skip)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 83, in _check_input\n    raise ValueError(\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 145, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 230, in _run_ruvsearch
    res_ruvsearch = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 163, in run_tool
    wf = tool.create_workflow(*args, **tool_options)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 67, in create_workflow
    _check_input(model, groups, p_value, skip)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 83, in _check_input
    raise ValueError(
ValueError: Please check base_model.mod file to make sure ID, TIME, CWRES are in $TABLE.

pharmr version: 0.78.0
'0.78.0'
Pharmpy version: 0.78.0

```

Note that at this stage there is no ruvsearch folder yet:
![image](https://user-images.githubusercontent.com/75365723/192648757-87ea3bfe-a0ad-43fc-863c-35614bce6d0b.png)

**Comment by ZheHuang96** [comment]
Hi @joaoabr , I think this error message indicates the input model of ruvsearch (the `base_model.mod` in your case) may not have CWRES or even any residuals generated. Because ruvsearch needs CWRES to generate a dataset and build models. Currently, we have some checks of options before running ruvsearch, if there is no CWRES in the input model, ruvsearch won't be run, so there is no ruvsearch folder.

I think there must be something wrong with the  `base_model.mod ` May I ask you to check:

1.  Is ` base_model.mod ` the best model you got from iivsearch?
2.  If so,  are ID, TIME, CWRES in the `$TABLE` of  `base_model.mod `? 
3.  Is there an error message in the `base_model.lst`? 

Thank you so much for your help!

**Comment by joaoabr** [comment]
Thanks @ZheHuang96. Looking into the results in more detail, it looks like all models crash, including the base model (!). This quite an atypical case.  

start.lst contains the following message:

```
 MONITORING OF SEARCH:

0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL       1   ID= 1.00000000000000E+00
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER1,ON DIRECTORY: "$PWD/worker"/, NODE ID: 1
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      13   ID= 2.00000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER2,ON DIRECTORY: "$PWD/worker"/, NODE ID: 2
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      25   ID= 3.20000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER3,ON DIRECTORY: "$PWD/worker"/, NODE ID: 3
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      36   ID= 4.15000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER4,ON DIRECTORY: "$PWD/worker"/, NODE ID: 4
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      47   ID= 4.70000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER5,ON DIRECTORY: "$PWD/worker"/, NODE ID: 5
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      58   ID= 4.95000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER6,ON DIRECTORY: "$PWD/worker"/, NODE ID: 6
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      69   ID= 5.48000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER7,ON DIRECTORY: "$PWD/worker"/, NODE ID: 7
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      80   ID= 6.63000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER8,ON DIRECTORY: "$PWD/worker"/, NODE ID: 8
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL      91   ID= 6.82000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER9,ON DIRECTORY: "$PWD/worker"/, NODE ID: 9
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     102   ID= 7.18000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER10,ON DIRECTORY: "$PWD/worker"/, NODE ID: 10
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     113   ID= 8.93000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER11,ON DIRECTORY: "$PWD/worker"/, NODE ID: 11
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     124   ID= 9.84000000000000E+02
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER12,ON DIRECTORY: "$PWD/worker"/, NODE ID: 12
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     135   ID= 2.00000000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER13,ON DIRECTORY: "$PWD/worker"/, NODE ID: 13
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     146   ID= 2.06200000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER14,ON DIRECTORY: "$PWD/worker"/, NODE ID: 14
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     157   ID= 2.08300000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER15,ON DIRECTORY: "$PWD/worker"/, NODE ID: 15
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     168   ID= 2.21200000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER16,ON DIRECTORY: "$PWD/worker"/, NODE ID: 16
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     179   ID= 2.24100000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER17,ON DIRECTORY: "$PWD/worker"/, NODE ID: 17
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     190   ID= 2.28100000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER18,ON DIRECTORY: "$PWD/worker"/, NODE ID: 18
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     201   ID= 2.36200000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER19,ON DIRECTORY: "$PWD/worker"/, NODE ID: 19
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     212   ID= 2.40200000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER20,ON DIRECTORY: "$PWD/worker"/, NODE ID: 20
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     223   ID= 2.46500000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER21,ON DIRECTORY: "$PWD/worker"/, NODE ID: 21
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     234   ID= 2.50000000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER22,ON DIRECTORY: "$PWD/worker"/, NODE ID: 22
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     246   ID= 2.60100000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION
ON WORKER: WORKER23,ON DIRECTORY: "$PWD/worker"/, NODE ID: 23
0PROGRAM TERMINATED BY OBJ
 ERROR IN CELS   WITH INDIVIDUAL     256   ID= 2.67100000000000E+03
 SUM OF "SQUARED" WEIGHTED INDIVIDUAL RESIDUALS IS INFINITE
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT INITIAL OBJ. FUNCTION EVALUATION

 #TERM:
```

Then modelsearch results:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



summary_tool |   |   |   |   |  
-- | -- | -- | -- | -- | --
model | description | dbic | bic | rank | parent_model
start |   |   |   |   | start
modelsearch_candidate1 | ELIMINATION(MM) |   |   |   | start
modelsearch_candidate2 | ELIMINATION(MIX-FO-MM) |   |   |   | start
modelsearch_candidate3 | PERIPHERALS(1) |   |   |   | start
modelsearch_candidate4 | ELIMINATION(MM);PERIPHERALS(1) |   |   |   | modelsearch_candidate1
modelsearch_candidate5 | ELIMINATION(MIX-FO-MM);PERIPHERALS(1) |   |   |   | modelsearch_candidate2
modelsearch_candidate6 | PERIPHERALS(1);ELIMINATION(MM) |   |   |   | modelsearch_candidate3
modelsearch_candidate7 | PERIPHERALS(1);ELIMINATION(MIX-FO-MM) |   |   |   | modelsearch_candidate3
modelsearch_candidate8 | PERIPHERALS(1);PERIPHERALS(2) |   |   |   | modelsearch_candidate3
modelsearch_candidate9 | PERIPHERALS(1);PERIPHERALS(2);ELIMINATION(MM) |   |   |   | modelsearch_candidate8
modelsearch_candidate10 | PERIPHERALS(1);PERIPHERALS(2);ELIMINATION(MIX-FO-MM) |   |   |   | modelsearch_candidate8
modelsearch_candidate11 | ELIMINATION(MM);PERIPHERALS(1);PERIPHERALS(2) |   |   |   | modelsearch_candidate4
modelsearch_candidate12 | ELIMINATION(MIX-FO-MM);PERIPHERALS(1);PERIPHERALS(2) |   |   |   | modelsearch_candidate5



</body>

</html>

And, finally IIV search:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abrantj1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">


</head>

<body link="#0563C1" vlink="#954F72">



summary_tool |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
step | model | description | dbic | bic | rank | parent_model
1 | base_model | [CL,VC] |   |   |   | base_model
1 | iivsearch_no_of_etas_candidate1 | [VC] |   |   |   | base_model
1 | iivsearch_no_of_etas_candidate2 | [CL] |   |   |   | base_model
1 | iivsearch_no_of_etas_candidate3 | [] |   |   |   | base_model
2 | base_model | [CL,VC] |   |   |   | base_model
2 | iivsearch_block_structure_candidate1 | [CL]+[VC] |   |   |   | base_model



</body>

</html>

All models have the same error message, and the OFV is not generated. Probably the user will want to re-start the tool with e.g. different initial estimates. 

Even though the base model crashed, it could make sense to move to modelsearch (debatable..). But if all models crash in modelsearch, I don't think any model should move to IIVsearch. Is there a way to make the tool stop earlier than reaching the RUVsearch?

**Comment by ZheHuang96** [comment]
Thank you so much for the details! Now I understand the error. It failed at the very beginning point. If my memory is correct, this error indicates there are zero predictions which can not be used to set proportional error model. We have a similar issue here https://github.com/pharmpy/pharmpy/issues/969 But actually, we have already added a zero protection in the start model to avoid this error. Maybe we need to improve it. 

About your question, I think we have the strategy to not propagate failed models but I am not so sure about it. @rikardn do you know our current strategy for it?

**Comment by joaoabr** [comment]
The base model is now running, after using better initial estimates (before they were completely off, I must say). What I think that could be improved is leading to the amd tool to stop earlier. In the case above, even though all models crashed from the beginning, an error only popped up during the ruvsearch.

**Comment by joaoabr** [comment]
We bumped into another case with this error. Even though the best structural model runs fine, the base model of IIV search crashes due to the fact that IIV_MAT is added. Then all IIVsearch executions crash, and the error only pops up when RUVmodel is executed:
`ValueError: Please check base_model.mod file to make sure ID, TIME, CWRES are in $TABLE.`

**Comment by stellabelin** [comment]
Hi! The `base_model.mod` is a model created by IIVSearch, if it fails it should of course not be propagated, it has been fixed in this commit: 83a2d10edd7d02ca4ba05b47a2e720537be97861. Could you send the .lst-files for the IIVSearch-candidates? We have seen cases where the base model fails but some of the candidates are successful.

**Comment by stellabelin** [comment]
This issue has been fixed, closing the issue.

**Comment by stellabelin** [comment]
I've also added an issue to assert passed models were successful: #1353
