### ISSUE TITLE
AttributeError("can\'t set attribute")

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1291]
After running with dataset16 (28OCT2022):
```
CL  = 0.4 #
V   = 10 #
MAT = 0.5 # 1/KA <- if oral

#run Automatic Model Development (AMD) tool
res <- run_amd(
    dataset_path,
    modeltype='pk_oral',
    cl_init= CL,
    vc_init= V,
    mat_init= MAT,
    categorical = "STUD",
    continuous = c("BW","ALB")
    )
```
the following appears:

```
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py:352: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
2022-10-28 12:31:37,189 - distributed.worker - WARNING - Compute Failed
Key:       ELIMINATION(MIX-FO-add_iivs-copy-update_inits-run0-7255f206-a2a6-4d6f-ac91-e583cd0a29b6
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7fb7756cddc0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7fb776407d00>, (<function _add_iiv_to_func at 0x7fb7752341f0>, 'absorption_delay', (<function _apply_transformation at 0x7fb7756ecf70>, ('ELIMINATION', 'MIX-FO-MM'), <function set_mixed_mm_fo_elimination at 0x7fb7b8ebc1f0>, (<function update_initial_estimates at 0x7fb779b180d0>, (<function _copy at 0x7fb775234160>, 'modelsearch_run18', (('ELIMINATION', 'MIX-FO-MM'),), <Pharmpy model object modelsearch_run2>))))))
kwargs:    {}
Exception: 'AttributeError("can\'t set attribute")'

<Client: 'inproc://172.17.0.7/336/1' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.7/336/10' processes=1 threads=12, memory=47.24 GiB>
OSError: [Errno 39] Directory not empty: '/tmp/tmpnui8fuk3'
Full stack:
OSError[Errno 39] Directory not empty: '/tmp/tmpnui8fuk3'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 251, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 205, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 68, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 51, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py\", line 827, in __exit__\n    self.cleanup()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py\", line 831, in cleanup\n    self._rmtree(self.name)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py\", line 813, in _rmtree\n    _shutil.rmtree(name, onerror=onerror)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/shutil.py\", line 722, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/shutil.py\", line 720, in rmtree\n    os.rmdir(path)\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3057, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2226, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2089, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py", line 92, in task
    return execute_model(model, context)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py", line 31, in execute_model
    model_with_correct_datapath = database.retrieve_model(model.name)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/baseclass.py", line 325, in retrieve_model
    return sn.retrieve_model()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/model_database/local_directory.py", line 307, in retrieve_model
    model = Model.create_model(path)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py", line 429, in create_model
    model = model_module.Model(code, path, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 149, in __init__
    statements, comp_map = parse_statements(self, control_stream)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py", line 88, in parse_statements
    comp = _compartmental_model(model, control_stream, sub.advan, sub.trans, des)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 304, in _compartmental_model
    dadt_dose.expression += sympy.Piecewise((rate, duration > t), (0, True))
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 154, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 251, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 205, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 68, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py", line 827, in __exit__
    self.cleanup()
  File "/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py", line 831, in cleanup
    self._rmtree(self.name)
  File "/miniconda/envs/r-reticulate/lib/python3.8/tempfile.py", line 813, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/miniconda/envs/r-reticulate/lib/python3.8/shutil.py", line 722, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/miniconda/envs/r-reticulate/lib/python3.8/shutil.py", line 720, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmpnui8fuk3'

pharmr version: 0.82.0
'0.82.0'
Pharmpy version: 0.82.0
```

Can you help?

**Comment by stellabelin** [comment]
Hi! The error above we discovered in another model, it was fixed in 5ea02191baca7b372d3abef4dbbf4cec7d8e8427 and will be in the next release!

**Comment by joaoabr** [comment]
Thanks! Same error found with another dataset (dataset6 29OCT2022)

**Comment by joaoabr** [comment]
also with datasets 3 and 5 (29OCT2022)

**Comment by stellabelin** [comment]
We now also have a test covering this code, added in 1f8e62310c447e6acbd2f9b95d885971415fbfca. Closing this issue as it has been fixed, please reopen if you still get issues!
