### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1293]
After running with dataset1 (29OCT2022):

```
res <- run_amd(
  dataset_path,
  modeltype='pk_iv',
  # search_space='PERIPHERALS(1)',
  # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
  cl_init= CL,
  vc_init= V,
  # mat_init=0.1,
  # occasion='VISI',
  categorical=c("SEX","RACE"),
  continuous=c("BMI","BSA")
)
```

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'
Full stack:
FileNotFoundError[Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 94, in run_amd\n    model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py\", line 248, in convert_model\n    new = nonmem.convert_model(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 97, in convert_model\n    nm_model = pharmpy.model.Model.create_model(StringIO(code))\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py\", line 429, in create_model\n    model = model_module.Model(code, path, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 149, in __init__\n    statements, comp_map = parse_statements(self, control_stream)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py\", line 88, in parse_statements\n    comp = _compartmental_model(model, control_stream, sub.advan, sub.trans, des)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 35, in _compartmental_model\n    dose = _dosing(model, control_stream, 1)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 549, in _dosing\n    return dosing(model.datainfo, dataset, dose_comp)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 556, in dosing\n    df = dataset()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 547, in dataset\n    return model._read_dataset(control_stream, raw=False)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 363, in _read_dataset\n    df = read_nonmem_dataset(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py\", line 252, in read_nonmem_dataset\n    file_io = NMTRANDataIO(path_or_io, ignore_character)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py\", line 26, in __init__\n    with open(str(filename_or_io), 'r', encoding='latin-1') as datafile:\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 94, in run_amd
    model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py", line 248, in convert_model
    new = nonmem.convert_model(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 97, in convert_model
    nm_model = pharmpy.model.Model.create_model(StringIO(code))
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py", line 429, in create_model
    model = model_module.Model(code, path, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 149, in __init__
    statements, comp_map = parse_statements(self, control_stream)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py", line 88, in parse_statements
    comp = _compartmental_model(model, control_stream, sub.advan, sub.trans, des)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 35, in _compartmental_model
    dose = _dosing(model, control_stream, 1)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 549, in _dosing
    return dosing(model.datainfo, dataset, dose_comp)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 556, in dosing
    df = dataset()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 547, in dataset
    return model._read_dataset(control_stream, raw=False)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 363, in _read_dataset
    df = read_nonmem_dataset(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py", line 252, in read_nonmem_dataset
    file_io = NMTRANDataIO(path_or_io, ignore_character)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py", line 26, in __init__
    with open(str(filename_or_io), 'r', encoding='latin-1') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'

pharmr version: 0.82.0
'0.82.0'
Pharmpy version: 0.82.0
```

**Comment by joaoabr** [comment]
Same issue with dataset2 (29OCT2022)

```
res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    cl_init= CL,
    vc_init= V,
    allometric_variable="WGT"
)
```

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'
Full stack:
FileNotFoundError[Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 94, in run_amd\n    model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py\", line 248, in convert_model\n    new = nonmem.convert_model(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 97, in convert_model\n    nm_model = pharmpy.model.Model.create_model(StringIO(code))\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py\", line 429, in create_model\n    model = model_module.Model(code, path, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 149, in __init__\n    statements, comp_map = parse_statements(self, control_stream)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py\", line 88, in parse_statements\n    comp = _compartmental_model(model, control_stream, sub.advan, sub.trans, des)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 35, in _compartmental_model\n    dose = _dosing(model, control_stream, 1)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 549, in _dosing\n    return dosing(model.datainfo, dataset, dose_comp)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 556, in dosing\n    df = dataset()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py\", line 547, in dataset\n    return model._read_dataset(control_stream, raw=False)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py\", line 363, in _read_dataset\n    df = read_nonmem_dataset(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py\", line 252, in read_nonmem_dataset\n    file_io = NMTRANDataIO(path_or_io, ignore_character)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py\", line 26, in __init__\n    with open(str(filename_or_io), 'r', encoding='latin-1') as datafile:\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 94, in run_amd
    model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/common.py", line 248, in convert_model
    new = nonmem.convert_model(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 97, in convert_model
    nm_model = pharmpy.model.Model.create_model(StringIO(code))
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/model.py", line 429, in create_model
    model = model_module.Model(code, path, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 149, in __init__
    statements, comp_map = parse_statements(self, control_stream)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/parsing.py", line 88, in parse_statements
    comp = _compartmental_model(model, control_stream, sub.advan, sub.trans, des)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 35, in _compartmental_model
    dose = _dosing(model, control_stream, 1)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 549, in _dosing
    return dosing(model.datainfo, dataset, dose_comp)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 556, in dosing
    df = dataset()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/advan.py", line 547, in dataset
    return model._read_dataset(control_stream, raw=False)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/model.py", line 363, in _read_dataset
    df = read_nonmem_dataset(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py", line 252, in read_nonmem_dataset
    file_io = NMTRANDataIO(path_or_io, ignore_character)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/dataset.py", line 26, in __init__
    with open(str(filename_or_io), 'r', encoding='latin-1') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rstudio/workspace/file.csv'

pharmr version: 0.82.0
'0.82.0'
Pharmpy version: 0.82.0

```

**Comment by joaoabr** [comment]
Same error with dataset8 (29OCT2022). The common element across datasets is the fact that they are iv.
