### ISSUE TITLE
Length of values (45) does not match length of index (47)

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1315]
After running run_amd with dataset1 (02NOV2022, virtual machine), already with Pharmpy 0.83.0.
Can you help?

```
#run Automatic Model Development (AMD) tool
res <- run_amd(
  dataset_path,
  modeltype='pk_iv',
  # search_space='PERIPHERALS(1)',
  # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
  cl_init= CL,
  vc_init= V,
  # mat_init=0.1,
  # occasion='VISI',
  categorical=c("SEX","RACE"),
  continuous=c("BMI","BSA")
)
```

```
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py:352: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
distributed.worker - WARNING - Compute Failed
Function:  post_process
args:      ('bic', None, <Pharmpy model object start>, <Pharmpy model object modelsearch_run1>, <Pharmpy model object modelsearch_run2>, <Pharmpy model object modelsearch_run3>, <Pharmpy model object modelsearch_run4>, <Pharmpy model object modelsearch_run5>, <Pharmpy model object modelsearch_run6>, <Pharmpy model object modelsearch_run7>, <Pharmpy model object modelsearch_run8>, <Pharmpy model object modelsearch_run9>, <Pharmpy model object modelsearch_run10>, <Pharmpy model object modelsearch_run11>, <Pharmpy model object modelsearch_run12>)
kwargs:    {}
Exception: ValueError('Length of values (45) does not match length of index (47)')

<Client: 'inproc://10.136.106.81/9928/1' processes=1 threads=10, memory=64.00 GiB>
<Client: 'inproc://10.136.106.81/9928/10' processes=1 threads=10, memory=64.00 GiB>
ValueError: Length of values (45) does not match length of index (47)
Full stack:
ValueErrorLength of values (45) does not match length of index (47)c("  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 251, in _run_modelsearch\n    res = run_tool(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\run.py\", line 205, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\workflows\\execute.py\", line 68, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\workflows\\dispatchers\\local_dask.py\", line 51, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\client.py\", line 2704, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\client.py\", line 2018, in gather\n    return self.sync(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\client.py\", line 859, in sync\n    return sync(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\utils.py\", line 326, in sync\n    raise exc.with_traceback(tb)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\utils.py\", line 309, in f\n    result[0] = yield future\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 762, in run\n    value = future.result()\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\distributed\\client.py\", line 1883, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\modelsearch\\tool.py\", line 104, in post_process\n    res = create_results(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\common.py\", line 39, in create_results\n    summary_individuals, summary_individuals_count = summarize_tool_individuals(\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\common.py\", line 111, in summarize_tool_individuals\n    summary_individuals = summarize_individuals(models)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\summarize_individuals.py\", line 68, in summarize_individuals\n    df = pd.concat(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\util\\_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 347, in concat\n    op = _Concatenator(\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\reshape\\concat.py\", line 401, in __init__\n    objs = list(objs)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\summarize_individuals.py\", line 70, in <lambda>\n    lambda model: groupedByIDAddColumnsOneModel(modelsDict, model),\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\summarize_individuals.py\", line 147, in groupedByIDAddColumnsOneModel\n    'predicted_dofv': predicted_dofv(model),\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\summarize_individuals.py\", line 126, in predicted_dofv\n    return _predicted(predict_influential_individuals, model, 'dofv')\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\summarize_individuals.py\", line 111, in _predicted\n    predicted = predict(model, model.modelfit_results)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\funcs\\ml.py\", line 229, in predict_influential_individuals\n    df = pd.DataFrame({'dofv': output, 'influential': output > cutoff}, index=get_ids(model))\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\frame.py\", line 636, in __init__\n    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\internals\\construction.py\", line 502, in dict_to_mgr\n    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\internals\\construction.py\", line 125, in arrays_to_mgr\n    arrays = _homogenize(arrays, index, dtype)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\internals\\construction.py\", line 628, in _homogenize\n    com.require_length_match(val, index)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pandas\\core\\common.py\", line 557, in require_length_match\n    raise ValueError(\n")Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py", line 154, in run_amd
    subresults = func(next_model)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py", line 251, in _run_modelsearch
    res = run_tool(
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run.py", line 205, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\execute.py", line 68, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 2704, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 2018, in gather
    return self.sync(
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 859, in sync
    return sync(
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\utils.py", line 309, in f
    result[0] = yield future
  File "C:\PROGRA~1\Python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 1883, in _gather
    raise exception.with_traceback(traceback)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\modelsearch\tool.py", line 104, in post_process
    res = create_results(
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py", line 39, in create_results
    summary_individuals, summary_individuals_count = summarize_tool_individuals(
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py", line 111, in summarize_tool_individuals
    summary_individuals = summarize_individuals(models)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py", line 68, in summarize_individuals
    df = pd.concat(
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\reshape\concat.py", line 347, in concat
    op = _Concatenator(
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\reshape\concat.py", line 401, in __init__
    objs = list(objs)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py", line 70, in <lambda>
    lambda model: groupedByIDAddColumnsOneModel(modelsDict, model),
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py", line 147, in groupedByIDAddColumnsOneModel
    'predicted_dofv': predicted_dofv(model),
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py", line 126, in predicted_dofv
    return _predicted(predict_influential_individuals, model, 'dofv')
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\summarize_individuals.py", line 111, in _predicted
    predicted = predict(model, model.modelfit_results)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\funcs\ml.py", line 229, in predict_influential_individuals
    df = pd.DataFrame({'dofv': output, 'influential': output > cutoff}, index=get_ids(model))
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\internals\construction.py", line 125, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\internals\construction.py", line 628, in _homogenize
    com.require_length_match(val, index)
  File "C:\PROGRA~1\Python39\lib\site-packages\pandas\core\common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (45) does not match length of index (47)

pharmr version: 0.83.0
'0.83.0'
Pharmpy version: 0.83.0
```

**Comment by stellabelin** [comment]
Hi! This looks like it's related to #1139. Adding it to high priority.

**Comment by stellabelin** [comment]
Marking this as duplicate (of #1139), closing the issue.
