### ISSUE TITLE
Node Compartment(CENTRAL, dose=Bolus(AMT)) is not in the graph

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1316]
After running run_amd with dataset3 (02NOV2022, virtual machine), already with Pharmpy 0.83.0.
Can you help?

```
#initial parameters
CL  = 0.50 #
V   = 3 #
MAT = 0.1 # 1/KA <- if oral

#run Automatic Model Development (AMD) tool
res <- run_amd(
    dataset_path,
    modeltype='pk_oral',
    # search_space='PERIPHERALS(1)',
    # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
    cl_init= CL,
    vc_init= V,
    mat_init= MAT,
    # occasion='VISI'
    continuous="AGE",
    categorical="DOSE"
)
```

```
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py:352: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run14: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run31: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run32: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run33: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run36: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run37: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run34: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run35: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run105: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run104: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run30: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run39: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run16: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run84: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run107: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\common.py:17: UserWarning: modelsearch_run13: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
distributed.worker - WARNING - Compute Failed
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x00000225B42F5DC0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x00000225B36BC610>, (<function _add_iiv_to_func at 0x00000225B429C8B0>, 'absorption_delay', (<function _apply_transformation at 0x00000225B429C670>, ('ABSORPTION', 'ZO'), <function set_zero_order_absorption at 0x0000022599B3DEE0>, (<function update_initial_estimates at 0x00000225B2D43040>, (<function _copy at 0x00000225B429C820>, 'modelsearch_run69', (('ABSORPTION', 'ZO'),), <Pharmpy model object modelsearch_run12>))))))
kwargs:    {}
Exception: KeyError('Node Compartment(CENTRAL, dose=Bolus(AMT)) is not in the graph')

<Client: 'inproc://10.136.106.81/12632/1' processes=1 threads=10, memory=64.00 GiB>
<Client: 'inproc://10.136.106.81/12632/10' processes=1 threads=10, memory=64.00 GiB>
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\abrantj1\\AppData\\Local\\Temp\\3\\tmpl6lj1thn\\NONMEM_run_modelsearch_run104-ed148668-5aad-11ed-86ae-005056ba1d39\\x\\FCON'
Full stack:
NotADirectoryError[WinError 267] The directory name is invalid: 'C:\\Users\\abrantj1\\AppData\\Local\\Temp\\3\\tmpl6lj1thn\\NONMEM_run_modelsearch_run104-ed148668-5aad-11ed-86ae-005056ba1d39\\x\\FCON'c("  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 251, in _run_modelsearch\n    res = run_tool(\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\tools\\run.py\", line 205, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\workflows\\execute.py\", line 68, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\workflows\\dispatchers\\local_dask.py\", line 51, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\internals\\fs\\tmp.py\", line 76, in __exit__\n    self.cleanup()\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\internals\\fs\\tmp.py\", line 80, in cleanup\n    self._rmtree(self.name)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\internals\\fs\\tmp.py\", line 62, in _rmtree\n    shutil.rmtree(name, onerror=onerror)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 740, in rmtree\n    return _rmtree_unsafe(path, onerror)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 613, in _rmtree_unsafe\n    _rmtree_unsafe(fullname, onerror)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 613, in _rmtree_unsafe\n    _rmtree_unsafe(fullname, onerror)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 618, in _rmtree_unsafe\n    onerror(os.unlink, fullname, sys.exc_info())\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\internals\\fs\\tmp.py\", line 54, in onerror\n    cls._rmtree(path)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\site-packages\\pharmpy\\internals\\fs\\tmp.py\", line 62, in _rmtree\n    shutil.rmtree(name, onerror=onerror)\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 740, in rmtree\n    return _rmtree_unsafe(path, onerror)\n", 
"  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 599, in _rmtree_unsafe\n    onerror(os.scandir, path, sys.exc_info())\n", "  File \"C:\\PROGRA~1\\Python39\\lib\\shutil.py\", line 596, in _rmtree_unsafe\n    with os.scandir(path) as scandir_it:\n")Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\networkx\relabel.py", line 154, in _relabel_inplace
    G.add_node(new, **G.nodes[old])
  File "C:\PROGRA~1\Python39\lib\site-packages\networkx\classes\reportviews.py", line 187, in __getitem__
    return self._nodes[n]
KeyError: Compartment(CENTRAL, dose=Bolus(AMT))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 2704, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 2018, in gather
    return self.sync(
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 859, in sync
    return sync(
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\utils.py", line 309, in f
    result[0] = yield future
  File "C:\PROGRA~1\Python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\PROGRA~1\Python39\lib\site-packages\distributed\client.py", line 1883, in _gather
    raise exception.with_traceback(traceback)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\modelsearch\algorithms.py", line 224, in _apply_transformation
    func(model)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\modeling\odes.py", line 1001, in set_zero_order_absorption
    _add_zero_order_absorption(model, dose.amount, cs.dosing_compartment, 'MAT', lag_time)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\modeling\odes.py", line 1272, in _add_zero_order_absorption
    cb.set_lag_time(model.statements.ode_system.dosing_compartment, lag_time)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\model\statements.py", line 605, in set_lag_time
    nx.relabel_nodes(self._g, mapping, copy=False)
  File "C:\PROGRA~1\Python39\lib\site-packages\networkx\relabel.py", line 121, in relabel_nodes
    return _relabel_inplace(G, m)
  File "C:\PROGRA~1\Python39\lib\site-packages\networkx\relabel.py", line 156, in _relabel_inplace
    raise KeyError(f"Node {old} is not in the graph") from e
KeyError: 'Node Compartment(CENTRAL, dose=Bolus(AMT)) is not in the graph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\abrantj1\\AppData\\Local\\Temp\\3\\tmpl6lj1thn\\NONMEM_run_modelsearch_run104-ed148668-5aad-11ed-86ae-005056ba1d39\\x\\FCON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 50, in onerror
    os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\abrantj1\\AppData\\Local\\Temp\\3\\tmpl6lj1thn\\NONMEM_run_modelsearch_run104-ed148668-5aad-11ed-86ae-005056ba1d39\\x\\FCON'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py", line 154, in run_amd
    subresults = func(next_model)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\amd\run.py", line 251, in _run_modelsearch
    res = run_tool(
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run.py", line 205, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\execute.py", line 68, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 76, in __exit__
    self.cleanup()
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 80, in cleanup
    self._rmtree(self.name)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 62, in _rmtree
    shutil.rmtree(name, onerror=onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 54, in onerror
    cls._rmtree(path)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\internals\fs\tmp.py", line 62, in _rmtree
    shutil.rmtree(name, onerror=onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\PROGRA~1\Python39\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\abrantj1\\AppData\\Local\\Temp\\3\\tmpl6lj1thn\\NONMEM_run_modelsearch_run104-ed148668-5aad-11ed-86ae-005056ba1d39\\x\\FCON'

pharmr version: 0.83.0
'0.83.0'
Pharmpy version: 0.83.0
```

**Comment by joaoabr** [comment]
Done.

**Comment by joaoabr** [comment]
Hi. We do not have this error in our Improve environment, so there is no need to prioritize this issue.

**Comment by rikardn** [comment]
Since we haven't seen this issue in a long while and the code that implemented this has changed I will close the issue.
