### ISSUE TITLE
\'NoneType\' object has no attribute \'empty\'

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1320]
After running run_amd with dataset2 (Phase 3/dataset2_03NOV2022), with Pharmpy 0.83.0.
Can you help?

```
txt> CL  = 0.05 
txt> V   = 5 
txt> res <- run_amd(
txt+     dataset_path,
txt+     modeltype='pk_iv',
txt+     search_space='PERIPHERALS([1,2]);ELIMINATION([MM,MIX-FO-MM])',
txt+     order=c('structural', 'iivsearch', 'residual', 'iovsearch','allometry', 'covariates'),
txt+     cl_init= CL,
txt+     vc_init= V,
txt+     allometric_variable = c('WGT'),
txt+     categorical = c('DIS'),
txt+     occasion='OCC'
txt+     # mat_init=0.1,
txt+     # occasion='VISI',
txt+ )
```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run4.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run7.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run6.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run5.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run12: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run11.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run12.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run10.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File modelsearch_run9.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run1.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run13.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run13.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run15.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run15.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run12.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run12.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run16.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run16.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File time_varying2_2.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File time_varying2_2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File base_2.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File base_2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File time_varying3_2.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File time_varying3_2.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py:42: UserWarning: base CWRES model of iteration 2 failed.
  warnings.warn(f'base CWRES model of iteration {iteration} failed.')
2022-11-04 04:43:07,897 - distributed.worker - WARNING - Compute Failed
Key:       results2
Function:  post_process
args:      (<pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f96a15f5d30>, <Pharmpy model object best_ruvsearch_1>, <Pharmpy model object base_2>, <Pharmpy model object power_2>, <Pharmpy model object combined_2>, <Pharmpy model object time_varying1_2>, <Pharmpy model object time_varying2_2>, <Pharmpy model object time_varying3_2>)
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'empty\'")'

2022-11-04 04:43:07,904 - distributed.worker - WARNING - Compute Failed
Key:       start_ruvsearch-results
Function:  execute_task
args:      ((<function _results at 0x7f96d2285ee0>, (<function start at 0x7f96a12548b0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f96a15f5d30>, <Pharmpy model object iivsearch_run20>, 4, 0.05, None)))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'empty\'")'

<Client: 'inproc://172.17.0.5/337/1' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/337/10' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/337/19' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/337/28' processes=1 threads=12, memory=47.24 GiB>
AttributeError: 'NoneType' object has no attribute 'empty'
Full stack:
AttributeError'NoneType' object has no attribute 'empty'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 281, in _run_ruvsearch\n    res = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 205, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 68, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 51, in run\n    res = client.get(dsk_optimized, 'results')\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3096, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2265, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2128, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 156, in start\n    res, best_model, selected_model_name = call_workflow(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/call.py\", line 40, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2265, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2128, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 225, in post_process\n    best_model_unfitted, selected_model_name = _create_best_model(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 365, in _create_best_model\n    if not res.cwres_models.empty and any(res.cwres_models['dofv'] > cutoff):\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 154, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 281, in _run_ruvsearch
    res = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 205, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 68, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3096, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2265, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2128, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 156, in start
    res, best_model, selected_model_name = call_workflow(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/call.py", line 40, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2265, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2128, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 225, in post_process
    best_model_unfitted, selected_model_name = _create_best_model(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 365, in _create_best_model
    if not res.cwres_models.empty and any(res.cwres_models['dofv'] > cutoff):
AttributeError: 'NoneType' object has no attribute 'empty'

pharmr version: 0.83.0
'0.83.0'
Pharmpy version: 0.83.0
Session restored from your saved work on 2022-Nov-04 06:43:09 UTC (7 hours ago)

```

**Comment by joaoabr** [comment]
Hi. We got an identical error with another dataset (dataset4_04NOV2022):

```
txt> CL  = 0.5 #
txt> V   = 4 #
txt> 
txt> #run Automatic Model Development (AMD) tool
txt> res <- run_amd(
txt+     dataset_path,
txt+     modeltype='pk_iv',
txt+     # search_space='PERIPHERALS(1)',
txt+     # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
txt+     cl_init= CL,
txt+     vc_init= V
txt+     # mat_init=0.1,
txt+     # occasion='VISI'
txt+ )
```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py:352: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run5: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run4: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run11: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:17: UserWarning: modelsearch_run12: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run5.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run5.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run41.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File iivsearch_run41.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File base_1.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File base_1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File combined_1.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File combined_1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File power_1.lst does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py:101: UserWarning: File power_1.ext does not exist
  warnings.warn(f'File {basename.with_suffix(suffix)} does not exist')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/results.py:42: UserWarning: base CWRES model of iteration 1 failed.
  warnings.warn(f'base CWRES model of iteration {iteration} failed.')
2022-11-04 23:37:32,655 - distributed.worker - WARNING - Compute Failed
Key:       results1
Function:  post_process
args:      (<pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f6337dc8970>, <Pharmpy model object iivsearch_run68>, <Pharmpy model object base_1>, <Pharmpy model object IIV_on_RUV_1>, <Pharmpy model object power_1>, <Pharmpy model object combined_1>, <Pharmpy model object time_varying1_1>, <Pharmpy model object time_varying2_1>, <Pharmpy model object time_varying3_1>)
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'empty\'")'

2022-11-04 23:37:32,662 - distributed.worker - WARNING - Compute Failed
Key:       start_ruvsearch-results
Function:  execute_task
args:      ((<function _results at 0x7f632cb6faf0>, (<function start at 0x7f6336afe700>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f6337dc8970>, <Pharmpy model object iivsearch_run68>, 4, 0.05, None)))
kwargs:    {}
Exception: 'AttributeError("\'NoneType\' object has no attribute \'empty\'")'

<Client: 'inproc://172.17.0.5/336/1' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/336/10' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/336/19' processes=1 threads=12, memory=47.24 GiB>
<Client: 'inproc://172.17.0.5/336/28' processes=1 threads=12, memory=47.24 GiB>
AttributeError: 'NoneType' object has no attribute 'empty'
Full stack:
AttributeError'NoneType' object has no attribute 'empty'c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 154, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 281, in _run_ruvsearch\n    res = run_tool('ruvsearch', model, path=path / 'ruvsearch')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 177, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 205, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 68, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 51, in run\n    res = client.get(dsk_optimized, 'results')\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3096, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2265, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2128, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 156, in start\n    res, best_model, selected_model_name = call_workflow(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/call.py\", line 40, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2265, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2128, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 225, in post_process\n    best_model_unfitted, selected_model_name = _create_best_model(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py\", line 365, in _create_best_model\n    if not res.cwres_models.empty and any(res.cwres_models['dofv'] > cutoff):\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 154, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 281, in _run_ruvsearch
    res = run_tool('ruvsearch', model, path=path / 'ruvsearch')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 177, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 205, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 68, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 51, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3096, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2265, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2128, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 156, in start
    res, best_model, selected_model_name = call_workflow(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/call.py", line 40, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2265, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2128, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 225, in post_process
    best_model_unfitted, selected_model_name = _create_best_model(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/ruvsearch/tool.py", line 365, in _create_best_model
    if not res.cwres_models.empty and any(res.cwres_models['dofv'] > cutoff):
AttributeError: 'NoneType' object has no attribute 'empty'

pharmr version: 0.83.0
'0.83.0'
Pharmpy version: 0.83.0
```

**Comment by stellabelin** [comment]
Hi! This looks like it's happening due to the fact that the base model is failing and that no cwres models have been added. It also looks like there are multiple .lst/.ext-files that do not exists, both in RUVSearch and IIVSearch. Have the issue with the NONMEM runs on your side been fixed? What I'm thinking otherwise is that maybe there is a delay when Pharmpy is retrieving the files. Adding this to high priority.

**Comment by stellabelin** [comment]
I've added an issue to account for delay: #1321

**Comment by joaoabr** [comment]
Potentially solved on our side by changing the grid definitions. To be checked.

**Comment by rikardn** [comment]
I assume this has been fixed by the delay and the changes on your grid. Feel free to open a new issue if this problems comes back.
