### ISSUE TITLE
run_amd crashes during iivsearch

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1325]
run_amd crashes with the error message below during iivsearch. Results.csv not produced (model 1). 
Do you recognize the error?

res <- run_amd(
    dataset_path,
    modeltype='pk_iv',
    cl_init= CL,
    vc_init= V,
    categorical=c("SEX","RACE"),
    continuous=c("BMI","BSA")
)

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 40329 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 40046 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 33584 instead
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/node.py:183: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 37207 instead
  warnings.warn(
2022-08-26 23:43:22,672 - distributed.worker - WARNING - Compute Failed
Key:       copy-remove_eta-update_description-update_inits-run49-2fdf917d-4906-44eb-83ba-084646f0e292
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7f179e2e2dc0>, (<function update_description at 0x7f17a5e5c280>, (<function remove_eta at 0x7f17a5e5c0d0>, ['eta_vc', 'ETA_QP1', 'ETA_VP2'], (<function update_initial_estimates at 0x7f17a5fbd5e0>, (<function copy at 0x7f17a5e5c1f0>, 'iivsearch_no_of_etas_candidate50', <Pharmpy model object base_model>))))))
kwargs:    {}
Exception: "OSError(12, 'Cannot allocate memory')"

2022-08-26 23:43:22,816 - distributed.worker - WARNING - Compute Failed
Key:       start_iiv-results
Function:  execute_task
args:      ((<function _results at 0x7f17a5e5c4c0>, (<function start at 0x7f17a5e5c3a0>, <Pharmpy model object modelsearch_candidate9>, 'brute_force', 'fullblock', 'bic', None)))
kwargs:    {}
Exception: "OSError(12, 'Cannot allocate memory')"

<Client: 'inproc://172.17.0.15/328/1' processes=1 threads=6, memory=15.49 GiB>
<Client: 'inproc://172.17.0.15/328/10' processes=1 threads=6, memory=15.49 GiB>
<Client: 'inproc://172.17.0.15/328/19' processes=1 threads=6, memory=15.49 GiB>
<Client: 'inproc://172.17.0.15/328/29' processes=1 threads=6, memory=15.49 GiB>
OSError: [Errno 12] Cannot allocate memory
Full stack:
<environment>[Errno 12] Cannot allocate memoryc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py\", line 160, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py\", line 211, in _run_iiv\n    res_iiv = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 167, in run_tool\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 58, in execute_workflow\n    res = dispatcher.run(workflow)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 40, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3036, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2210, in gather\n    return self.sync(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2073, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/iivsearch/tool.py\", line 104, in start\n    next_res = call_workflow(wf, f'results_{algorithm}')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 133, in call_workflow\n    res = client.gather(futures)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2210, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 338, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 405, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 378, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2073, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py\", line 74, in task\n    return execute_model(model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py\", line 35, in execute_model\n    result = subprocess.run(\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py\", line 493, in run\n    with Popen(*popenargs, **kwargs) as process:\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py\", line 858, in __init__\n    self._execute_child(args, executable, preexec_fn, close_fds,\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py\", line 1639, in _execute_child\n    self.pid = _posixsubprocess.fork_exec(\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py", line 160, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run_amd.py", line 211, in _run_iiv
    res_iiv = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 167, in run_tool
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 58, in execute_workflow
    res = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 40, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3036, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2210, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2073, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/iivsearch/tool.py", line 104, in start
    next_res = call_workflow(wf, f'results_{algorithm}')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 133, in call_workflow
    res = client.gather(futures)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2210, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2073, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/modelfit/tool.py", line 74, in task
    return execute_model(model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/plugins/nonmem/run.py", line 35, in execute_model
    result = subprocess.run(
  File "/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/miniconda/envs/r-reticulate/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory

pharmr version: 0.75.0
'0.75.0'
Pharmpy version: 0.75.0
Session restored from your saved work on 2022-Aug-28 12:01:24 UTC (1 day ago)

**Comment by rikardn** [comment]
The code where this was raised has been changed over the year and given the difficulty of reproducing such a problem I will close now. Please feel free to open new issues for this or similar issues in newer versions of Pharmpy.
