### ISSUE TITLE
Also return results in retrieve_models and retrieve_final_model

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1370]
When `modelfit_results` have been split from the `Model`-object, `retrieve_models` and `retrieve_final_model` will only return the `Model`-object. To allow easier piping in e.g. AMD or general scripting, those functions could return tuples with model and result.

**Comment by rikardn** [comment]
Example error message for the lazy evaluation shenanigans:

```
object 'rs1' not foundFull stack:
IndexErroronly integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices  File "/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 935, in __getitem__
    raise IndexError(
Traceback (most recent call last):
  File "/home/rikard/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 935, in __getitem__
    raise IndexError(
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by stellabelin** [comment]
Closing, in tools we now use model entries.
