### ISSUE TITLE
Add check if covariate for allometric_variable is not available in the dataset

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#1378]
### Feature request

The amd tool (pharmpy 0.85.0) currently crashes if an incorrect variable name is given in allometric_variable. However, this only happens when the allometry module kicks in (example dataset11_27NOV2022), and not initially. Consider adding an initial check which lead to the tool crashing even before the initial model is estimated.

```
res <- run_amd(
  dataset_path,
  modeltype='pk_oral',
  # search_space='PERIPHERALS(1)',
  # order=c('structural', 'iivsearch', 'residual', 'iovsearch', 'allometry', 'covariates'),
  search_space = "LET(CATEGORICAL,[SEX]);LET(CONTINUOUS,[AGE])",
  cl_init= CL,
  vc_init= V,
  mat_init= MAT,
  # occasion='VISI',
  allometric_variable="WGT"
)

```

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
<Client: 'inproc://172.17.0.20/337/1' processes=3 threads=9, memory=126.99 GiB>
<Client: 'inproc://172.17.0.20/337/16' processes=3 threads=9, memory=126.99 GiB>
<Client: 'inproc://172.17.0.20/337/39' processes=3 threads=9, memory=126.99 GiB>
<Client: 'inproc://172.17.0.20/337/60' processes=3 threads=9, memory=126.99 GiB>
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py:367: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run74: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run76: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run75: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run73: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run139: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run137: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
ValueError: Invalid `allometric_variable`: got `WGT`, free symbols must be a subset of ['AGE', 'ALB', 'AMT', 'BLQ', 'BMI', 'BSA', 'BTYPE4', 'BTYPE5', 'BTYPE6', 'BTYPE7', 'BTYPE8', 'BTYPE9', 'BW', 'C', 'CENT', 'DAY', 'DOSE', 'DOSEWT', 'DUR', 'DV', 'EVID', 'ID', 'IGNFLG', 'LBW', 'LDV', 'NDAY', 'NTIM', 'RACE', 'RATE', 'SEX', 'STUD', 'SUBJ', 'TAD', 'TIME', 'TYPE'].
Full stack:
ValueErrorInvalid `allometric_variable`: got `WGT`, free symbols must be a subset of ['AGE', 'ALB', 'AMT', 'BLQ', 'BMI', 'BSA', 'BTYPE4', 'BTYPE5', 'BTYPE6', 'BTYPE7', 'BTYPE8', 'BTYPE9', 'BW', 'C', 'CENT', 'DAY', 'DOSE', 'DOSEWT', 'DUR', 'DV', 'EVID', 'ID', 'IGNFLG', 'LBW', 'LDV', 'NDAY', 'NTIM', 'RACE', 'RATE', 'SEX', 'STUD', 'SUBJ', 'TAD', 'TIME', 'TYPE'].c("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 185, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 356, in _run_allometry\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 178, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 194, in run_tool_with_name\n    validate_input(*args, **tool_options)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py\", line 42, in _wrapped\n    return fn(*args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/signature.py\", line 50, in _wrapped\n    return fn(*permuted)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/allometry/tool.py\", line 141, in validate_input\n    raise ValueError(\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 185, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 356, in _run_allometry
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 178, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 194, in run_tool_with_name
    validate_input(*args, **tool_options)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/type.py", line 42, in _wrapped
    return fn(*args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/internals/fn/signature.py", line 50, in _wrapped
    return fn(*permuted)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/allometry/tool.py", line 141, in validate_input
    raise ValueError(
ValueError: Invalid `allometric_variable`: got `WGT`, free symbols must be a subset of ['AGE', 'ALB', 'AMT', 'BLQ', 'BMI', 'BSA', 'BTYPE4', 'BTYPE5', 'BTYPE6', 'BTYPE7', 'BTYPE8', 'BTYPE9', 'BW', 'C', 'CENT', 'DAY', 'DOSE', 'DOSEWT', 'DUR', 'DV', 'EVID', 'ID', 'IGNFLG', 'LBW', 'LDV', 'NDAY', 'NTIM', 'RACE', 'RATE', 'SEX', 'STUD', 'SUBJ', 'TAD', 'TIME', 'TYPE'].

pharmr version: 0.85.0
```

**Comment by stellabelin** [comment]
Hi! Thanks for reporting, I agree we should check this! @pharmpy-dev-123, could this be done similarly to #1357?

**Comment by pharmpy-dev-123** [comment]
@stellabelin Yes!
