### ISSUE TITLE
Cannot convert expression to float

### ISSUE THREAD

**Issue by zrinkaduvnjak** [pharmpy/pharmpy#1477]
### Bug report

Hi,

I was running the full amd tool with pharmr version 0.86.0 and during the model search, I got this error:

TypeError: Cannot convert expression to float
Full stack:
TypeErrorCannot convert expression to floatc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 198, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 295, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 178, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 206, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 71, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 52, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3122, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2291, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 769, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2154, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py\", line 28, in update_initial_estimates\n    update_inits(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py\", line 42, in update_inits\n    parameter_estimates = _move_est_close_to_bounds(model, parameter_estimates)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py\", line 52, in _move_est_close_to_bounds\n    sdcorr = rvs.parameters_sdcorr(est)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/random_variables.py\", line 735, in parameters_sdcorr\n    sigma = np.array(sigma_sym.subs(values)).astype(np.float64)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/sympy/core/expr.py\", line 351, in __float__\n    raise TypeError(\"Cannot convert expression to float\")\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 198, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 295, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 178, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 206, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 71, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 52, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3122, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2291, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2154, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py", line 28, in update_initial_estimates
    update_inits(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py", line 42, in update_inits
    parameter_estimates = _move_est_close_to_bounds(model, parameter_estimates)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py", line 52, in _move_est_close_to_bounds
    sdcorr = rvs.parameters_sdcorr(est)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/random_variables.py", line 735, in parameters_sdcorr
    sigma = np.array(sigma_sym.subs(values)).astype(np.float64)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float

pharmr version: 0.86.0
'0.86.0'
Pharmpy version: 0.86.0

**Comment by rikardn** [comment]
Thanks for reporting this. The `update_inits` function seem to crash on a model. Is it possible to find which model it couldn't update? Perhaps some parameter estimates are bad for that model.

**Comment by zrinkaduvnjak** [comment]
Hi,
we will share the content of amd_dir folder.

**Comment by SylvieRetout** [comment]
Hi,

I was also running the same version of pharmr 0.86.0 on another example and I am now facing the same issue as reported above, with the error message reported below. Could you please have a look and go back to us?
Thanks, Sylvie


/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run97: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run99: Could not update initial estimates, using original estimates
  warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2023-02-14 01:01:39,968 - distributed.worker - WARNING - Compute Failed
Key:       PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-2e3cf5e8-3ee1-4e22-a506-d94fc82fb08d
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x7fddb501a040>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7fdd9f263e50>, (<function _add_iiv_to_func at 0x7fdd9ff86e50>, 'absorption_delay', (<function _apply_transformation at 0x7fdd9ff86f70>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7fddf9ba0430>, n=1), (<function update_initial_estimates at 0x7fddf9afc310>, (<function _copy at 0x7fdd9ff864c0>, 'modelsearch_run101', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7fdd9ff868b0>, <Pharmpy model object modelsearch_run30>, <Pharmpy model object modelsearch_run49>)))))))
kwargs:    {}
Exception: "TypeError('Cannot convert expression to float')"

<Client: 'inproc://172.17.0.8/336/1' processes=3 threads=9, memory=46.99 GiB>
<Client: 'inproc://172.17.0.8/336/16' processes=3 threads=9, memory=46.99 GiB>
TypeError: Cannot convert expression to float
Full stack:
TypeErrorCannot convert expression to floatc("  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 198, in run_amd\n    subresults = func(next_model)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py\", line 295, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 178, in run_tool\n    return run_tool_with_name(name, tool, *args, **kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py\", line 206, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=database)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py\", line 71, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 52, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 3122, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2291, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 339, in sync\n    return sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 406, in sync\n    raise exc.with_traceback(tb)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py\", line 379, in f\n    result = yield future\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py\", line 769, in run\n    value = future.result()\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py\", line 2154, in _gather\n    raise exception.with_traceback(traceback)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py\", line 28, in update_initial_estimates\n    update_inits(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py\", line 42, in update_inits\n    parameter_estimates = _move_est_close_to_bounds(model, parameter_estimates)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py\", line 52, in _move_est_close_to_bounds\n    sdcorr = rvs.parameters_sdcorr(est)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/random_variables.py\", line 735, in parameters_sdcorr\n    sigma = np.array(sigma_sym.subs(values)).astype(np.float64)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.8/site-packages/sympy/core/expr.py\", line 351, in __float__\n    raise TypeError(\"Cannot convert expression to float\")\n"
)Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 198, in run_amd
    subresults = func(next_model)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/amd/run.py", line 295, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 178, in run_tool
    return run_tool_with_name(name, tool, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/run.py", line 206, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=database)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/execute.py", line 71, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 52, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 3122, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2291, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/distributed/client.py", line 2154, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py", line 28, in update_initial_estimates
    update_inits(
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py", line 42, in update_inits
    parameter_estimates = _move_est_close_to_bounds(model, parameter_estimates)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/modeling/update_inits.py", line 52, in _move_est_close_to_bounds
    sdcorr = rvs.parameters_sdcorr(est)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/model/random_variables.py", line 735, in parameters_sdcorr
    sigma = np.array(sigma_sym.subs(values)).astype(np.float64)
  File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float

pharmr version: 0.86.0
'0.86.0'
Pharmpy version: 0.86.0
Session restored from your saved work on 2023-Feb-14 15:07:04 UTC (23 hours ago)

**Comment by stellabelin** [comment]
Hi! Thanks for reporting! This seems similar to #1117, when this happened it was due to the fact that the .ext-file was incomplete, but there should already be a workaround in place for this. I'll need to look further into the run in question to double check, I can do so this week.

**Comment by stellabelin** [comment]
Hi again! I've looked at your issue and cannot reproduce it but I get a warning in the same row for one of the candidates when I try 0.86.0. If it's the same cause, the newest release (0.90.0) should have fixed it. If you want I could dig a little further, but then: @zrinkaduvnjak could you copy the full message? Just above the error message you posted it should be something like: 

```
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run97: Could not update initial estimates, using original estimates
warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/common.py:21: UserWarning: modelsearch_run99: Could not update initial estimates, using original estimates
warnings.warn(f'{model.name}: Could not update initial estimates, using original estimates')
2023-02-14 01:01:39,968 - distributed.worker - WARNING - Compute Failed
Key: PERIPHERALS(1)-add_iivs-choose_best_model-copy-update_inits-run0-2e3cf5e8-3ee1-4e22-a506-d94fc82fb08d
Function: execute_task
args: ((<function retrieve_from_database_or_execute_model_with_tool..task at 0x7fddb501a040>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7fdd9f263e50>, (<function _add_iiv_to_func at 0x7fdd9ff86e50>, 'absorption_delay', (<function _apply_transformation at 0x7fdd9ff86f70>, ('PERIPHERALS', 1), functools.partial(<function set_peripheral_compartments at 0x7fddf9ba0430>, n=1), (<function update_initial_estimates at 0x7fddf9afc310>, (<function _copy at 0x7fdd9ff864c0>, 'modelsearch_run101', (('PERIPHERALS', 1),), (<function _get_best_model at 0x7fdd9ff868b0>, , )))))))
kwargs: {}
Exception: "TypeError('Cannot convert expression to float')"

<Client: 'inproc://172.17.0.8/336/1' processes=3 threads=9, memory=46.99 GiB>
<Client: 'inproc://172.17.0.8/336/16' processes=3 threads=9, memory=46.99 GiB>
```
(copied from Sylvie's example). It contains information regarding which candidate model it refers to, then I can confirm whether it's the same model that I could get a similar warning for.

**Comment by MahmAbdelwahab** [comment]
I am also getting same error  using Moxonidine dataset and following command  pharmpy :
run10.mod -covariates=AGE,SEX,NYHA,WT,ACE,DIG,CRCL -categorical=SEX,NYHA,ACE,DIG -check -dir=frem_run10_log_mu -log=WT -bipp -force_posdef_covmatrix -mu

> Traceback (most recent call last):
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/bin/pharmpy", line 8, in <module>
    sys.exit(run())
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/__main__.py", line 8, in run
    main(args)
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/cli.py", line 2153, in main
    args.func(args)
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/cli.py", line 753, in results_frem
    res = psn_frem_results(
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 1083, in psn_frem_results
    res = calculate_results(
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 426, in calculate_results
    res = calculate_results_using_bipp(
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 953, in calculate_results_using_bipp
    res = calculate_results_from_samples(
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 640, in calculate_results_from_samples
    estimated_covbase = _calculate_covariate_baselines(frem_model, frem_model_results, covariates)
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 900, in _calculate_covariate_baselines
    df = res.individual_estimates.apply(fn, axis=1, result_type='expand')
  File "/SciPy-bundle/2023.02-foss-2018b/lib/python3.10/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/SciPy-bundle/2023.02-foss-2018b/lib/python3.10/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/SciPy-bundle/2023.02-foss-2018b/lib/python3.10/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/SciPy-bundle/2023.02-foss-2018b/lib/python3.10/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 898, in fn
    return [np.float64(subs(expr, dict(row))) for expr in exprs]
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/pharmpy/tools/frem/results.py", line 898, in <listcomp>
    return [np.float64(subs(expr, dict(row))) for expr in exprs]
  File "s0ftwar3/psn/PsN_5_3_2/pyvenv/lib/python3.10/site-packages/sympy/core/expr.py", line 351, in __float__
    raise TypeError("Cannot convert expression to float")
TypeError: Cannot convert expression to float
frem done

**Comment by rikardn** [comment]
Thanks @MahmAbdelwahab for reporting this. This was actually a bug that was triggered by using mu-referencing in frem. I have fixed it in 8b7e22a6176fae24d0c6375397a43f01370a65d3 and the fix will be in the next release of Pharmpy and PsN (which will come out in the not too distant future).

@stellabelin If the original issue has been solved perhaps we can close this issue?

**Comment by stellabelin** [comment]
Yes I think the original issue was solved, closing.
