### ISSUE TITLE
Whitespace in nonmem files causes problems

### ISSUE THREAD

**Issue by antoniaih** [pharmpy/pharmpy#1817]
### Bug report

It is not possible to use the functions `set_direct_effect` or `add_effect_compartment` if there is whitespace in front of assignments.

For example the whitespace in front of the `Y` statement in a nonmem file cause problems when adding an error model:

```
$ERROR
C = A(1)/VC                     ; Drug Plasma conc.
 
     Y = C*(1+EPS(1))       ; PK – Proportional RUV
```

Code:
```
model = read_model("runtest3.mod")
model = add_effect_compartment(model, "baseline")
```

Error message:
```
Traceback (most recent call last):
  File "/home/antonia/testing/test_structsearch.py", line 9, in <module>
    model1 = add_effect_compartment(model, "baseline")
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/modeling/pd.py", line 71, in add_effect_compartment
    model = _add_effect(model, expr, conc_e)
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/modeling/pd.py", line 163, in _add_effect
    model = set_proportional_error_model(model, dv=2, zero_protection=False)
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/modeling/error.py", line 272, in set_proportional_error_model
    model = add_population_parameter(model, sigma.name, 0.09)
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/modeling/parameters.py", line 627, in add_population_parameter
    return model.update_source()
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/model/external/nonmem/model.py", line 198, in update_source
    model, updated_dataset = update_statements(
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/model/external/nonmem/update.py", line 634, in update_statements
    new_error = new_error.update_extra_nodes(model.dependent_variables)
  File "/home/antonia/testing/testpharmpy/lib/python3.10/site-packages/pharmpy/model/external/nonmem/records/code_record.py", line 610, in update_extra_nodes
    if node.find('block_if'):
AttributeError: 'AttrToken' object has no attribute 'find'
```
[runtest3.zip](https://github.com/pharmpy/pharmpy/files/11937257/runtest3.zip)

**Comment by vrognas** [comment]
I'd say it is desirable to keep the leading whitespace for formatting and readability purposes. Pharmpy should ideally handle such common programming practices. This appears to be a bug or an oversight in Pharmpy's parsing mechanism.

**Comment by rikardn** [comment]
I agree that this is a bug. The issue seems to be in the update rather than the parser.
