### ISSUE TITLE
Errors in uncertainty method in estmethod

### ISSUE THREAD

**Issue by keqiss** [pharmpy/pharmpy#1898]
### Bug report

`res = run_estmethod(algorithm = 'exhaustive',model=model, results=results, covs='all')`
The algorithm argument (not sure if necessary for covmethod) accepts 'exhaustive', 'exhaustive_with_update', and 'exhaustive_only_eval', but 'exhaustive_with_update’ gives an error.

![image](https://github.com/pharmpy/pharmpy/assets/133008289/0ce51f4f-54da-4284-97db-12d615b57bc2)

Pharmpy version: 0.98.2

**Comment by vrognas** [comment]
Hi @keqiss,

Thank you for reporting this issue with the `exhaustive_with_update` algorithm. I see the error in the image you provided.

In the future, could you please submit errors as text instead of images? Text can easily be copied and pasted, allowing for quicker analysis and debugging. Text can also be searched by others who may encounter the same issue, helping them find solutions faster.

To help further investigate this issue, could you please provide the error message as text? You can copy and paste it directly from your terminal or code editor.

Thank you for your cooperation.

**Comment by keqiss** [comment]
Hi @vrognas,

Sorry for the inconvenience. I just have started using GitHub, thank you so much for your suggestion.

Please find the text of the error message, I hope it is not too late.
```
<Client: 'inproc://172.18.9.42/18757/1' processes=1 threads=6, memory=37.50 GiB>
2023-07-24 12:26:13,561 - distributed.worker - WARNING - Compute Failed
Key:       create_base_model-start_estmethod-run0-b3eea775-df32-479b-b6ca-f9b892c9a422
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2b2b0c9aa8c0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x2b2b0974edd0>, (<function _create_base_model at 0x2b2b0537eef0>, (<function start at 0x2b2b0537f2e0>, <Pharmpy model object dauno_0_starting>))))
kwargs:    {}
Exception: 'TypeError("_create_description() missing 1 required positional argument: \'cov\'")'

Traceback (most recent call last):
  File "/crex/proj/pmgroup_active_storage/private/users/keqi/AMDTEST/ESTtool/covmethod/covmethod_2.py", line 7, in <module>
    res = run_estmethod('exhaustive_with_update',model=model, results=results, covs='all')
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/run.py", line 173, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/run.py", line 220, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/workflows/execute.py", line 69, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/workflows/dispatchers/local_dask.py", line 81, in run
    res = client.get(dsk_optimized, 'results')
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/client.py", line 3227, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/client.py", line 2361, in gather
    return self.sync(
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/utils.py", line 351, in sync
    return sync(
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/utils.py", line 418, in sync
    raise exc.with_traceback(tb)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/utils.py", line 391, in f
    result = yield future
  File "/home/kesh5913/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/distributed/client.py", line 2224, in _gather
    raise exception.with_traceback(traceback)
  File "/domus/h1/kesh5913/pharmpy/src/pharmpy/tools/estmethod/algorithms.py", line 106, in _create_base_model
    description=_create_description([est_method, eval_method], solver=None, update=False)
TypeError: _create_description() missing 1 required positional argument: 'cov'
```
