### ISSUE TITLE
set_transit_compartments(model, 0) causes crash in some cases. 

### ISSUE THREAD

**Issue by davsjob** [pharmpy/pharmpy#1998]
### Bug report

Hi! Thank you so much for taking the time!
When running `m=load_example_model("pheno")` and setting `m=set_transit_compartments(model, n)` with n>1 first and then removing the transit compartment by  `m=set_transit_compartments(model, 0)` causes IndexError. 
``
>>> m = set_transit_compartments(m, 2) 
>>> m = set_transit_compartments(m, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sjobe\OneDrive - Uppsala universitet\Farma\pharmpygui\Lib\site-packages\pharmpy\modeling\odes.py", line 891, in set_transit_compartments
    from_comp, from_flow = cs.get_compartment_inflows(trans)[0]
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
``  

If I instead `m=set_transit_compartments(model, 1)`  and look at the model statements it seems like transit compartment is still there, but no error. 
This is fixed by setting `m=set_transit_compartments(model, 1, keep_depot=False)`, returning correct statements for n=1, but still crashes for n>1

**Comment by rikardn** [comment]
I have tested this and it works now.
