### ISSUE TITLE
pharmr fails to find nmfe script for nonmem

### ISSUE THREAD

**Issue by Eliford** [pharmpy/pharmpy#2128]
### Bug report

I am trying to fit the example `pheno` model with ```results <- fit(model)``` on Windows. I get the 'FileNotFoundError' below.

My pharmy.config file has ```default_nonmem_path=C:\nm75g64```. Is this a correct way to specify the path to nonmem installation to make nmfe75 discoverable?

```
 fitpheno <- fit(model)
2023-10-01 12:49:43,135 - distributed.worker - WARNING - Compute Failed
Key:       run0-results
Function:  execute_task
args:      ((<function post_process_results_many at 0x0000029CBB3EC220>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x0000029CBD2982D0>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x0000029CBEB22520>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x0000029CBD2982D0>, <Pharmpy model object pheno>)))
kwargs:    {}
Exception: "FileNotFoundError('Cannot find nmfe script for NONMEM (C:\\\\nm75g64,nmfe75\\\\run)')"

<Client: 'inproc://10.145.26.151/9756/54' processes=1 threads=8, memory=15.68 GiB>
FileNotFoundError: Cannot find nmfe script for NONMEM (C:\nm75g64,nmfe75\run)
Run `reticulate::py_last_error()` for details.Full stack:
FileNotFoundErrorCannot find nmfe script for NONMEM (C:\nm75g64,nmfe75\run)c("  File \"C:\\Users\\ELIFOR~1.KIT\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 82, in fit\n    models = run_tool('modelfit', kept, tool=tool)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\ELIFOR~1.KIT\\AppData\\Local\\R-MINI~1\\envs\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 173, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^
```

**Comment by stellabelin** [comment]
Hi! It looks correct to write `default_nonmem_path=C:\nm75g64`. From the error message, it looks like it finds a tuple of paths, what does your full config file look like?

**Comment by Eliford** [comment]
Hi @stellabelin the full config file look like below
```
[pharmpy.plugins.nonmem]
default_nonmem_path=C:\nm75g64

```

**Comment by Eliford** [comment]
Below is the error after removing tuples from the path.

```
fitpheno <- fit(model)
2023-10-17 20:50:38,626 - distributed.worker - WARNING - Compute Failed
Key:       run0-results
Function:  execute_task
args:      ((<function post_process_results_many at 0x000001BF9DC1C680>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x000001BF9F2AB090>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x000001BF9F11E8E0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x000001BF9F2AB090>, <Pharmpy model object pheno>)))
kwargs:    {}
Exception: "FileNotFoundError('No path to NONMEM configured in pharmpy.conf and nmfe not in PATH')"

<Client: 'inproc://10.103.74.111/57556/18' processes=1 threads=48, memory=63.49 GiB>
FileNotFoundError: No path to NONMEM configured in pharmpy.conf and nmfe not in PATH
Run `reticulate::py_last_error()` for details.Full stack:
FileNotFoundErrorNo path to NONMEM configured in pharmpy.conf and nmfe not in PATHc("  File \"C:\\Users\\ELIFOR~1.KIT\\CONDA~1\\envs\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 83, in fit\n    models = run_tool('modelfit', kept, tool=tool)\n             ^^^^^^^^^^^^^
```

**Comment by Eliford** [comment]
Below is the output from `py_last_error()`

```
reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\run.py", line 83, in fit
    models = run_tool('modelfit', kept, tool=tool)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\run.py", line 174, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\run.py", line 221, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\workflows\execute.py", line 74, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 80, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\distributed\client.py", line 3281, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\distributed\client.py", line 2384, in gather
    return self.sync(
           ^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\modelfit\tool.py", line 126, in task
    return execute_model(model, context)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 68, in execute_model
    args = nmfe(
      ^^^^^^^^^^^
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 196, in nmfe
    nmfe_path(),
  File "C:\Users\ELIFOR~1.KIT\CONDA~1\envs\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 184, in nmfe_path
    raise FileNotFoundError(
    ^^^^^^^^^^^^^^^^^
FileNotFoundError: No path to NONMEM configured in pharmpy.conf and nmfe not in PATH

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────────────────────
     ▆
  1. └─pharmr::fit(model)
  2.   ├─base::tryCatch(...)
  3.   │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  4.   │   ├─base (local) tryCatchOne(...)
  5.   │   │ └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  6.   │   └─base (local) tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
  7.   │     └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
  8.   │       └─base (local) doTryCatch(return(expr), name, parentenv, handler)
  9.   └─pharmpy$tools$fit(model_or_models, tool = tool)
 10.     └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
```

**Comment by muhonggary** [comment]
Just started learning Pharmpy and had the same issue. Have you figured out?

**Comment by stellabelin** [comment]
Hi! Thanks for reporting @muhonggary! I apologise @Eliford for never getting back to you on this issue, I lost track of this. Some things you can try to check that everything looks correct/expected:

- Check that the expected config-file is found by using the function: `get_config_path()` (sometimes this can be an issue on Windows, if e.g. Python has been installed via Microsoft store). 
- Check if the NONMEM installation has the files Pharmpy expects: does the file nmfe75.bat exist in the `run` directory of your NONMEM installation?
- Do you have the NONMEM installation path as a `PATH`-variable?

The error message is not very clear, so I will make some changes so it's clear whether the problem is that Pharmpy cannot find the config or if the path itself is incorrect, hopefully making the errors more understandable.

**Comment by muhonggary** [comment]
Hi @stellabelin, thank you for the possible solutions, but I still have the problem. Here are some of my environments:

1. get_config_path(): '\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf'

2. nmfe75.bat is in the run directory. And here how my conf file looks like:
   [pharmpy.plugins.nonmem]
   default_nonmem_path=C:\nm75g

3. C:\nm75g is added as a path to environment system variables

**Comment by stellabelin** [comment]
Hi again! Thanks for checking. Which version of Pharmpy/pharmr are you using? 1&2 look correct, for 3 you need to have `C:\nm75g\run` in your environment system variables (however it should still work with the config-file). 

I've added (hopefully) clearer error messages in 4029550 which is in Pharmpy version 0.109.0, another thing you could do is try rerunning and see if it's the same error message or if it's more detailed.

**Comment by muhonggary** [comment]
Thank you, @stellabelin ! Now, I see where the issue is.

**Comment by stellabelin** [comment]
Hi! Okay, great! Out of curiosity, what was the issue?

**Comment by muhonggary** [comment]
I was using C:\nm75g. Now, switching to C:\nm75g\run and finally works. I was just following the example, so it seems the NONMEM installation method is a little bit different.

**Comment by Eliford** [comment]
the path below works for me now.
`default_nonmem_path=C:/nm75g64`
