### ISSUE TITLE
Error when creating report on cluster

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#2145]
### Bug report

```
<Client: 'inproc://172.18.9.159/14135/1' processes=1 threads=20, memory=125.00 GiB>
<Client: 'inproc://172.18.9.159/14135/10' processes=1 threads=20, memory=125.00 GiB>
<Client: 'inproc://172.18.9.159/14135/19' processes=1 threads=20, memory=125.00 GiB>
<Client: 'inproc://172.18.9.159/14135/28' processes=1 threads=20, memory=125.00 GiB>
Traceback (most recent call last):
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/crex/proj/pmgroup_active_storage/private/users/samia/2909_PKPD/IV_1comp/Indirect/Kout_degradation/Emax/Kout_Emax.py", line 27, in <module>
    res_pk = run_amd(input=pk_model,
  File "/crex/proj/pmgroup_active_storage/private/users/samia/Git/mypharmpy/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 382, in run_amd
    generate_report(rst_path, results_path, target_path)
  File "/crex/proj/pmgroup_active_storage/private/users/samia/Git/mypharmpy/lib/python3.10/site-packages/pharmpy/reporting/reporting.py", line 95, in generate_report
    embed_css_and_js(tmp_path / 'results.html', report_path)
  File "/crex/proj/pmgroup_active_storage/private/users/samia/Git/mypharmpy/lib/python3.10/site-packages/pharmpy/reporting/reporting.py", line 109, in embed_css_and_js
    with urlopen(source) as infile:
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by rikardn** [comment]
Should be fixed with d9bab07047e1bc7a28a06234444452c5ef6642ff
