### ISSUE TITLE
iivsearch crash for problematic model

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#2422]
```python

model = read_model("run1.mod")
results = read_modelfit_results("run1.mod")

res = run_iivsearch(model=model, algorithm='brute_force_no_of_etas', results=results, strictness=None)
```

```
Gives error:

Traceback (most recent call last):

  File "/tmp/ipykernel_11024/1564958283.py", line 1, in <module>
    res = run_iivsearch(model=model, algorithm='brute_force_no_of_etas', results=results, strictness=None)

  File "/home/devel/pharmpy/src/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)

  File "/home/devel/pharmpy/src/pharmpy/tools/run.py", line 188, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)

  File "/home/devel/pharmpy/src/pharmpy/tools/run.py", line 235, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)

  File "/home/devel/pharmpy/src/pharmpy/workflows/execute.py", line 74, in execute_workflow
    res: T = dispatcher.run(workflow)

  File "/home/devel/pharmpy/src/pharmpy/workflows/dispatchers/local_dask.py", line 80, in run
    res = client.get(dsk_optimized, 'results')

  File "/home/.local/lib/python3.10/site-packages/distributed/client.py", line 3213, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)

  File "/home/.local/lib/python3.10/site-packages/distributed/client.py", line 2348, in gather
    return self.sync(

  File "/home/.local/lib/python3.10/site-packages/distributed/utils.py", line 349, in sync
    return sync(

  File "/home/.local/lib/python3.10/site-packages/distributed/utils.py", line 416, in sync
    raise exc.with_traceback(tb)

  File "/home/.local/lib/python3.10/site-packages/distributed/utils.py", line 389, in f
    result = yield future

  File "/home/.local/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()

  File "/home/.local/lib/python3.10/site-packages/distributed/client.py", line 2211, in _gather
    raise exception.with_traceback(traceback)

  File "/home/devel/pharmpy/src/pharmpy/tools/iivsearch/tool.py", line 191, in start
    final_model_entry = context.model_database.retrieve_model_entry(res.final_model.name)

  File "/home/devel/pharmpy/src/pharmpy/workflows/model_database/baseclass.py", line 404, in retrieve_model_entry
    return sn.retrieve_model_entry()

  File "/home/devel/pharmpy/src/pharmpy/workflows/model_database/local_directory.py", line 381, in retrieve_model_entry
    model = self.retrieve_model()

  File "/home/devel/pharmpy/src/pharmpy/workflows/model_database/local_directory.py", line 361, in retrieve_model
    raise KeyError(

KeyError: 'Could not find run1 in LocalModelDirectoryDatabase(/home/rikard/iivsearch_dir14/models). Looked up `/home/rikard/iivsearch_dir14/models/run1/run1.mod`, `/home/rikard/iivsearch_dir14/models/run1/run1.ctl`.'
```

The model:

```
$PROBLEM    PHENOBARB SIMPLE MODEL
$DATA      pheno.dta IGNORE=@
$INPUT      ID TIME AMT WGT APGR DV FA1 FA2
$SUBROUTINE ADVAN13 TOL=9
$MODEL COMP=(CENTRAL)
$PK

CL=THETA(1)*EXP(ETA(1))
V=THETA(2)*EXP(ETA(2))
S1=V

$DES
DADT(1) = -CL * A(1) / V + 0.00001*T

$ERROR
Y=F+F*EPS(1)

$THETA (0,0.00469307) ; POP_CL
$THETA  (0,1.00916) ; POP_V

$OMEGA  DIAGONAL(2)
0.0309626  ; IVCL
0.031128  ; IVV

$SIGMA  0.0130865
$ESTIMATION METHOD=1 INTERACTION PRINT=1 MAXEVAL=0
$TABLE ID TIME DV PRED NOAPPEND FILE=sdtab_pheno_des
```

**Comment by rikardn** [comment]
Also a `run1` directory created in addition to `input_model` in database. No results-file in `input_model` directory
