### ISSUE TITLE
run_AMD TMDD model building from input dataset returns an error message 

### ISSUE THREAD

**Issue by schaedeli** [pharmpy/pharmpy#2683]
### Bug report

Hi,
I have tried to use Kequi's proposed code to start a tmdd model building using run_amd() with 3 dvtypes: "drug", "target", and "drug_tot".  
Running PharmR v.0.106.0
The code below returns an error message that I cannot interpret. Furthermore, it is not clear to me, how to initiate a run_structsearch() with 3 DVTYPES, when starting with a PK model. (See previously generated issue [#2681](https://github.com/pharmpy/pharmpy/issues/2681))

```
res <- run_amd(input=dataset_path,
        strategy = "SIR",
        search_space="PERIPHERALS([0,1,2]);ELIMINATION([FO,MM,MIX-FO-MM])",
        modeltype='tmdd',
        dv_types = list("drug"=1L,"target"=2L, "drug_tot"=3L)
        )
TypeError: _subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'
Run `reticulate::py_last_error()` for details.Full stack:
TypeError_subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 429, in run_amd

```

**Comment by schaedeli** [comment]
Hi,
do you have any update on this error message? 
I have in the mean time tried this with only 2 dvtypes, and administration="iv" specified, which I had forgotten before, but still the same error type. Please see fullstack below, and a snapshot of the data

```
Pharmpy version: 0.106.0
txt> res <- run_amd(input=data_path2b,
txt+                administration = "iv",
txt+               # strategy = "SIR",
txt+                search_space="PERIPHERALS([0,1,2]);ELIMINATION([FO,MM,MIX-FO-MM])",
txt+                modeltype='tmdd',
txt+                dv_types = list("drug"=1L,"target"=2L)
txt+ )
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1073: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1095: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1148: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/common.py:719: UserWarning:  The expression is invalid
  warnings.warn(""" The expression is invalid""")
TypeError: _subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'
Run `reticulate::py_last_error()` for details.Full stack:
TypeError_subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 429, in run_amd
    func = _subfunc_ruvsearch(
Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 429, in run_amd
    func = _subfunc_ruvsearch(
TypeError: _subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.TypeError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = data_path2b, administration = "iv", search_space = "PERIPHERALS([0,1,2]);ELIMINATION([FO,MM,MIX-FO-MM])", modeltype = "tmdd", dv_types = list(drug = 1, target = 2)), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = data_path2b, administration = "iv", search_space = "PERIPHERALS([0,1,2]);ELIMINATION([FO,MM,MIX-FO-MM])", 
    modeltype = "tmdd", dv_types = list(drug = 1, target = 2)), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 0.106.0
'0.106.0'
Pharmpy version: 0.106.0

```





[Untitled spreadsheet - Sheet2.csv](https://github.com/pharmpy/pharmpy/files/14343755/Untitled.spreadsheet.-.Sheet2.csv)

**Comment by stellabelin** [comment]
Hi, thanks for reporting this! I have fixed the error in fef63bf. Another issue is that the DV ID column currently needs to be named `DVID`, we have an issue for this since the long term solution would be to not have it hard coded: https://github.com/pharmpy/pharmpy/issues/2699. With fe1c836 it should raise if this is not the case.

**Comment by schaedeli** [comment]
Hi Stella

thanks for looking into this. I realize I miss-labeled the column
DVTYPE instead of DVID. I was apparently confused by the argument dv_types
that requires a column named DVID, not DVTYPE.

I will now try to update the column name and run the code again.

Thanks,
Franziska


*Franziska Schaedeli Stark, PhD*Senior Pharmacometrician
Senior Principal Scientist
Pharmaceutical Sciences - Predictive Modeling & Data Analytics (PS-PMDA)
Roche Pharma Research & Early Development (pRED)

Roche Innovation Center Basel

F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124
Bldg 1 - Floor 7

4070 Basel

Phone:  +41 61 688 5819
Mob +41 79 773 12 61
mailto: ***@***.***

**Comment by stellabelin** [comment]
Hi Franziska! The original error (`TypeError_subfunc_ruvsearch() missing 1 required positional argument: 'dir_name'`) will still occur unfortunately, as soon as there is a new Pharmpy release it should work.

**Comment by schaedeli** [comment]
Hi Stella
thanks for the update, so I will wait for the new version to be implemented
in our system.
Kind Regards
Franziska


*Franziska Schaedeli Stark, PhD*Senior Pharmacometrician
Senior Principal Scientist
Pharmaceutical Sciences - Predictive Modeling & Data Analytics (PS-PMDA)
Roche Pharma Research & Early Development (pRED)

Roche Innovation Center Basel

F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124
Bldg 1 - Floor 7

4070 Basel

Phone:  +41 61 688 5819
Mob +41 79 773 12 61
mailto: ***@***.***
