### ISSUE TITLE
Couldn't parse failed model in ESTmethod

### ISSUE THREAD

**Issue by keqiss** [pharmpy/pharmpy#2745]
### Bug report

Could be recreated with _read_modelfit_results("estmethod_run6.ctl")_

`Traceback (most recent call last):
  File "/crex/proj/pmgroup_active_storage/private/users/keqi/AMDTEST/ESTmethod/temp_debug/broken_est/estmethod_run6/script.py", line 5, in <module>
    res = read_modelfit_results("estmethod_run6.ctl")
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/run.py", line 1193, in read_modelfit_results
    res = parse_modelfit_results(model, path)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/external/results.py", line 11, in parse_modelfit_results
    res = module.parse_modelfit_results(model, path)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/external/nonmem/results.py", line 804, in parse_modelfit_results
    res = _parse_modelfit_results(
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/external/nonmem/results.py", line 84, in _parse_modelfit_results
    ) = _parse_ext(control_stream, name_map, ext_tables, subproblem, parameters)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/external/nonmem/results.py", line 578, in _parse_ext
    final_ofv, ofv_iterations = _parse_ofv(ext_tables, subproblem)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/tools/external/nonmem/results.py", line 615, in _parse_ofv
    df = _get_iter_df(table.data_frame)
  File "/home/kesh5913/ppenv/lib/python3.10/site-packages/pharmpy/model/external/nonmem/table.py", line 260, in data_frame
    raise ValueError('Broken table in ext-file')
ValueError: Broken table in ext-file`

[estmethod_run6.zip](https://github.com/pharmpy/pharmpy/files/14521591/estmethod_run6.zip)

**Comment by stellabelin** [comment]
Currently, if the whole .ext-file is broken, we will catch the error, log it, then return `ModelfitResults` with `NaN`-values etc. If only one table is broken, then we log it but then proceed to try to parse it.
