### ISSUE TITLE
PKPD iiv_search and ruv_search

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#2929]
I was running the PKPD test on the new version 0.109. It is now generating PKPD structural models. However, it is still not proceeding to iiv_search and ruv_search. This is the code I used:

res_pd = run_amd(input=model_pkpd,
                 results=model_results,
                 modeltype='pkpd',
                 emax_init=80.0,
                 b_init=100.0,
                 ec50_init=1.0,
                 met_init=10.0,
                 retries_strategy='skip')

I tried this one as well:

res_pd = run_amd(input=model_pkpd,
                 results=model_results,
                 modeltype='pkpd',
                 emax_init=80.0,
                 b_init=100.0,
                 ec50_init=1.0,
                 met_init=10.0,
                 strategy = 'SIR',
                 retries_strategy='skip')

I'm getting this error message:
IndexError: list index out of range

**Comment by antoniaih** [comment]
This was fixed in #2917

**Comment by Orwa-bit** [comment]
This issue has been resolved in v 1.1.0. Thanks!
I still get a long bug report, which I will copy here, but everything seems to work just fine:

/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1208: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1230: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1327: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:249: UserWarning: Skipping allometry since modeltype is "pkpd"
  warnings.warn('Skipping allometry since modeltype is "pkpd"')
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/iivsearch/tool.py:405: UserWarning: Worse bic in final model iivsearch_run21 than input, selecting input model
  warnings.warn(
<Client: 'inproc://172.17.0.6/38854/1' processes=1 threads=12, memory=46.86 GiB>
<Client: 'inproc://172.17.0.6/38854/10' processes=1 threads=12, memory=46.86 GiB>
<Client: 'inproc://172.17.0.6/38854/19' processes=1 threads=12, memory=46.86 GiB>
<Client: 'inproc://172.17.0.6/38854/28' processes=1 threads=12, memory=46.86 GiB>
Full stack:
ValueError: too many values to unpack (expected 2)
Run `reticulate::py_last_error()` for details.ValueErrortoo many values to unpack (expected 2)c("  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 595, in run_amd\n    final_vpc_plot = plot_vpc(final_model, simulation_data, stratify_on=dvid_name)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 1021, in plot_vpc\n    _vpc_plot(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 844, in _vpc_plot\n    df = _calculate_vpc(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 759, in _calculate_vpc\n    sim_central_lower = [lower for lower, _ in median_cis]\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 759, in <listcomp>\n    sim_central_lower = [lower for lower, _ in median_cis]\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 595, in run_amd
    final_vpc_plot = plot_vpc(final_model, simulation_data, stratify_on=dvid_name)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 1021, in plot_vpc
    _vpc_plot(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 844, in _vpc_plot
    df = _calculate_vpc(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 759, in _calculate_vpc
    sim_central_lower = [lower for lower, _ in median_cis]
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 759, in <listcomp>
    sim_central_lower = [lower for lower, _ in median_cis]
ValueError: too many values to unpack (expected 2)
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = model_pkpd, results = model_results, modeltype = "pkpd", emax_init = 80, b_init = 100, ec50_init = 1, met_init = 10, retries_strategy = "skip"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = model_pkpd, results = model_results, modeltype = "pkpd", 
    emax_init = 80, b_init = 100, ec50_init = 1, met_init = 10, retries_strategy = "skip"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.1.0
'1.1.0'
Pharmpy version: 1.1.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by rikardn** [comment]
This new error message was a bug in the VPC code that should have been fixed now. Thanks for reporting!
