### ISSUE TITLE
parsing error running nlmixr2 model

### ISSUE THREAD

**Issue by roninsightrx** [pharmpy/pharmpy#3003]
### Bug report

Hi, I'm seeing an issue running a nlmixr2 model with latest version v109 (I do not see this error in v106).

Error in R:
```
2024-05-07 04:59:48,397 - distributed.worker - WARNING - Compute Failed
Key:       run0-results
Function:  execute_task
args:      ((<function post_process_results_one at 0xffff342bc8b0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0xffff424de020>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0xffff30d6caf0>, <pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0xffff424de020>, <pharmpy.workflows.model_entry.ModelEntry object at 0xffff30e6d3f0>)))
kwargs:    {}
Exception: 'AttributeError("\'Matrix\' object has no attribute \'row\'")'

Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  AttributeError: 'Matrix' object has no attribute 'row'
```

Python trace:
```
── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/run.py", line 169, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/run.py", line 207, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
  File "/app/venv/lib/python3.10/site-packages/distributed/client.py", line 3279, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/app/venv/lib/python3.10/site-packages/distributed/client.py", line 2372, in gather
    return self.sync(
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/modelfit/tool.py", line 102, in task
    return execute_model(model_entry, context)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/external/nlmixr/run.py", line 139, in execute_model
    res = parse_modelfit_results(model, path)
  File "/app/venv/lib/python3.10/site-packages/pharmpy/tools/external/nlmixr/run.py", line 603, in parse_modelfit_results
    symb = omega.row(i)[j]
AttributeError: 'Matrix' object has no attribute 'row'
```
Does this error look familiar? Let me know if you need more info, I can try and make a reproducible example.

Environment: This is on a Mac M1, but running in Docker in a virtual Python environment.

**Comment by rikardn** [comment]
Thanks for reporting this. We should be able to fix it based on your information.
