### ISSUE TITLE
structsearch TMDD : ValueError: nan is not in list

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmpy#3006]
Hi ! 
When I try to run run_structsearch with tmdd, I get this error message. I tried with others models / dataset and I get almost the same message (ofvs.index). Can you tell me what that means please ? 
```
/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py:148: RuntimeWarning: All-NaN axis encountered
  minindex = ofvs.index(np.nanmin(ofvs))
2024-05-07 15:39:32,879 - distributed.worker - WARNING - Compute Failed
Key:       results
Function:  run_tmdd
args:      (<pharmpy.workflows.tool_database.local_directory.LocalDirectoryToolDatabase object at 0x7f7534adaff0>, <Pharmpy model object startdvids>, <Pharmpy modelfit results object start>, None, None, 'minimization_successful or (rounding_errors and sigdigs >= 0.1)', None)
kwargs:    {}
Exception: "ValueError('nan is not in list')"

ValueError: nan is not in list
Run `reticulate::py_last_error()` for details.Full stack:
ValueErrornan is not in listc("  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/wrap.py\", line 34, in func\n    return run_tool(tool_name, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 169, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 207, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py\", line 3275, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py\", line 2372, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py\", line 148, in run_tmdd\n    minindex = ofvs.index(np.nanmin(ofvs))\n      ^^^^^^^^^^^^^^^^^\n")Traceback (most recent call last):
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py", line 169, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/run.py", line 207, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, database=tool_database)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py", line 3275, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/distributed/client.py", line 2372, in gather
    return self.sync(
           ^^^^^^^^^^
  File "/homemtp/u1029377/miniconda3/envs/r-reticulate/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py", line 148, in run_tmdd
    minindex = ofvs.index(np.nanmin(ofvs))
      ^^^^^^^^^^^^^^^^^
ValueError: nan is not in list
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_structsearch(type = "tmdd", model = modeldvids, results = modelfitresults), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", 
"local", "local", "local", NA, ":::"), full_call = list(run_structsearch(type = "tmdd", model = modeldvids, results = modelfitresults), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.model.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}, warning = function(cond) {
    message(cond)
    message("Full stack:")
    message(reticulate::py_last_error())
    message("pharmr version: ", packageVersion("pharmr"))
    message("Pharmpy version: ", print_pharmpy_version())
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 0.109.0
'0.109.0'
Pharmpy version: 0.109.0
```

**Comment by artikandms** [comment]
I closed the issue by error.

**Comment by artikandms** [comment]
I closed by error.

**Comment by antoniaih** [comment]
Hi, it looks like all ofvs are NaN, so all QSS models are failing. How does your model and dataset look like? The input model should be a PK model and the dataset should be a TMDD dataset.

**Comment by artikandms** [comment]
Sorry I was OOO. 
My input model is a basic pk model that I fit with a filtered dataset dvid 1, then I change the dataset to have dvid 1 and dvid 2, but I keep the basic pk model as input. 
I don’t know if that’s clear.

**Comment by antoniaih** [comment]
Ok this seems correct. How does your code look like? Have you specified `dv_types`? If you have two DVs then you should specify it. If `dv_types` is not specified then all rows in the dataset will be treated as drug. 
Maybe you can also check the lst files to get some more information about why the models are failing.

**Comment by artikandms** [comment]
So I tried with another dataset  with columns ID, TIME, AMT, DV, DVID, CMT and a basic model with IV administration. 
DVID = 1 is the drug and DVID = 2 is the target. And I specify it in dv_types.
CMT = 1 is my central compartment and CMT = 2 is my target compartment.

As mentioned above, I run the basic model with the filtered dataset where I only have DVID = 1, then I read the results with modelfit, and I re-read the basic model with the fulldataset (DVID = 1 and DVID = 2) , and this model is my input model.

Now, pharmr manages to go beyond qss models, except that not all other tmdd models are created (only 1,2,3,4,7,8,12) and I get the error 'all models fail the strictness criteria'. 

Here is the nonmem error message, I tried to change the initial values of my initial model but without success. 
Any help is greatly appreciated.

```
0PRED EXIT CODE = 1
0INDIVIDUAL NO.       4   ID= 4.00000000000000E+00   (WITHIN-INDIVIDUAL) DATA REC NO.  15
 THETA=
  2.00E-01   2.00E-01   8.28E+02   1.00E-01   1.73E+01   5.62E+00
 ETA=
  0.00E+00   0.00E+00  -2.92E-01
 OCCURS DURING SEARCH FOR ETA AT A NONZERO VALUE OF ETA
 ERROR IN LSODA: CODE  -1                                                                                                            
0PROGRAM TERMINATED BY OBJ
 MESSAGE ISSUED FROM ESTIMATION STEP
 AT 0TH ITERATION, UPON EVALUATION OF GRADIENT
```

**Comment by antoniaih** [comment]
The reason not all TMDD models are created is that it is not possible to ignore DVIDs in Pharmpy/pharmr. Thus we cannot create models with fewer DVIDs than exist in the dataset.
