### ISSUE TITLE
error during run_amd

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3078]
### Bug report

Pharmpy version: 0.110.0
The run stopped after iivsearch. Here is the error message:
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py:76: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
Traceback (most recent call last):
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/sw/comp/python/3.10.8/rackham/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 681, in initialize
    self.init_sockets()
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 334, in init_sockets
    self.init_control(context)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 341, in init_control
    self.control_port = self._bind_socket(self.control_socket, self.control_port)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 252, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 228, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/domus/h1/rosemary/.virtualenvs/r-reticulate/lib/python3.10/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:54474')
<Client: 'inproc://172.18.10.47/12809/1' processes=1 threads=8, memory=50.00 GiB>
<Client: 'inproc://172.18.10.47/12809/10' processes=1 threads=8, memory=50.00 GiB>
<Client: 'inproc://172.18.10.47/12809/19' processes=1 threads=8, memory=50.00 GiB>
<Client: 'inproc://172.18.10.47/12809/29' processes=1 threads=8, memory=50.00 GiB>
amd1 flag: error messages
Error in py_call_impl(callable, dots$args, dots$keywords): sphinx.errors.ExtensionError: Notebook execution failed (exception: Kernel died before replying to kernel_info)

Note: "amd1 flag: error messages" is added through tryCatch()

**Comment by yahanhsutw** [comment]
**Pharmpy version**: 1.1.0
**Run location**: /crex/proj/pmgroup_active_storage/private/users/yahan/AMD/loop_run/loop_0803_genta
**Issue**: Same as above, the amd run stopped after _iivsearch_ in /amd4. The error message was reported through tryCatch() .

**Error message**: 
<Client: 'inproc://172.18.9.71/28706/420' processes=1 threads=8, memory=50.00 GiB>
/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/pharmpy/tools/mfl/parse.py:1124: UserWarning: Could not determine absorption of model.
  warnings.warn("Could not determine absorption of model.")
<Client: 'inproc://172.18.9.71/28706/429' processes=1 threads=8, memory=50.00 GiB>
/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/pharmpy/tools/funcs/summarize_individuals.py:62: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
<Client: 'inproc://172.18.9.71/28706/438' processes=1 threads=8, memory=50.00 GiB>
/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/pharmpy/tools/funcs/summarize_individuals.py:62: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
<Client: 'inproc://172.18.9.71/28706/449' processes=1 threads=8, memory=50.00 GiB>
/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/pharmpy/tools/funcs/summarize_individuals.py:62: UserWarning: tflite is not installed, using NaN for predictions
  warnings.warn("tflite is not installed, using NaN for predictions")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 692, in initialize
    self.init_sockets()
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 345, in init_sockets
    self.init_control(context)
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 352, in init_control
    self.control_port = self._bind_socket(self.control_socket, self.control_port)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_venv/lib/python3.12/site-packages/zmq/sugar/socket.py", line 311, in bind
    super().bind(addr)
  File "_zmq.py", line 898, in zmq.backend.cython._zmq.Socket.bind
  File "_zmq.py", line 160, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:54164')
Full stack:
amd4 flag: error messages
Notebook execution failed (exception: Kernel died before replying to kernel_info)
<Client: 'inproc://172.18.9.71/28706/459' processes=1 threads=8, memory=50.00 GiB>

or see full message in /crex/proj/pmgroup_active_storage/private/users/yahan/AMD/loop_run/loop_0803_genta/genta_AMD_loop_0803.Rout
