### ISSUE TITLE
Example code produces error on Windows with conda

### ISSUE THREAD

**Issue by falkenhagen** [pharmpy/pharmpy#3095]
### Bug report

I am trying to run the following example code from the documentation of [fit](https://pharmpy.github.io/latest/api/pharmpy.tools.fit.html#pharmpy.tools.fit).

```python
>>> from pharmpy.modeling import load_example_model
>>> from pharmpy.tools import fit
>>> model = load_example_model("pheno")      
>>> results = fit(model)  
```

However, this code produces the following error message:

```shell
<Client: 'inproc://10.10.119.57/47748/1' processes=1 threads=20, memory=63.60 GiB>
C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\tools\external\nonmem\run.py:123: UserWarning: Expected result files do not exist, copying everything: model
  warnings.warn(f'Expected result files do not exist, copying everything: {basename}')
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\shutil.py", line 646, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USERNAME\\AppData\\Local\\Temp\\tmp2_oi1ceb\\NONMEM_run_pheno-8ea4f7dc-28d9-11ef-aeac-60452e4d3b35\\x\\nonmem.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\PATH_TO_FILE\test_pharmpy_clean.py", line 4, in <module>
    results = fit(model)
              ^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\tools\run.py", line 95, in fit
    modelfit_results = run_tool('modelfit', models, esttool=esttool, path=path, context=context)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\tools\run.py", line 190, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\tools\run.py", line 249, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\workflows\execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 26, in run
    with TemporaryDirectory() as tempdirname, chdir(tempdirname):
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\internals\fs\tmp.py", line 103, in exit
    self.cleanup()
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\internals\fs\tmp.py", line 107, in cleanup
    self._rmtree(self.name, ignore_errors=self._ignore_cleanup_errors)
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\internals\fs\tmp.py", line 86, in _rmtree
    _shutil.rmtree(name, onexc=onerror)  # pyright: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\shutil.py", line 820, in rmtree
    return _rmtree_unsafe(path, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\shutil.py", line 643, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onexc)
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\shutil.py", line 643, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onexc)
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\shutil.py", line 648, in _rmtree_unsafe
    onexc(os.unlink, fullname, err)
  File "C:\Users\USERNAME\AppData\Local\anaconda3\envs\pharmpy_test4\Lib\site-packages\pharmpy\internals\fs\tmp.py", line 48, in onerror
    if issubclass(exc, PermissionError):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

I have installed pharmpy in a new conda environment without errors using:
```shell
conda create --name pharmpy_test4
conda activate pharmpy_test4
conda install pip
pip install pharmpy-core
```

Pharmpy version: 1.0.0
Operating system: Windows 11

Any help is appreciated.

**Comment by stellabelin** [comment]
Hi! Thanks for reporting this issue! We have seen a similar error before and had a workaround in place which do not seem to be working, I've opened an issue here for this: #3099. 

However, since the warning `Expected result files do not exist, copying everything` occurred, it could be an error when NONMEM is run where it crashes instantly and thus that the subprocess running NONMEM was not closed before Pharmpy tries to delete the temporary directory. Do you have an .lst-file or STDOUT/STDERR-files and if so, do these look as expected? An example of causing one of these crashes would be if the NONMEM license has expired or is missing (I also made an issue for a Pharmpy error for this here: #3098).

**Comment by falkenhagen** [comment]
Thank you for the quick answer!
I found the stdout-file in the temporary directory, which contains the line:
`ERROR reading license file C:\nm75g64\license`
I corrected the line in my configuration file to point to the actual file, not the folder:
`licfile=C:/nm75g64/license/nonmem.lic`
and the code ran through!

It might be helpful to add a full example configuration file in the documentation for the configuration setup (https://pharmpy.github.io/latest/configuration.html).

**Comment by stellabelin** [comment]
Great to hear that worked! It should also work without specifying the path to the license at all if the license file is located in the NONMEM installation directory, the use case for the `licfile` option in the configuration is when it is located somewhere else. 

Thank you for your feedback, I agree that a full example in the documentation would be useful (as well as clarifying that the `licfile` option does not need to be set). I've made an issue for this (#3112), can I close this issue?

**Comment by rikardn** [comment]
If the `licfile` was used we should also check if the file exists in the validate input machinery. This way we can get a nicer error message.

**Comment by stellabelin** [comment]
Agreed, added this to #3098.

**Comment by falkenhagen** [comment]
Yes, this issue is solved. Thanks again!
