### ISSUE TITLE
FileNotFoundError: No path to NONMEM configured in pharmpy.conf and nmfe not in PATH

### ISSUE THREAD

**Issue by Razan2512** [pharmpy/pharmpy#3103]
### Bug report

Hey,
I am using pharmpy version '1.0.1'
I am trying to run a model but I get this error:
C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\amd\run.py:1204: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\amd\run.py:1308: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\model\external\nonmem\dataset.py:112: DatasetWarning: Dataset contains non-unique id numbers. Renumbering starting from 1
  warnings.warn(
2024-06-14 16:26:14,651 - distributed.worker - WARNING - Compute Failed
Key:       run0-results
Function:  execute_task
args:      ((<function post_process_results_one at 0x0000019AE3A574C0>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x0000019AF355B560>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x0000019AF1118B80>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x0000019AF355B560>, <pharmpy.workflows.model_entry.ModelEntry object at 0x0000019AF355B3B0>)))
kwargs:    {}
Exception: "FileNotFoundError('No path to NONMEM configured in pharmpy.conf and nmfe not in PATH')"

<Client: 'inproc://192.168.11.108/23556/310' processes=1 threads=12, memory=15.65 GiB>
Full stack:
FileNotFoundError: No path to NONMEM configured in pharmpy.conf and nmfe not in PATH
Run `reticulate::py_last_error()` for details.FileNotFoundErrorNo path to NONMEM configured in pharmpy.conf and nmfe not in PATHc("  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 482, in run_amd\n    results = run_tool('modelfit', model, path=ctx.path, resume=resume)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 190, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 249, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\workflows\\execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\workflows\\dispatchers\\local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\distributed\\client.py\", line 3284, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\distributed\\client.py\", line 2374, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\modelfit\\tool.py\", line 105, in task\n    me = execute_model(model_entry, context)\n    ^^^^^^^^^^^^^^^^^\n", 
"  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py\", line 64, in execute_model\n    args = nmfe(\"model.ctl\", \"model.lst\")\n      ^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py\", line 192, in nmfe\n    nmfe_path(),\n", "  File \"C:\\Users\\Razan\\DOCUME~1\\VIRTUA~1\\R-RETI~1\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py\", line 176, in nmfe_path\n    raise FileNotFoundError(\n    ^^^^^^^^^^^^^^^^^\n"
)Traceback (most recent call last):
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\amd\run.py", line 482, in run_amd
    results = run_tool('modelfit', model, path=ctx.path, resume=resume)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\run.py", line 190, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\run.py", line 249, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\workflows\execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\distributed\client.py", line 3284, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\distributed\client.py", line 2374, in gather
    return self.sync(
           ^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\modelfit\tool.py", line 105, in task
    me = execute_model(model_entry, context)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 64, in execute_model
    args = nmfe("model.ctl", "model.lst")
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 192, in nmfe
    nmfe_path(),
  File "C:\Users\Razan\DOCUME~1\VIRTUA~1\R-RETI~1\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 176, in nmfe_path
    raise FileNotFoundError(
    ^^^^^^^^^^^^^^^^^
FileNotFoundError: No path to NONMEM configured in pharmpy.conf and nmfe not in PATH
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.FileNotFoundError", "python.builtin.OSError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = dataset_path, modeltype = "basic_pk", administration = "oral", cl_init = 13, vc_init = 23, mat_init = 2, strategy = "default", search_space = "ABSORPTION(FO);ELIMINATION(FO)", allometric_variable = "WT", ), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = dataset_path, modeltype = "basic_pk", administration = "oral", 
    cl_init = 13, vc_init = 23, mat_init = 2, strategy = "default", search_space = "ABSORPTION(FO);ELIMINATION(FO)", allometric_variable = "WT", ), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.0.1
'1.0.1'
Pharmpy version: 1.0.1
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

I listed in R:
pharmpy.conf<-"C:\\Users\\Razan\\Desktop\\Final_R_Data\\Pharmpy\\pharmpy.conf"
licfile<-"C:\\nm75g64\\license\\nonmem.lic"
default_nonmem_path<-"C:\\nm75g64\\run"

I have in the pharmpy.conf file:
[pharmpy.plugins.nonmem]
default_nonmem_path=C:\\nm75g64\\run

I tried different other default_nonmem_path such as C:\\nm75g64 or C:/nm75g64  without success

**Comment by rikardn** [comment]
Thanks for reporting this. This is a bug, but there might also be something on your side. To rule out some options perhaps could you could try calling `get_config_path` to see if the configuration file is in the wrong place? There is also the option to remove the configuration item and instead add the path to nmfe to the PATH environment variable.

**Comment by Razan2512** [comment]
Hey,

Thanks for your reply.

Indeed when I called get_config_path() - the path that I got was different than  the path I wrote in:

 pharmpy.conf<-"C:\Users\Razan\Desktop\Final_R_Data\Pharmpy\pharmpy.conf"


It turns out that that the config file is in appData.

But again, when I changed the path to appData-

PHARMPYCONFIGPATH<-"C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf"

 the same error reappeared.


Also, I tried to remove the PHARMPYCONFIGPATH item and call:

nonmem_path<-"C:\\nm75g64\\run"


again with the same error.


What do you think?


Thank you,

Razan

________________________________

**Comment by stellabelin** [comment]
Hi! Just to double check, are you writing these paths as environment variables or as R variables? When Pharmpy looks for the configuration file it will look for the file `C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf`, so unless you change the _environment_ variable `PHARMPYCONFIGPATH` Pharmpy will still look for that file in AppData. What I think you need to do is to change the file `C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf` to have the NONMEM path etc., is this what you have tried?

**Comment by Razan2512** [comment]
Hey Stella,
Exactly, I changed the NONMEM path in the config file. The same issue persists.
Thanks,
Razan

**Comment by stellabelin** [comment]
Okay, and to double check another thing, you changed the file `C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf` and not `C:\Users\Razan\Desktop\Final_R_Data\Pharmpy\pharmpy.conf`?

**Comment by arcjohnsonj** [comment]
I am also having this same issue, this is what I have in my .conf file (I have tried several variations, no luck)

[pharmpy.plugins.nonmem]
default_nonmem_path=C:/nm75g64/run
licfile = C:/nm75g64/license/nonmem.lic

**Comment by Razan2512** [comment]
> Okay, and to double check another thing, you changed the file `C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf` and not `C:\Users\Razan\Desktop\Final_R_Data\Pharmpy\pharmpy.conf`?

**Comment by Razan2512** [comment]
Hey Stella,
Yes. 
I changed the file C:\\Users\\Razan\\AppData\\Local\\Pharmpy\\Pharmpy\\pharmpy.conf to the default NONMEM path.
I also added the path to nmfe to the PATH environment variable.
I also created an environmental variable called PHARMPYCONFIGPATH and added the correct path to it.
When I run get_config_path() in R -> it gives me the correct location of the pharmpy.conf file in APPDATA.
Again, without access.
