### ISSUE TITLE
run_amd for basic PK failed to finalize model search and proceed to IIV search

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#3187]
### Bug report

pharmr versions 1.0.1 and 1.1.0.

I used run_amd for basic_PK:

res_pk <- run_amd(input="TMDD_TYPE1_dataset_filtered.csv",
                  cl_init = init_cl,
                  vc_init = init_vc,
                  mat_init = init_mat, strategy = 'SIR',
                  administration='oral',
                  modeltype = "basic_pk")

I got the following bug report:

/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1208: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1230: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1327: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/miniconda/envs/r-reticulate/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/miniconda/envs/r-reticulate/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/miniconda/envs/r-reticulate/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/threadpoolexecutor.py", line 57, in _worker
    task.run()
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/_concurrent_futures_thread.py", line 65, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/utils.py", line 1550, in <lambda>
    executor, lambda: context.run(func, *args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/worker.py", line 2963, in apply_function
    msg = apply_function_simple(function, args, kwargs, time_delay)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/worker.py", line 3000, in apply_function_simple
    result = function(*args, **kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process
    res = create_results(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 97, in create_results
    summary_individuals, summary_individuals_count = summarize_tool_individuals(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 216, in summarize_tool_individuals
    summary_individuals = summarize_individuals(mes)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 64, in summarize_individuals
    df = pd.concat(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 504, in _clean_keys_and_objs
    objs_list = list(objs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 66, in <lambda>
    lambda me: groupedByIDAddColumnsOneModel(resDict, me),
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 146, in groupedByIDAddColumnsOneModel
    'predicted_dofv': predicted_dofv(model, model_res),
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 118, in predicted_dofv
    return _predicted(predict_influential_individuals, model, res, 'dofv')
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 103, in _predicted
    predicted = predict(model, res)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 245, in predict_influential_individuals
    output = _predict_with_tflite(model_path, data)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 296, in _predict_with_tflite
    interpreter = tflite.Interpreter(str(model_path))
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 464, in __init__
    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
AttributeError: _ARRAY_API not found
2024-07-24 12:35:16,149 - distributed.worker - WARNING - Compute Failed
Key:       run_candidate_models
State:     executing
Function:  post_process
args:      (ABSORPTION([FO,ZO,SEQ-ZO-FO]);ELIMINATION(FO);TRANSITS([0,1,3,10],*);PERIPHERALS(0..1);LAGTIME([OFF,ON]), 'bic', None, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', None, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x7fdfb140b130>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdfa97e2020>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdfa82d4880>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf998bb4f0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf99652b90>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf99472b60>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf9856ed40>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdfaa7f6620>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdfdf2513f0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf931b0370>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fdf99473610>, <pharmpy.workflows.model_en
kwargs:    {}
Exception: "SystemError('<built-in method CreateWrapperFromFile of PyCapsule object at 0x7fdf92847360> returned a result with an exception set')"
Traceback: '  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process\n    res = create_results(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 97, in create_results\n    summary_individuals, summary_individuals_count = summarize_tool_individuals(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 216, in summarize_tool_individuals\n    summary_individuals = summarize_individuals(mes)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 64, in summarize_individuals\n    df = pd.concat(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 382, in concat\n    op = _Concatenator(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 445, in __init__\n    objs, keys = self._clean_keys_and_objs(objs, keys)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 504, in _clean_keys_and_objs\n    objs_list = list(objs)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 66, in <lambda>\n    lambda me: groupedByIDAddColumnsOneModel(resDict, me),\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 146, in groupedByIDAddColumnsOneModel\n    \'predicted_dofv\': predicted_dofv(model, model_res),\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 118, in predicted_dofv\n    return _predicted(predict_influential_individuals, model, res, \'dofv\')\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 103, in _predicted\n    predicted = predict(model, res)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 245, in predict_influential_individuals\n    output = _predict_with_tflite(model_path, data)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 296, in _predict_with_tflite\n    interpreter = tflite.Interpreter(str(model_path))\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 464, in __init__\n    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(\n'

2024-07-24 12:35:16,158 - distributed.worker - WARNING - Compute Failed
Key:       start_modelsearch-results
State:     long-running
Function:  execute_task
args:      ((<function _results at 0x7fdfa9943d00>, (<function start at 0x7fdfa9943910>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x7fdfb140b130>, ABSORPTION([FO,ZO,SEQ-ZO-FO]);ELIMINATION(FO);TRANSITS([0,1,3,10],*);PERIPHERALS(0..1);LAGTIME([OFF,ON]), 'reduced_stepwise', 'absorption_delay', 'bic', None, <Pharmpy modelfit results object>, <Pharmpy model object start>, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', None)))
kwargs:    {}
Exception: "SystemError('<built-in method CreateWrapperFromFile of PyCapsule object at 0x7fdf92847360> returned a result with an exception set')"
Traceback: '  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 166, in start\n    res = call_workflow(wb, \'run_candidate_models\', context)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 2562, in gather\n    return self.sync(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process\n    res = create_results(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 97, in create_results\n    summary_individuals, summary_individuals_count = summarize_tool_individuals(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 216, in summarize_tool_individuals\n    summary_individuals = summarize_individuals(mes)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 64, in summarize_individuals\n    df = pd.concat(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 66, in <lambda>\n    lambda me: groupedByIDAddColumnsOneModel(resDict, me),\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 146, in groupedByIDAddColumnsOneModel\n    \'predicted_dofv\': predicted_dofv(model, model_res),\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 118, in predicted_dofv\n    return _predicted(predict_influential_individuals, model, res, \'dofv\')\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 103, in _predicted\n    predicted = predict(model, res)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 245, in predict_influential_individuals\n    output = _predict_with_tflite(model_path, data)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 296, in _predict_with_tflite\n    interpreter = tflite.Interpreter(str(model_path))\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 464, in __init__\n    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(\n'

<Client: 'inproc://172.17.0.7/341/1' processes=1 threads=12, memory=46.86 GiB>
<Client: 'inproc://172.17.0.7/341/10' processes=1 threads=12, memory=46.86 GiB>
Full stack:
SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0x7fdf92847360> returned a result with an exception set
Run `reticulate::py_last_error()` for details.SystemError<built-in method CreateWrapperFromFile of PyCapsule object at 0x7fdf92847360> returned a result with an exception setc("  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 491, in run_amd\n    subresults = func(next_model, next_res)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 700, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 248, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py\", line 3477, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py\", line 2562, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py\", line 166, in start\n    res = call_workflow(wb, 'run_candidate_models', context)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py\", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py\", line 302, in post_process\n    res = create_results(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py\", line 97, in create_results\n    summary_individuals, summary_individuals_count = summarize_tool_individuals(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py\", line 216, in summarize_tool_individuals\n    summary_individuals = summarize_individuals(mes)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py\", line 64, in summarize_individuals\n    df = pd.concat(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py\", line 66, in <lambda>\n    lambda me: groupedByIDAddColumnsOneModel(resDict, me),\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py\", line 146, in groupedByIDAddColumnsOneModel\n    'predicted_dofv': predicted_dofv(model, model_res),\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py\", line 118, in predicted_dofv\n    return _predicted(predict_influential_individuals, model, res, 'dofv')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py\", line 103, in _predicted\n    predicted = predict(model, res)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py\", line 245, in predict_influential_individuals\n    output = _predict_with_tflite(model_path, data)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py\", line 296, in _predict_with_tflite\n    interpreter = tflite.Interpreter(str(model_path))\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/tflite_runtime/interpreter.py\", line 464, in __init__\n    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(\n")ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 491, in run_amd
    subresults = func(next_model, next_res)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 700, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 248, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 3477, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 2562, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 166, in start
    res = call_workflow(wb, 'run_candidate_models', context)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process
    res = create_results(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 97, in create_results
    summary_individuals, summary_individuals_count = summarize_tool_individuals(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 216, in summarize_tool_individuals
    summary_individuals = summarize_individuals(mes)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 64, in summarize_individuals
    df = pd.concat(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 66, in <lambda>
    lambda me: groupedByIDAddColumnsOneModel(resDict, me),
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 146, in groupedByIDAddColumnsOneModel
    'predicted_dofv': predicted_dofv(model, model_res),
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 118, in predicted_dofv
    return _predicted(predict_influential_individuals, model, res, 'dofv')
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/summarize_individuals.py", line 103, in _predicted
    predicted = predict(model, res)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 245, in predict_influential_individuals
    output = _predict_with_tflite(model_path, data)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/funcs/ml.py", line 296, in _predict_with_tflite
    interpreter = tflite.Interpreter(str(model_path))
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/tflite_runtime/interpreter.py", line 464, in __init__
    self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
SystemError: <built-in method CreateWrapperFromFile of PyCapsule object at 0x7fdf92847360> returned a result with an exception set
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.SystemError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "TMDD_TYPE1_dataset_filtered.csv", cl_init = init_cl, vc_init = init_vc, mat_init = init_mat, strategy = "SIR", administration = "oral", modeltype = "basic_pk"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "TMDD_TYPE1_dataset_filtered.csv", cl_init = init_cl, 
    vc_init = init_vc, mat_init = init_mat, strategy = "SIR", administration = "oral", modeltype = "basic_pk"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.1.0
'1.1.0'
Pharmpy version: 1.1.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by stellabelin** [comment]
Hi, thanks for reporting! This looks to me like there is an issue with NumPy versions. For tflite (which is used for the ML functionality) it is limited to NumPy 1.x while the latest version is 2.x. If you downgrade NumPy in your environment to e.g. 1.26.4 this error should no longer occur. This is a temporary workaround, we're going to implement so that we support NumPy > 2.x.

**Comment by Orwa-bit** [comment]
Thank you so much. That resolved the issue.

**Comment by Orwa-bit** [comment]
For sure, thanks Rikard!
