### ISSUE TITLE
Parent - Metabolite - pharmr 1.2.0

### ISSUE THREAD

**Issue by SylvieRetout** [pharmpy/pharmpy#3324]
Hi All, @rikardn , @stellabelin , @emiliesg 
I am still facing an issue with the modeling of a parent-metabolite dataset using pharmr v1.2.0.
Please see the code I use below and the error message:

dataset_path <- "dataset_filtered2.csv"
sp <- "ABSORPTION([FO,SEQ-ZO-FO]);ELIMINATION(FO);LAGTIME([OFF,ON]);PERIPHERALS([0,1]);TRANSITS([0,1,3],*);METABOLITE(PSC);PERIPHERALS(0..1,MET)"

res = run_amd(dataset_path,
              search_space=sp,
              modeltype = "drug_metabolite", 
              administration="oral", 
              # order=order, 
              cl_init=1, vc_init=3.0, mat_init=0.1)

/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1208: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1230: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py:1312: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2024-09-02 13:38:23,816 - distributed.worker - ERROR - Compute Failed
Key:       run_candidate_models
State:     executing
Function:  post_process
args:      (ABSORPTION([FO,SEQ-ZO-FO]);ELIMINATION(FO);TRANSITS([0,1,3],*);PERIPHERALS(0..1);LAGTIME([OFF,ON]), 'bic', None, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', None, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x7fa7cdfc9570>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7ccd626e0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7cf4cc5b0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7b9738dc0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa79f51de40>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa79ffa3a90>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa79fe36020>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7c82ccac0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7c826ccd0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7cca64cd0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x7fa7b9c58130>, <pharmpy.workflows.model_entry.Mo
kwargs:    {}
Exception: "KeyError('[1, 3, 5, 7, 9, 13, 15, 17, 19, 24, 26, 28, 30, 32, 34, 36, 38, 40, 43, 45, 47, 49, 51, 53, 57, 59, 61, 64, 68, 70, 72, 74, 76, 78, 80, 82, 85, 87, 89, 91, 93, 95, 97, 101, 103, 106, 108, 112, 114, 116, 118, 120, 122, 124, 127, 129, 131, 133, 135, 137, 139, 141, 147, 149, 151, 153, 155, 157, 159, 161, 163, 168, 170, 172, 174, 178, 180, 182, 184, 186, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 210, 212, 214, 216, 218, 222, 224, 226, 230, 232, 234, 236, 238, 240, 244, 246, 248, 251, 255, 257, 259, 261, 263, 265, 267, 269, 272, 274, 276, 278, 280, 282, 284, 288, 290, 293, 295, 299, 301, 303, 305, 307, 309, 311, 314, 316, 318, 322, 324, 326, 328, 330, 332, 335, 337, 339, 341, 345, 347, 349, 351, 353, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 377, 381, 383, 385, 387, 389, 393, 395, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 419, 421, 423, 425, 429, 431, 433, 435, 437, 441, 443, 445, 447, 449, 451, 453, 455, 457, 460, 464, 466, 468, 470, 472, 476, 478, 482, 484, 488, 490, 492, 494, 496, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 524, 526, 528, 530, 532, 536, 538, 540, 543, 557, 559, 561, 564, 566, 568, 570, 572, 574, 576, 578, 580, 1260, 1262, 1263, 1265, 1275, 1277, 1284, 1285, 1287, 1290, 1299, 1301, 1303] not in index')"
Traceback: '  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process\n    res = create_results(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 130, in create_results\n    plots = create_plots(best_model, final_results)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 259, in create_plots\n    cwres_vs_idv_plot = plot_cwres_vs_idv(model, results.residuals, dvid_name)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 597, in plot_cwres_vs_idv\n    df = model.dataset.loc[residuals.index, columns]\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexing.py", line 1184, in __getitem__\n    return self._getitem_tuple(key)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexing.py", line 1375, in _getitem_tuple\n    return self._multi_take(tup)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexing.py", line 1326, in _multi_take\n    d = {\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexing.py", line 1327, in <dictcomp>\n    axis: self._get_listlike_indexer(key, axis)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexing.py", line 1558, in _get_listlike_indexer\n    keyarr, indexer = ax._get_indexer_strict(key, axis_name)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing\n    raise KeyError(f"{not_found} not in index")\n'

2024-09-02 13:38:23,823 - distributed.worker - ERROR - Compute Failed
Key:       start_modelsearch-results
State:     long-running
Function:  execute_task
args:      ((<function _results at 0x7fa7cbfb4b80>, (<function start at 0x7fa7cdf4a170>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x7fa7cdfc9570>, ABSORPTION([FO,SEQ-ZO-FO]);ELIMINATION(FO);TRANSITS([0,1,3],*);PERIPHERALS(0..1);LAGTIME([OFF,ON]), 'reduced_stepwise', 'absorption_delay', 'bic', None, <Pharmpy modelfit results object>, <Pharmpy model object start_filtered>, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', None)))
kwargs:    {}
Exception: "KeyError('[1, 3, 5, 7, 9, 13, 15, 17, 19, 24, 26, 28, 30, 32, 34, 36, 38, 40, 43, 45, 47, 49, 51, 53, 57, 59, 61, 64, 68, 70, 72, 74, 76, 78, 80, 82, 85, 87, 89, 91, 93, 95, 97, 101, 103, 106, 108, 112, 114, 116, 118, 120, 122, 124, 127, 129, 131, 133, 135, 137, 139, 141, 147, 149, 151, 153, 155, 157, 159, 161, 163, 168, 170, 172, 174, 178, 180, 182, 184, 186, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 210, 212, 214, 216, 218, 222, 224, 226, 230, 232, 234, 236, 238, 240, 244, 246, 248, 251, 255, 257, 259, 261, 263, 265, 267, 269, 272, 274, 276, 278, 280, 282, 284, 288, 290, 293, 295, 299, 301, 303, 305, 307, 309, 311, 314, 316, 318, 322, 324, 326, 328, 330, 332, 335, 337, 339, 341, 345, 347, 349, 351, 353, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 377, 381, 383, 385, 387, 389, 393, 395, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 419, 421, 423, 425, 429, 431, 433, 435, 437, 441, 443, 445, 447, 449, 451, 453, 455, 457, 460, 464, 466, 468, 470, 472, 476, 478, 482, 484, 488, 490, 492, 494, 496, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 524, 526, 528, 530, 532, 536, 538, 540, 543, 557, 559, 561, 564, 566, 568, 570, 572, 574, 576, 578, 580, 1260, 1262, 1263, 1265, 1275, 1277, 1284, 1285, 1287, 1290, 1299, 1301, 1303] not in index')"
Traceback: '  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 166, in start\n    res = call_workflow(wb, \'run_candidate_models\', context)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 2567, in gather\n    return self.sync(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process\n    res = create_results(\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 130, in create_results\n    plots = create_plots(best_model, final_results)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 259, in create_plots\n    cwres_vs_idv_plot = plot_cwres_vs_idv(model, results.residuals, dvid_name)\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 597, in plot_cwres_vs_idv\n    df = model.dataset.loc[residuals.index, columns]\n  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing\n    raise KeyError(f"{not_found} not in index")\n'

<Client: 'inproc://172.17.0.13/344/1' processes=1 threads=12, memory=46.86 GiB>
<Client: 'inproc://172.17.0.13/344/10' processes=1 threads=12, memory=46.86 GiB>
Full stack:
<...truncated...>186, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 210, 212, 214, 216, 218, 222, 224, 226, 230, 232, 234, 236, 238, 240, 244, 246, 248, 251, 255, 257, 259, 261, 263, 265, 267, 269, 272, 274, 276, 278, 280, 282, 284, 288, 290, 293, 295, 299, 301, 303, 305, 307, 309, 311, 314, 316, 318, 322, 324, 326, 328, 330, 332, 335, 337, 339, 341, 345, 347, 349, 351, 353, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 377, 381, 383, 385, 387, 389, 393, 395, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 419, 421, 423, 425, 429, 431, 433, 435, 437, 441, 443, 445, 447, 449, 451, 453, 455, 457, 460, 464, 466, 468, 470, 472, 476, 478, 482, 484, 488, 490, 492, 494, 496, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 524, 526, 528, 530, 532, 536, 538, 540, 543, 557, 559, 561, 564, 566, 568, 570, 572, 574, 576, 578, 580, 1260, 1262, 1263, 1265, 1275, 1277, 1284, 1285, 1287, 1290, 1299, 1301, 1303] not in index'
Run `reticulate::py_last_error()` for details.KeyError'[1, 3, 5, 7, 9, 13, 15, 17, 19, 24, 26, 28, 30, 32, 34, 36, 38, 40, 43, 45, 47, 49, 51, 53, 57, 59, 61, 64, 68, 70, 72, 74, 76, 78, 80, 82, 85, 87, 89, 91, 93, 95, 97, 101, 103, 106, 108, 112, 114, 116, 118, 120, 122, 124, 127, 129, 131, 133, 135, 137, 139, 141, 147, 149, 151, 153, 155, 157, 159, 161, 163, 168, 170, 172, 174, 178, 180, 182, 184, 186, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 210, 212, 214, 216, 218, 222, 224, 226, 230, 232, 234, 236, 238, 240, 244, 246, 248, 251, 255, 257, 259, 261, 263, 265, 267, 269, 272, 274, 276, 278, 280, 282, 284, 288, 290, 293, 295, 299, 301, 303, 305, 307, 309, 311, 314, 316, 318, 322, 324, 326, 328, 330, 332, 335, 337, 339, 341, 345, 347, 349, 351, 353, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 377, 381, 383, 385, 387, 389, 393, 395, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 419, 421, 423, 425, 429, 431, 433, 435, 437, 441, 443, 445, 447, 449, 451, 453, 455, 457, 460, 464, 466, 468, 470, 472, 476, 478, 482, 484, 488, 490, 492, 494, 496, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 524, 526, 528, 530, 532, 536, 538, 540, 543, 557, 559, 561, 564, 566, 568, 570, 572, 574, 576, 578, 580, 1260, 1262, 1263, 1265, 1275, 1277, 1284, 1285, 1287, 1290, 1299, 1301, 1303] not in index'c("  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 491, in run_amd\n    subresults = func(next_model, next_res)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py\", line 700, in _run_modelsearch\n    res = run_tool(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py\", line 248, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py\", line 3484, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py\", line 2567, in gather\n    return self.sync(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py\", line 166, in start\n    res = call_workflow(wb, 'run_candidate_models', context)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py\", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py\", line 302, in post_process\n    res = create_results(\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py\", line 130, in create_results\n    plots = create_plots(best_model, final_results)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py\", line 259, in create_plots\n    cwres_vs_idv_plot = plot_cwres_vs_idv(model, results.residuals, dvid_name)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py\", line 597, in plot_cwres_vs_idv\n    df = model.dataset.loc[residuals.index, columns]\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6252, in _raise_if_missing\n    raise KeyError(f\"{not_found} not in index\")\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 491, in run_amd
    subresults = func(next_model, next_res)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/amd/run.py", line 700, in _run_modelsearch
    res = run_tool(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/run.py", line 248, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 3484, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/distributed/client.py", line 2567, in gather
    return self.sync(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 166, in start
    res = call_workflow(wb, 'run_candidate_models', context)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/workflows/call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/modelsearch/tool.py", line 302, in post_process
    res = create_results(
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 130, in create_results
    plots = create_plots(best_model, final_results)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/tools/common.py", line 259, in create_plots
    cwres_vs_idv_plot = plot_cwres_vs_idv(model, results.residuals, dvid_name)
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pharmpy/modeling/plots.py", line 597, in plot_cwres_vs_idv
    df = model.dataset.loc[residuals.index, columns]
  File "/miniconda/envs/r-reticulate/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6252, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: '[1, 3, 5, 7, 9, 13, 15, 17, 19, 24, 26, 28, 30, 32, 34, 36, 38, 40, 43, 45, 47, 49, 51, 53, 57, 59, 61, 64, 68, 70, 72, 74, 76, 78, 80, 82, 85, 87, 89, 91, 93, 95, 97, 101, 103, 106, 108, 112, 114, 116, 118, 120, 122, 124, 127, 129, 131, 133, 135, 137, 139, 141, 147, 149, 151, 153, 155, 157, 159, 161, 163, 168, 170, 172, 174, 178, 180, 182, 184, 186, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207, 210, 212, 214, 216, 218, 222, 224, 226, 230, 232, 234, 236, 238, 240, 244, 246, 248, 251, 255, 257, 259, 261, 263, 265, 267, 269, 272, 274, 276, 278, 280, 282, 284, 288, 290, 293, 295, 299, 301, 303, 305, 307, 309, 311, 314, 316, 318, 322, 324, 326, 328, 330, 332, 335, 337, 339, 341, 345, 347, 349, 351, 353, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 377, 381, 383, 385, 387, 389, 393, 395, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 419, 421, 423, 425, 429, 431, 433, 435, 437, 441, 443, 445, 447, 449, 451, 453, 455, 457, 460, 464, 466, 468, 470, 472, 476, 478, 482, 484, 488, 490, 492, 494, 496, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519, 524, 526, 528, 530, 532, 536, 538, 540, 543, 557, 559, 561, 564, 566, 568, 570, 572, 574, 576, 578, 580, 1260, 1262, 1263, 1265, 1275, 1277, 1284, 1285, 1287, 1290, 1299, 1301, 1303] not in index'
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.KeyError", "python.builtin.LookupError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(dataset_path, search_space = sp, modeltype = "drug_metabolite", administration = "oral", cl_init = 1, vc_init = 3, mat_init = 0.1), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(dataset_path, search_space = sp, modeltype = "drug_metabolite", 
    administration = "oral", cl_init = 1, vc_init = 3, mat_init = 0.1), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by stellabelin** [comment]
Hi Sylvie! This error looks the same as #3203, we have been able to reproduce this locally and are working on a fix.

**Comment by rikardn** [comment]
This is indeed a duplicate of #3203. Next version will have  a fix.
