### ISSUE TITLE
error with PKPD (unable to find dosing records in the dataset)

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#3390]
### Bug report

> na_pkpd <- run_structsearch(type = "pkpd",
+                             model = start_model,
+                             results = start_model_results,
+                             # search_space = "DIRECTEFFECT(*)",
+                             search_space = "DIRECTEFFECT(*);EFFECTCOMP(*);INDIRECTEFFECT(*,*)",
+                             b_init = 400,
+                             emax_init = 600,
+                             ec50_init = 1,
+                             met_init = 1)
2024-10-21 11:11:36,856 - distributed.worker - WARNING - Compute Failed
Key:       run-results_remaining
Function:  execute_task
args:      ((<function bundle_results at 0x154841080>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x155b68d60>, <pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x15592b950>, <pharmpy.workflows.model_entry.ModelEntry object at 0x1557b12e0>)))
kwargs:    {}
Exception: "ValueError('Unable to find dosing records in the dataset')"

2024-10-21 11:11:36,864 - distributed.worker - WARNING - Compute Failed
Key:       results
Function:  run_pkpd
args:      (<pharmpy.workflows.context.local_directory.LocalDirectoryContext object at 0x15592b950>, <Pharmpy model object model>, <Pharmpy modelfit results object>, 'DIRECTEFFECT(*);EFFECTCOMP(*);INDIRECTEFFECT(*,*)', 400.0, 600.0, 1.0, 1.0, 'minimization_successful or (rounding_errors and sigdigs >= 0.1)')
kwargs:    {}
Exception: "ValueError('Unable to find dosing records in the dataset')"

<Client: 'inproc://130.238.35.53/81369/10' processes=1 threads=16, memory=32.00 GiB>
Full stack:
ValueError: Unable to find dosing records in the dataset
Run `reticulate::py_last_error()` for details.ValueErrorUnable to find dosing records in the datasetc("  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/wrap.py\", line 34, in func\n    return run_tool(tool_name, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 248, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py\", line 84, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py\", line 3275, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py\", line 2372, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py\", line 208, in run_pkpd\n    pd_baseline_fit = call_workflow(Workflow(wb), 'results_remaining', context)\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/call.py\", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n      ^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/modelfit/tool.py\", line 107, in task\n    me = execute_model(model_entry, context)\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/external/nonmem/run.py\", line 37, in execute_model\n    model_with_correct_datapath = database.retrieve_model(model)\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/model_database/baseclass.py\", line 428, in retrieve_model\n    return sn.retrieve_model()\n    ^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/model_database/local_directory.py\", line 341, in retrieve_model\n    model = Model.parse_model(path)\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/model.py\", line 678, in parse_model\n    model = model_module.parse_model(code, path, missing_data_token=missing_data_token)\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/model.py\", line 362, in parse_model\n    dataset = parse_dataset(di, control_stream, raw=False)\n    ^^^^^^^^^^^^^^^^^\n", 
"  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py\", line 885, in parse_dataset\n    df = filter_observations(df, di)\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py\", line 899, in filter_observations\n    raise ValueError(\"Unable to find dosing records in the dataset\")\n    ^^^^^^^^^^^^^^^^^\n")Traceback (most recent call last):
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py", line 891, in filter_observations
    label = di.typeix['mdv'][0].name
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/datainfo.py", line 1065, in __getitem__
    raise IndexError(f"No columns of type {i} available")
    ^^^^^^^^^^^^^^^^^
IndexError: No columns of type mdv available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py", line 894, in filter_observations
    label = di.typeix['event'][0].name
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/datainfo.py", line 1065, in __getitem__
    raise IndexError(f"No columns of type {i} available")
    ^^^^^^^^^^^^^^^^^
IndexError: No columns of type event available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py", line 897, in filter_observations
    label = di.typeix['dose'][0].name
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/datainfo.py", line 1065, in __getitem__
    raise IndexError(f"No columns of type {i} available")
    ^^^^^^^^^^^^^^^^^
IndexError: No columns of type dose available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/wrap.py", line 34, in func
    return run_tool(tool_name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/run.py", line 248, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask.py", line 84, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py", line 3275, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/distributed/client.py", line 2372, in gather
    return self.sync(
           ^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/structsearch/tool.py", line 208, in run_pkpd
    pd_baseline_fit = call_workflow(Workflow(wb), 'results_remaining', context)
      ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
      ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/modelfit/tool.py", line 107, in task
    me = execute_model(model_entry, context)
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/tools/external/nonmem/run.py", line 37, in execute_model
    model_with_correct_datapath = database.retrieve_model(model)
      ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/model_database/baseclass.py", line 428, in retrieve_model
    return sn.retrieve_model()
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/workflows/model_database/local_directory.py", line 341, in retrieve_model
    model = Model.parse_model(path)
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/model.py", line 678, in parse_model
    model = model_module.parse_model(code, path, missing_data_token=missing_data_token)
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/model.py", line 362, in parse_model
    dataset = parse_dataset(di, control_stream, raw=False)
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py", line 885, in parse_dataset
    df = filter_observations(df, di)
    ^^^^^^^^^^^^^^^^^
  File "/Users/xiach933/.virtualenvs/pharmr2/lib/python3.12/site-packages/pharmpy/model/external/nonmem/parsing.py", line 899, in filter_observations
    raise ValueError("Unable to find dosing records in the dataset")
    ^^^^^^^^^^^^^^^^^
ValueError: Unable to find dosing records in the dataset
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.ValueError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_structsearch(type = "pkpd", model = start_model, results = start_model_results, search_space = "DIRECTEFFECT(*);EFFECTCOMP(*);INDIRECTEFFECT(*,*)", b_init = 400, emax_init = 600, ec50_init = 1, met_init = 1), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", 
"local", "local", "local", NA, ":::"), full_call = list(run_structsearch(type = "pkpd", model = start_model, results = start_model_results, search_space = "DIRECTEFFECT(*);EFFECTCOMP(*);INDIRECTEFFECT(*,*)", b_init = 400, emax_init = 600, ec50_init = 1, met_init = 1), tryCatch({
    func_out <- pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_structsearch(type, search_space = search_space, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, 
    met_init = met_init, results = results, model = model, extra_model = extra_model, strictness = strictness, extra_model_results = extra_model_results, dv_types = dv_types, ...), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0

But there is dosing records in the dataset:
> start_model$dataset %>% head()
   ID VISI GROUP DOSE TIME       DV AMT SS II EVID DVID
1 110    3     8  200  0.0   0.0000 200  0  0    1    1
2 110    3     8  200  0.0 814.0000   0  0  0    0    2
3 110    3     8  200  1.0   0.0834   0  0  0    0    1
4 110    3     8  200  1.0 700.0000   0  0  0    0    2
5 110    3     8  200  1.5   0.2225   0  0  0    0    1
6 110    3     8  200  2.0   0.4890   0  0  0    0    1

**Comment by rikardn** [comment]
This is due to two issues that needs to be fixed. The workaround is to use `datatype='nonmem'` in `set_dataset`.

Technical details:

If not using this option nothing is assumed about the types of the columns, and later Pharmpy cannot find the dose column. I think we could improve here in `set_dataset` and use the previous datainfo and/or look in the model or even make more assumptions on the types of the columns.

The second thing is that `structsearch` parses the datainfo when fitting the model which is also unnecessary. This is part of an older workaround.
