### ISSUE TITLE
run_amd(modeltype='tmdd') stops after modelsearch with a file not found error

### ISSUE THREAD

**Issue by Orwa-bit** [pharmpy/pharmpy#3395]
### Bug report

Pharmr v1.2.0 development version, please find below the attempt of run_amd(modeltype='tmdd')

init_cl  <- 0.6
> init_vc  <- 0.8
> init_mat <- 12
> res <- run_amd(input="TMDD_ALL_dataset_filtered.csv",
+                cl_init = init_cl,
+                vc_init = init_vc,
+                mat_init = init_mat,
+                administration = "oral",
+                modeltype='tmdd',
+                dv_types = list('drug_tot'= 1L,'target'= 2L)
+ )

+ . /miniconda/bin/activate
+ conda activate '/miniconda/envs/r-reticulate'
+ '/miniconda/envs/r-reticulate/bin/python' -m pip install --upgrade --no-user 'pharmpy-core'
Requirement already satisfied: pharmpy-core in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (1.2.0)
Requirement already satisfied: lark>=1.1.4 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (1.2.2)
Requirement already satisfied: sympy>=1.9 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (1.13.3)
Requirement already satisfied: symengine>=0.11.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (0.13.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (2.2.3)
Requirement already satisfied: numexpr>=2.7.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (2.10.1)
Requirement already satisfied: altair>=5.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (5.4.1)
Requirement already satisfied: jsonschema>=3.1.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (4.23.0)
Requirement already satisfied: sphinx>=2.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (8.1.3)
Requirement already satisfied: csscompressor>=0.9.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (0.9.5)
Requirement already satisfied: beautifulsoup4>=4.8.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (4.12.3)
Requirement already satisfied: lxml>=4.4.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (5.3.0)
Requirement already satisfied: numpy>=1.17 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (2.1.2)
Requirement already satisfied: scipy>=1.4.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (1.14.1)
Requirement already satisfied: dask>=2022.12.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (2024.10.0)
Requirement already satisfied: distributed>=2022.12.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (2024.10.0)
Requirement already satisfied: networkx>=2.3 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (3.4.1)
Requirement already satisfied: appdirs>=1.4.4 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (1.4.4)
Requirement already satisfied: rich>=4.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (13.9.2)
Requirement already satisfied: jupyter-sphinx>=0.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (0.5.3)
Requirement already satisfied: ipykernel>=5.4.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pharmpy-core) (6.29.5)
Requirement already satisfied: jinja2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from altair>=5.0.0->pharmpy-core) (3.1.4)
Requirement already satisfied: narwhals>=1.5.2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from altair>=5.0.0->pharmpy-core) (1.9.4)
Requirement already satisfied: packaging in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from altair>=5.0.0->pharmpy-core) (24.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from altair>=5.0.0->pharmpy-core) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from beautifulsoup4>=4.8.0->pharmpy-core) (2.6)
Requirement already satisfied: click>=8.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (8.1.7)
Requirement already satisfied: cloudpickle>=3.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (3.1.0)
Requirement already satisfied: fsspec>=2021.09.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (2024.9.0)
Requirement already satisfied: partd>=1.4.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from dask>=2022.12.1->pharmpy-core) (8.5.0)
Requirement already satisfied: locket>=1.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (1.1.0)
Requirement already satisfied: psutil>=5.8.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (6.1.0)
Requirement already satisfied: sortedcontainers>=2.0.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (3.0.0)
Requirement already satisfied: tornado>=6.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (6.4.1)
Requirement already satisfied: urllib3>=1.26.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (2.2.3)
Requirement already satisfied: zict>=3.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from distributed>=2022.12.1->pharmpy-core) (3.0.0)
Requirement already satisfied: comm>=0.1.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (1.8.7)
Requirement already satisfied: ipython>=7.23.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (8.28.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (0.1.7)
Requirement already satisfied: nest-asyncio in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (1.6.0)
Requirement already satisfied: pyzmq>=24 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (26.2.0)
Requirement already satisfied: traitlets>=5.4.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipykernel>=5.4.0->pharmpy-core) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jsonschema>=3.1.0->pharmpy-core) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jsonschema>=3.1.0->pharmpy-core) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jsonschema>=3.1.0->pharmpy-core) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jsonschema>=3.1.0->pharmpy-core) (0.20.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jupyter-sphinx>=0.2.0->pharmpy-core) (8.1.5)
Requirement already satisfied: nbconvert>=5.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jupyter-sphinx>=0.2.0->pharmpy-core) (7.16.4)
Requirement already satisfied: nbformat in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jupyter-sphinx>=0.2.0->pharmpy-core) (5.10.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->pharmpy-core) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->pharmpy-core) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.4->pharmpy-core) (2024.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from rich>=4.2.0->pharmpy-core) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from rich>=4.2.0->pharmpy-core) (2.18.0)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.0.0)
Requirement already satisfied: docutils<0.22,>=0.20 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (0.21.2)
Requirement already satisfied: snowballstemmer>=2.2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.2.0)
Requirement already satisfied: babel>=2.13 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.16.0)
Requirement already satisfied: alabaster>=0.7.14 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sphinx>=2.2.0->pharmpy-core) (2.32.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from sympy>=1.9->pharmpy-core) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from importlib-metadata>=4.13.0->dask>=2022.12.1->pharmpy-core) (3.20.2)
Requirement already satisfied: decorator in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.19.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (3.0.48)
Requirement already satisfied: stack-data in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.6.3)
Requirement already satisfied: pexpect>4.3 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (4.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.12 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipywidgets>=7.0.0->jupyter-sphinx>=0.2.0->pharmpy-core) (4.0.13)
Requirement already satisfied: jupyterlab-widgets~=3.0.12 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from ipywidgets>=7.0.0->jupyter-sphinx>=0.2.0->pharmpy-core) (3.0.13)
Requirement already satisfied: MarkupSafe>=2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jinja2->altair>=5.0.0->pharmpy-core) (3.0.1)
Requirement already satisfied: platformdirs>=2.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=5.4.0->pharmpy-core) (4.3.6)
Requirement already satisfied: mdurl~=0.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=4.2.0->pharmpy-core) (0.1.2)
Requirement already satisfied: bleach!=5.0.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (6.1.0)
Requirement already satisfied: defusedxml in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (0.10.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (1.5.1)
Requirement already satisfied: tinycss2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (1.3.0)
Requirement already satisfied: fastjsonschema>=2.15 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from nbformat->jupyter-sphinx>=0.2.0->pharmpy-core) (2.20.0)
Requirement already satisfied: six>=1.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->pharmpy-core) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from requests>=2.30.0->sphinx>=2.2.0->pharmpy-core) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from requests>=2.30.0->sphinx>=2.2.0->pharmpy-core) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from requests>=2.30.0->sphinx>=2.2.0->pharmpy-core) (2024.8.30)
Requirement already satisfied: webencodings in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from bleach!=5.0.0->nbconvert>=5.5->jupyter-sphinx>=0.2.0->pharmpy-core) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.7.0)
Requirement already satisfied: wcwidth in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (2.4.1)
Requirement already satisfied: pure-eval in /miniconda/envs/r-reticulate/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel>=5.4.0->pharmpy-core) (0.2.3)
Done!
/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py:1223: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py:1245: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py:1342: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
amd1                  2024-10-22     INFO    Dispatching workflow: <Client:     
                      15:42:23               'inproc://172.17.0.5/341/1'        
                                             processes=1 threads=12,            
                                             memory=46.86 GiB>                  
amd1                  2024-10-22     INFO    End dispatch                       
                      15:46:16                                                  
amd1/modelsearch      2024-10-22     INFO    Dispatching workflow: <Client:     
                      15:46:17               'inproc://172.17.0.5/341/10'       
                                             processes=1 threads=12,            
                                             memory=46.86 GiB>                  
amd1/modelsearch      2024-10-22     INFO    End dispatch                       
                      18:59:12                                                  
Full stack:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp7jvs2o4r/_static/documentation_options.js?v=d6d90d09'
Run `reticulate::py_last_error()` for details.FileNotFoundError[Errno 2] No such file or directory: '/tmp/tmp7jvs2o4r/_static/documentation_options.js?v=d6d90d09'c("  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py\", line 506, in run_amd\n    subresults = func(next_model, next_res)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py\", line 756, in _run_structsearch_tmdd\n    res = run_tool(\n          ^^^^^^^^^\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/run.py\", line 248, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/workflows/execute.py\", line 87, in execute_workflow\n    create_report(res, context.path)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/reporting.py\", line 29, in create_report\n    reporting.generate_report(get_rst_path(results), json_path, path)\n", 
"  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/reporting/reporting.py\", line 96, in generate_report\n    embed_css_and_js(tmp_path / 'results.html', report_path)\n", "  File \"/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/reporting/reporting.py\", line 131, in embed_css_and_js\n    with open(path, 'r') as sh:\n         ^^^^^^^^^^^^^^^\n")Traceback (most recent call last):
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py", line 506, in run_amd
    subresults = func(next_model, next_res)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/amd/run.py", line 756, in _run_structsearch_tmdd
    res = run_tool(
          ^^^^^^^^^
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/run.py", line 248, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/workflows/execute.py", line 87, in execute_workflow
    create_report(res, context.path)
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/tools/reporting.py", line 29, in create_report
    reporting.generate_report(get_rst_path(results), json_path, path)
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/reporting/reporting.py", line 96, in generate_report
    embed_css_and_js(tmp_path / 'results.html', report_path)
  File "/miniconda/envs/r-reticulate/lib/python3.11/site-packages/pharmpy/reporting/reporting.py", line 131, in embed_css_and_js
    with open(path, 'r') as sh:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp7jvs2o4r/_static/documentation_options.js?v=d6d90d09'
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.FileNotFoundError", "python.builtin.OSError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "TMDD_ALL_dataset_filtered.csv", cl_init = init_cl, vc_init = init_vc, mat_init = init_mat, administration = "oral", modeltype = "tmdd", dv_types = list(drug_tot = 1, target = 2)), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "TMDD_ALL_dataset_filtered.csv", cl_init = init_cl, 
    vc_init = init_vc, mat_init = init_mat, administration = "oral", modeltype = "tmdd", dv_types = list(drug_tot = 1, target = 2)), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.2.0
'1.2.0'
Pharmpy version: 1.2.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!

**Comment by leovuong** [comment]
hi @stellabelin, thanks for picking up on this issue. It happened when I excecuted the run_amd() command for my dataset with the "basic_pk" option. I also used version 1.2 as @Orwa-bit

**Comment by Orwa-bit** [comment]
All good yes this is solved already. Thanks!
