### ISSUE TITLE
sphinx.errors.ExtensionError: Notebook execution failed (exception: [WinError 6] The handle is invalid)

### ISSUE THREAD

**Issue by duvnjakzrinka** [pharmpy/pharmpy#3399]
### Bug report

Hi,

It is great to see how rapidly pharmpy is being developed, thanks for that! 

Recently I installed the new pharmpy/pharmr version 1.3.0 and tried to do a test AMD tool run (strategy = "SIR"). The modelsearch finished (the results.csv file in the modelsearch subfolder looks okay), however, it did not manage to continue with IIVsearch (no models created in any other subfolder). Instead, the error was raised: **"sphinx.errors.ExtensionError: Notebook execution failed (exception: [WinError 6] The handle is invalid)"**.
I was not sure if this problem was related to an already opened issue: #3078 

I have Python v.3.12, pip v.24.2, and versions of R packages can be found in the attached renv.lock (uploaded as a txt file)

Thank you in advance!
[renv.lock.txt](https://github.com/user-attachments/files/17530639/renv.lock.txt)

This was the function call:
```
res <- run_amd(input='data5_2.csv',
               modeltype='basic_pk',
               administration='oral',
               cl_init=8.0,
               vc_init=1000.0,
               mat_init=3.0,
               strategy='SIR',
               search_space='ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)',
               strictness = 'minimization_successful'
)
```

This was printed out:
```
amd2                  2024-10-26     INFO   Starting tool amd                  
                      13:49:26                                                 
\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\amd\run.py:1287: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\amd\run.py:1309: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\amd\run.py:1391: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
amd2/modelfit         2024-10-26     INFO   Dispatching workflow: <Client:     
                      13:49:30              'inproc://130.133.44.73/18168/19'  
                                            processes=1 threads=12,            
                                            memory=15.24 GiB>                  
amd2/modelfit         2024-10-26     INFO   End dispatch                       
                      13:49:42                                                 
amd2/modelsearch      2024-10-26     INFO   Dispatching workflow: <Client:     
                      13:49:44              'inproc://130.133.44.73/18168/28'  
                                            processes=1 threads=12,            
                                            memory=15.24 GiB>                  
amd2/modelsearch      2024-10-26     INFO   Starting tool modelsearch          
                      13:49:44                                                 
amd2/modelsearch      2024-10-26     INFO   Finishing tool modelsearch         
                      13:50:42                                                 
amd2/modelsearch      2024-10-26     INFO   End dispatch                       
                      13:50:42                                                 
Full stack:
sphinx.errors.ExtensionError: Notebook execution failed (exception: [WinError 6] The handle is invalid)
Run `reticulate::py_last_error()` for details.ExtensionErrorNotebook execution failed (exception: [WinError 6] The handle is invalid)c("  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 530, in run_amd\n    subresults = func(next_model, next_res)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 760, in _run_modelsearch\n    res = run_tool(\n          ^^^^^^^^^\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\tools\\run.py\", line 244, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\workflows\\execute.py\", line 87, in execute_workflow\n    create_report(res, context.path)\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\tools\\reporting.py\", line 29, in create_report\n    reporting.generate_report(get_rst_path(results), json_path, path)\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\reporting\\reporting.py\", line 76, in generate_report\n    app.build()\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\application.py\", line 355, in build\n    self.builder.build_update()\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\builders\\__init__.py\", line 290, in build_update\n    self.build(['__all__'], to_build)\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\builders\\__init__.py\", line 313, in build\n    updated_docnames = set(self.read())\n                           ^^^^^^^^^^^\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\builders\\__init__.py\", line 420, in read\n    self._read_serial(docnames)\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\builders\\__init__.py\", line 441, in _read_serial\n    self.read_doc(docname)\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\builders\\__init__.py\", line 498, in read_doc\n    publisher.publish()\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\docutils\\core.py\", line 236, in publish\n    self.apply_transforms()\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\docutils\\core.py\", line 216, in apply_transforms\n    self.document.transformer.apply_transforms()\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\sphinx\\transforms\\__init__.py\", line 83, in apply_transforms\n    super().apply_transforms()\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\docutils\\transforms\\__init__.py\", line 182, in apply_transforms\n    transform.apply(**kwargs)\n", 
"  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\reporting\\jupyter_sphinx\\execute.py\", line 151, in apply\n    notebook = execute_cells(\n               ^^^^^^^^^^^^^^\n", "  File \"\\\\camcl04user.campus.fu-berlin.de\\home_z\\zrinkaduvnj\\.virtualenvs\\r-reticulate\\Lib\\site-packages\\pharmpy\\reporting\\jupyter_sphinx\\execute.py\", line 275, in execute_cells\n    raise ExtensionError(\"Notebook execution failed\", orig_exc=e)\n"
)Traceback (most recent call last):
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\reporting\jupyter_sphinx\execute.py", line 273, in execute_cells
    executenb(notebook, **execute_kwargs)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\312~1.1\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\nbclient\client.py", line 693, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "C:\Users\ZRINKA~1\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\312~1.1\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\nbclient\client.py", line 648, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\nbclient\client.py", line 550, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_core\utils\__init__.py", line 198, in ensure_async
    result = await obj
             ^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\manager.py", line 96, in wrapper
    raise e
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\jupyter_client\launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zrinkaduvnj\Downloads\Pharmpy\renv\library\R-4.3\x86_64-w64-mingw32\reticulate\python\rpytools\subprocess.py", line 15, in __init__
    return og_Popen__init__(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\312~1.1\Lib\subprocess.py", line 992, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\AppData\Local\R-RETI~1\R-RETI~1\pyenv\PYENV-~1\versions\312~1.1\Lib\subprocess.py", line 1368, in _get_handles
    c2pwrite = _winapi.GetStdHandle(_winapi.STD_OUTPUT_HANDLE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\amd\run.py", line 530, in run_amd
    subresults = func(next_model, next_res)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\amd\run.py", line 760, in _run_modelsearch
    res = run_tool(
          ^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\run.py", line 244, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\workflows\execute.py", line 87, in execute_workflow
    create_report(res, context.path)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\tools\reporting.py", line 29, in create_report
    reporting.generate_report(get_rst_path(results), json_path, path)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\reporting\reporting.py", line 76, in generate_report
    app.build()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\application.py", line 355, in build
    self.builder.build_update()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\builders\__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\builders\__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\builders\__init__.py", line 420, in read
    self._read_serial(docnames)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\builders\__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\builders\__init__.py", line 498, in read_doc
    publisher.publish()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\docutils\core.py", line 236, in publish
    self.apply_transforms()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\docutils\core.py", line 216, in apply_transforms
    self.document.transformer.apply_transforms()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\sphinx\transforms\__init__.py", line 83, in apply_transforms
    super().apply_transforms()
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\docutils\transforms\__init__.py", line 182, in apply_transforms
    transform.apply(**kwargs)
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\reporting\jupyter_sphinx\execute.py", line 151, in apply
    notebook = execute_cells(
               ^^^^^^^^^^^^^^
  File "\\camcl04user.campus.fu-berlin.de\home_z\zrinkaduvnj\.virtualenvs\r-reticulate\Lib\site-packages\pharmpy\reporting\jupyter_sphinx\execute.py", line 275, in execute_cells
    raise ExtensionError("Notebook execution failed", orig_exc=e)
sphinx.errors.ExtensionError: Notebook execution failed (exception: [WinError 6] The handle is invalid)
py_call_impl(callable, call_args$unnamed, call_args$named)c("sphinx.errors.ExtensionError", "sphinx.errors.SphinxError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = "data/data5_2.csv", modeltype = "basic_pk", administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", strictness = "minimization_successful"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = "data/data5_2.csv", modeltype = "basic_pk", 
    administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", strictness = "minimization_successful"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.3.0
'1.3.0'
Pharmpy version: 1.3.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!
```

**Comment by duvnjakzrinka** [comment]
I tried to triage this problem a bit more and this is what I discovered:

In my environment, the problem was not only with run_amd(), but also with all other subtool calls (all crashing with the same error message, at the point when the HTML report should be created). I also tested v.1.1.0 (the version before some fix with a similar error message was introduced), but it did not help. The pharmpy/pharmr v.0.105 is the version I used before and that worked for me, so I tried to reinstall that one again - however that one now also had the same issue. The next thing was to create a new clean python virtual environment since the error seemed to be related to python. I also tried to run the run_amd() in python, using reticulate::repl_python(), but I again got the same error. The thing is that all these tests I was performing using Rstudio IDE - either using pharmr either pharmpy through reticulate::repl_python()).

**After executing run_amd() outside of Rstudio (either pharmr or pharmpy), I would not get the error, so this problem must be related to Rstudio.** 

I'm not sure which Rstudio version I had when this problem was not appearing. I now tested versions 2024.09.0 and 2023.06.02 and with both the same error would be raised. Unfortunately, deleting all files related to Rstudio and reinstalling everything did not help in my case and I was not able to track the issue further.

Even though this in the end was not a pharmpy bug, I hope it helps those with a similar issue.

**Comment by rikardn** [comment]
Thanks for reporting this. I suspect this to be the same issue as reported at the end of https://github.com/pharmpy/pharmpy/issues/3012. Let us use only this issue for further discussion.

What we know so far:

1. It happens only on Windows
2. It happens only when running pharmr in Rstudio not in plain R
3. It happens when generating the report using jupyter-sphinx from sphinx
4. It is due to a problematic file handle for stdout (i.e. output to the console)
5. @liangqiongyue have tried to redirect stdout inside jupyter-sphinx to DEVNULL without success.

I will try again to see if I can reproduce the issue.

**Comment by stellabelin** [comment]
Can be recreated with the current PKPD environment.

**Comment by rikardn** [comment]
This should be fixed in the next version of Pharmpy. Here is the commit: 2f5453657d25c8596adb2bf023979c2be7417522

Thanks @duvnjakzrinka and @liangqiongyue for the help with debugging this.
