### ISSUE TITLE
lloq_limit argument of run_amd() - TypeError: Invalid `lloq_limit`: got `0.05` of type <class 'float'>, expected typing.Optional[str]

### ISSUE THREAD

**Issue by duvnjakzrinka** [pharmpy/pharmpy#3404]
### Bug report

Hi,

I'm using pharmpy/pharmr v.1.3.0.

It is great that you implmented handling of BLOQ values inside the and run, thanks! However, even though it seems obvious, I was not sure what to pass to the argument "lloq_limit". I tried passing both the numeric value and a string, but both raised an error. It would be amazing if you could expand the documentation a bit on this topic and provide an example. Thank you in advance!

Passing the number:
```

res3 <- run_amd(input = dataset_path, 
+                 modeltype='basic_pk', 
+                 administration='oral', 
+                 cl_init=8.0, 
+                 vc_init=1000.0, 
+                 mat_init=3.0, 
+                 strategy='SIR',
+                 search_space='ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)',
+                 lloq_limit = 0.05,
+                 lloq_method = 'm3'
+ )
amd45                 2024-10-28     INFO   Starting tool amd                  
                      10:57:51                                                 
Full stack:
**TypeError: Invalid `lloq_limit`: got `0.05` of type <class 'float'>, expected typing.Optional[str]**
Run `reticulate::py_last_error()` for details.TypeErrorInvalid `lloq_limit`: got `0.05` of type <class 'float'>, expected typing.Optional[str]c("  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 253, in run_amd\n    to_be_skipped = validate_input(**args)\n                    ^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\internals\\fn\\type.py\", line 39, in _wrapped\n    raise TypeError(\n")Traceback (most recent call last):
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\tools\amd\run.py", line 253, in run_amd
    to_be_skipped = validate_input(**args)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\internals\fn\type.py", line 39, in _wrapped
    raise TypeError(
TypeError: Invalid `lloq_limit`: got `0.05` of type <class 'float'>, expected typing.Optional[str]
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.TypeError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = dataset_path, modeltype = "basic_pk", administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, strategy = "SIR", search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", lloq_limit = 0.05, lloq_method = "m3"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = dataset_path, modeltype = "basic_pk", 
    administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, strategy = "SIR", search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", lloq_limit = 0.05, lloq_method = "m3"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.3.0
'1.3.0'
Pharmpy version: 1.3.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!


```

Passing a string:
```

res3 <- run_amd(input = dataset_path, 
+                 modeltype='basic_pk', 
+                 administration='oral', 
+                 cl_init=8.0, 
+                 vc_init=1000.0, 
+                 mat_init=3.0, 
+                 strategy='SIR',
+                 search_space='ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)',
+                 lloq_limit = '0.05',
+                 lloq_method = 'm3'
+ )
amd47                 2024-10-28     INFO   Starting tool amd                  
                      10:59:09                                                 
C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\tools\amd\run.py:1287: UserWarning: IOVsearch will be skipped because occasion is None.
  warnings.warn('IOVsearch will be skipped because occasion is None.')
C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\tools\amd\run.py:1309: UserWarning: Allometry will be skipped because allometric_variable is None and could not be inferred through .datainfo via "body weight" descriptor.
  warnings.warn(
C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\tools\amd\run.py:1391: UserWarning: COVsearch will be skipped because no covariates were given or could be extracted. Check search_space definition and .datainfo usage of "covariate" type and "continuous" flag.
  warnings.warn(
Full stack:
**TypeError: must be real number, not str**
Run `reticulate::py_last_error()` for details.TypeErrormust be real number, not strc("  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\tools\\amd\\run.py\", line 259, in run_amd\n    model = transform_blq(\n            ^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\modeling\\blq.py\", line 143, in transform_blq\n    model = _m3_m4_method(model, indicator, indicator_type, level, level_type, lometh)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\modeling\\blq.py\", line 232, in _m3_m4_method\n    lloq = Assignment(symbol, Expr.float(value))\n                              ^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\ZRINKA~1\\DOWNLO~1\\R-VIRT~1\\VIRTUA~1\\Lib\\site-packages\\pharmpy\\basic\\expr.py\", line 238, in float\n    x = symengine.RealDouble(value)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"symengine_wrapper.pyx\", line 1977, in symengine.lib.symengine_wrapper.RealDouble.__new__\n"
)Traceback (most recent call last):
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\tools\amd\run.py", line 259, in run_amd
    model = transform_blq(
            ^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\modeling\blq.py", line 143, in transform_blq
    model = _m3_m4_method(model, indicator, indicator_type, level, level_type, lometh)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\modeling\blq.py", line 232, in _m3_m4_method
    lloq = Assignment(symbol, Expr.float(value))
                              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ZRINKA~1\DOWNLO~1\R-VIRT~1\VIRTUA~1\Lib\site-packages\pharmpy\basic\expr.py", line 238, in float
    x = symengine.RealDouble(value)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "symengine_wrapper.pyx", line 1977, in symengine.lib.symengine_wrapper.RealDouble.__new__
TypeError: must be real number, not str
py_call_impl(callable, call_args$unnamed, call_args$named)c("python.builtin.TypeError", "python.builtin.Exception", "python.builtin.BaseException", "python.builtin.object", "error", "condition")list(call = list(run_amd(input = dataset_path, modeltype = "basic_pk", administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, strategy = "SIR", search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", lloq_limit = "0.05", lloq_method = "m3"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)), parent = c(0, 1, 2, 3, 4, 3, 6, 7, 1, 9), visible = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE), namespace = c("pharmr", "base", "base", "base", "base", "base", "base", "base", NA, "reticulate"), scope = c("::", "::", "local", "local", "local", "local", "local", "local", NA, ":::"), full_call = list(run_amd(input = dataset_path, modeltype = "basic_pk", 
    administration = "oral", cl_init = 8, vc_init = 1000, mat_init = 3, strategy = "SIR", search_space = "ABSORPTION([FO,ZO]);PERIPHERALS([0,1]);LAGTIME(ON)", lloq_limit = "0.05", lloq_method = "m3"), tryCatch({
    mechanistic_covariates <- convert_input(mechanistic_covariates, "list")
    seed <- convert_input(seed, "int")
    func_out <- pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, 
        mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E)
    if ("pharmpy.workflows.results.Results" %in% class(func_out)) {
        func_out <- reset_indices_results(func_out)
    }
    return(py_to_r(func_out))
}, error = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}, warning = function(cond) {
    err <- reticulate::py_last_error()
    if (is.null(err)) {
        message(cond)
    }
    else if (err$type == "InputValidationError") {
        message(err$value)
    }
    else {
        message("Full stack:")
        message(cond)
        message(err)
        message("pharmr version: ", packageVersion("pharmr"))
        message("Pharmpy version: ", print_pharmpy_version())
        message("This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!")
    }
    return(NA)
}), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), names[nh], parentenv, handlers[[nh]]), doTryCatch(return(expr), name, parentenv, handler), tryCatchList(expr, names[-nh], parentenv, handlers[-nh]), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), pharmpy$tools$run_amd(input, results = results, modeltype = modeltype, administration = administration, strategy = strategy, 
    cl_init = cl_init, vc_init = vc_init, mat_init = mat_init, b_init = b_init, emax_init = emax_init, ec50_init = ec50_init, met_init = met_init, search_space = search_space, lloq_method = lloq_method, lloq_limit = lloq_limit, allometric_variable = allometric_variable, occasion = occasion, path = path, resume = resume, strictness = strictness, dv_types = dv_types, mechanistic_covariates = mechanistic_covariates, retries_strategy = retries_strategy, seed = seed, parameter_uncertainty_method = parameter_uncertainty_method, 
    ignore_datainfo_fallback = ignore_datainfo_fallback, `_E` = .E), py_call_impl(callable, call_args$unnamed, call_args$named)))
pharmr version: 1.3.0
'1.3.0'
Pharmpy version: 1.3.0
This is a BUG. Please report it at https://github.com/pharmpy/pharmpy/issues. Thanks!
```

**Comment by rikardn** [comment]
Thanks for reporting this. What you are experiencing is a bug. The `lloq_limit` should indeed be a value, but that doesn't seem to work.

**Comment by rikardn** [comment]
This option was broken. The fix should be available in the next release.

**Comment by duvnjakzrinka** [comment]
Amazing, thank you!
