### ISSUE TITLE
covsearch in AMD failed when IOV exists

### ISSUE THREAD

**Issue by yahanhsutw** [pharmpy/pharmpy#3429]
### Bug report

**Pharmpy version**: 1.3.0

**Issue**: Full AMD fails in _covsearch_ step, while the standalone _covsearch_ with same search space works. This happens only when IOV on any parameter was selected in the previous _iovsearch_ step.

**Error message**:
(Full message: "/crex/proj/pmgroup_active_storage/private/users/yahan/AMD/Barbara/amd_sse_100/test/amd_test.Rout")

2024-11-08 17:37:59,715 - distributed.worker - ERROR - Compute Failed
Key:       VC-run9-1d57ef9f-fe80-4588-abc4-963cc3dda920
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('VC', 'WT', 'lin', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='VC', covariate='WT', effect='lin', operation='*')), 10)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,717 - distributed.worker - ERROR - Compute Failed
Key:       MAT-run7-8b5efa32-6c4d-4a3f-a0bf-8236fd3c7932
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('MAT', 'AGE', 'lin', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='MAT', covariate='AGE', effect='lin', operation='*')), 8)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,717 - distributed.worker - ERROR - Compute Failed
Key:       CL-run2-0d5bef8e-ace2-4c7b-ad00-b830d00f5ea7
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('CL', 'AGE', 'exp', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='CL', covariate='AGE', effect='exp', operation='*')), 3)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,718 - distributed.worker - ERROR - Compute Failed
Key:       MAT-run5-8f3a6c9b-1f96-4d5d-9cb6-7e6a524ccff0
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('MAT', 'WT', 'lin', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='MAT', covariate='WT', effect='lin', operation='*')), 6)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,719 - distributed.worker - ERROR - Compute Failed
Key:       CL-run3-32f76d22-5a4e-4293-8775-5a704ef508c9
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('CL', 'AGE', 'lin', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='CL', covariate='AGE', effect='lin', operation='*')), 4)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,726 - distributed.worker - ERROR - Compute Failed
Key:       MAT-run6-43ecdd1f-457d-4a8c-a7d0-fe33e9f706c9
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('MAT', 'AGE', 'exp', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='MAT', covariate='AGE', effect='exp', operation='*')), 7)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,728 - distributed.worker - ERROR - Compute Failed
Key:       VC-run8-30fda361-6d02-471b-b9ce-5bb5256605eb
State:     executing
Function:  execute_task
args:      ((<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x2ad366d60c20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, (<function task_add_covariate_effect at 0x2ad366ef20c0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, Candidate(modelentry=<pharmpy.workflows.model_entry.ModelEntry object at 0x2ad3475df6e0>, steps=()), (('VC', 'WT', 'exp', '*'), functools.partial(<function add_covariate_effect at 0x2ad2f9169d00>, parameter='VC', covariate='WT', effect='exp', operation='*')), 9)))
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n'

2024-11-08 17:37:59,776 - distributed.worker - ERROR - Compute Failed
Key:       backward-search-create_modelentry-forward-search-init-store_input_model-results
State:     long-running
Function:  execute_task
args:      ((<function task_results at 0x2ad366ef2340>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, 0.01, 0.001, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', (<function task_greedy_backward_search at 0x2ad366ef1e40>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, 0.001, -1, 0, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', (<function task_greedy_forward_search at 0x2ad366ef1bc0>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, 0.01, -1, 0, 'minimization_successful or (rounding_errors and sigdigs>=0.1)', False, (<function _init_search_state at 0x2ad366ef0180>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x2ad2f86278c0>, COVARIATE?([CL,MAT,VC],[AGE,WT],[LIN,EXP]);COVARIATE?([CL,MAT,VC],PREGNANCY,CAT), 'scm-forward-then-backward', (<function _start at 0x2ad366ef13a0>, <Pharmpy model object fin
kwargs:    {}
Exception: 'AssertionError()'
Traceback: '  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 380, in task_greedy_forward_search\n    return _greedy_search(\n           ^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 468, in _greedy_search\n    nonsignificant_effects, all_candidates_so_far, best_candidate_so_far = perform_step_procedure(\n                                                                           ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 548, in perform_step_procedure\n    new_candidates = handle_effects(\n                     ^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 374, in handle_effects\n    new_candidate_modelentries = context.call_workflow(wf, f\'{NAME_WF}-effects_addition-{step}\')\n                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/contexts/baseclass.py", line 237, in call_workflow\n    res = call_workflow(workflow, unique_name, self)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask/call.py", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n             ^^^^^^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/client.py", line 2556, in gather\n    return self.sync(\n           ^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n      ^^^^^^^^^^^^^^^^^\n  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n      ^^^^^^^^^^^^^^^^^\n'

2024-11-08 17:37:59,803 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('CL-run1-f6c2b4ea-c53f-47c6-a163-d306a9e7af7a')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,803 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('MAT-run13-af639312-7d28-4196-9c31-533ecf44da4f')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,804 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('VC-run10-abb639f3-24a1-4bd6-92f4-685a7344a34e')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,804 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('CL-run0-f4dada9e-7263-4e8f-9a5d-32df304af34c')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,804 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('VC-run11-885152fd-6131-456f-92c2-0fcfbaba3d74')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,804 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('CL-run12-c3645eca-929c-4c73-b090-eed8826917df')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
2024-11-08 17:37:59,805 - distributed.worker.state_machine - WARNING - Async instruction for <Task cancelled name="execute('VC-run14-f6b88f74-59f2-40f5-ab52-2aa3a174d268')" coro=<Worker.execute() done, defined at /domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/worker_state_machine.py:3609>> ended with CancelledError
Full stack:
AssertionError
Run `reticulate::py_last_error()` for details.AssertionErrorc("  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/amd/run.py\", line 530, in run_amd\n    subresults = func(next_model, next_res)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/amd/run.py\", line 1104, in _run_mechanistic_exploratory_covariates\n    res = run_tool(\n          ^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 189, in run_tool\n    return run_tool_with_name(name, tool, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/run.py\", line 244, in run_tool_with_name\n    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/execute.py\", line 73, in execute_workflow\n    res: T = dispatcher.run(workflow, context)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask/run.py\", line 85, in run\n    res = client.get(dsk_optimized, 'results')\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/client.py\", line 3483, in get\n    results = self.gather(packed, asynchronous=asynchronous, direct=direct)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/client.py\", line 2556, in gather\n    return self.sync(\n           ^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py\", line 380, in task_greedy_forward_search\n    return _greedy_search(\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py\", line 468, in _greedy_search\n    nonsignificant_effects, all_candidates_so_far, best_candidate_so_far = perform_step_procedure(\n      ^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py\", line 548, in perform_step_procedure\n    new_candidates = handle_effects(\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py\", line 374, in handle_effects\n    new_candidate_modelentries = context.call_workflow(wf, f'{NAME_WF}-effects_addition-{step}')\n    ^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/contexts/baseclass.py\", line 237, in call_workflow\n    res = call_workflow(workflow, unique_name, self)\n    ^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask/call.py\", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n      ^^^^^^^^^^^^^^^^^\n", "  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py\", line 671, in task_add_covariate_effect\n    model_with_added_effect = func(model_with_added_effect, allow_nested=True)\n      ^^^^^^^^^^^^^^^^^\n", 
"  File \"/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py\", line 431, in add_covariate_effect\n    assert last_existing_parameter_assignment is not None\n      ^^^^^^^^^^^^^^^^^\n")Traceback (most recent call last):
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/amd/run.py", line 530, in run_amd
    subresults = func(next_model, next_res)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/amd/run.py", line 1104, in _run_mechanistic_exploratory_covariates
    res = run_tool(
          ^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/run.py", line 244, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask/run.py", line 85, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/client.py", line 3483, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/distributed/client.py", line 2556, in gather
    return self.sync(
           ^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 380, in task_greedy_forward_search
    return _greedy_search(
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 468, in _greedy_search
    nonsignificant_effects, all_candidates_so_far, best_candidate_so_far = perform_step_procedure(
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 548, in perform_step_procedure
    new_candidates = handle_effects(
    ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 374, in handle_effects
    new_candidate_modelentries = context.call_workflow(wf, f'{NAME_WF}-effects_addition-{step}')
    ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/contexts/baseclass.py", line 237, in call_workflow
    res = call_workflow(workflow, unique_name, self)
    ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/workflows/dispatchers/local_dask/call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/tools/covsearch/tool.py", line 671, in task_add_covariate_effect
    model_with_added_effect = func(model_with_added_effect, allow_nested=True)
      ^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_12/lib/python3.12/site-packages/pharmpy/modeling/covariate_effect.py", line 431, in add_covariate_effect
    assert last_existing_parameter_assignment is not None
      ^^^^^^^^^^^^^^^^^

**Comment by yahanhsutw** [comment]
**Update**: Running with the same dataset, the issue did not occur when having PREGNANCY as structural covariate.
```
data.path <- "mc-sim-1.csv"
result <-run_amd(input = data.path,
                modeltype = 'basic_pk',
                administration = 'oral',
                cl_init = 1.50,
                vc_init = 25,
                mat_init = 0.75,
                occasion = 'PREGNANCY',
                strategy = 'default',
                search_space='ABSORPTION([FO]); ELIMINATION(FO); PERIPHERALS([0]); COVARIATE?([CL,MAT,VC],[AGE,WT],[LIN,EXP]);COVARIATE([CL],PREGNANCY, CAT)')
```
