### ISSUE TITLE
Compute Failed while running simulation

### ISSUE THREAD

**Issue by Jay-Kuang** [pharmpy/pharmpy#3447]
### Feature request

I'm a beginner at AMD,and I was tried to run a simple model using AMD. The model ran in nonmem without problems,but I met some problems while using AMD. AMD runs smoothly firstly,but when running simulation part,AMD run stopped,and could't give out final result. The following are my model code,python code and error log,I really want to figure it out where the problem is, thank you!
Model code:$PROB RUN# 101 (POPULATION PK MODEL)
$INPUT ID NOMTIME=TIME AMT DV WEIGHTB SEX
$DATA test.csv IGNORE=@
$SUBROUTINES ADVAN2 TRANS2         ;CL V KA
$PK
      TVCL=THETA(1)
      CL=TVCL*EXP(ETA(1))
      TVV = THETA(2)
      V = TVV*EXP(ETA(2))
      TVKA = THETA(3)
      KA = TVKA*EXP(ETA(3))
      S2 = V
$ERROR  Y= F+EPS(1)+F*EPS(2)
$THETA   (0,10)   ;CL
                (0,100) ;V
                (0,5)     ;KA
$OMEGA  0.09  ;1
                 0.09  ;2
                 0.09  ;3
$SIGMA    0.01  ;a
                 0.16  ;b
$EST METHOD=1 INTERACTION MAXEVAL=9999 ;PRINT=20 NOABORT POSTHOC MSF=SINGLEDOSE.msf
$COV UNCOND PRINT=E
$TABLE  ID TIME  DV PRED CWRES RES NOPRINT NOAPPEND ONEHEADER FILE=SINGLEDOSE.tab 

Python code:from pharmpy.modeling import *
from pharmpy.tools import *

file_path = read_model("C:/Users/asus/Desktop/暂存数据/Dataset/Dataset/single_Ascending_Code.mod")
print_model_code(file_path)
order=['structural', 'iivsearch','covariates']

res = run_simulation(file_path)

results = run_amd(input=file_path,
                  modeltype = 'basic_pk',
                  cl_init=9.08,
                  vc_init=79.9,
                  mat_init=0.376,
                  administration='oral',
                  strategy='SIR',
                  search_space="ABSORPTION([FO,ZO]);ELIMINATION(FO);LAGTIME([OFF,ON]); PERIPHERALS([0,1]);LET(CATEGORICAL, [SEX]); LET(CONTINUOUS, [WEIGHTB])")

Error log:2024-11-14 11:59:07,352 - distributed.worker - ERROR - Compute Failed
Key:       run-results_remaining
State:     executing
Function:  execute_task
args:      ((<function bundle_results at 0x000002E149E75440>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x000002E153DBEA20>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x000002E1561914F0>, <pharmpy.workflows.model_entry.ModelEntry object at 0x000002E1561AFAA0>)))
kwargs:    {}
Exception: 'KeyError("None of [\'SIM\', \'index\'] are in the columns")'
Traceback: '  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\modelfit\\tool.py", line 107, in task\n    me = execute_model(model_entry, context)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py", line 109, in execute_model\n    simulation_results = parse_simulation_results(model, model_path / basename)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 889, in parse_simulation_results\n    table = _parse_table_file(model, path=path, subproblem=subproblem)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 882, in _parse_table_file\n    df = df.set_index([\'SIM\', \'index\'])\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py", line 6122, in set_index\n    raise KeyError(f"None of {missing} are in the columns")\n'

2024-11-14 11:59:07,356 - distributed.worker - ERROR - Compute Failed
Key:       results
State:     long-running
Function:  run_simulations
args:      (<pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x000002E1561914F0>, <Pharmpy model object final_iivsearch_retries>)
kwargs:    {}
Exception: 'KeyError("None of [\'SIM\', \'index\'] are in the columns")'
Traceback: '  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\simulation\\tool.py", line 46, in run_simulations\n    modelentry_simulation = context.call_workflow(Workflow(wb), \'results_remaining\')[0]\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\workflows\\contexts\\baseclass.py", line 237, in call_workflow\n    res = call_workflow(workflow, unique_name, self)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\workflows\\dispatchers\\local_dask\\call.py", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n             ^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\distributed\\client.py", line 2556, in gather\n    return self.sync(\n           ^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\modelfit\\tool.py", line 107, in task\n    me = execute_model(model_entry, context)\n    ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py", line 109, in execute_model\n    simulation_results = parse_simulation_results(model, model_path / basename)\n    ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 889, in parse_simulation_results\n    table = _parse_table_file(model, path=path, subproblem=subproblem)\n      ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 882, in _parse_table_file\n    df = df.set_index([\'SIM\', \'index\'])\n      ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py", line 6122, in set_index\n    raise KeyError(f"None of {missing} are in the columns")\n    ^^^^^^^^^^^^^^^^^\n'

Traceback (most recent call last):
  File "c:\Users\asus\Desktop\Warfarintest.py", line 10, in <module>
    results = run_amd(input=file_path,
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\amd\run.py", line 582, in run_amd
    sim_res = _run_simulation(sim_model, ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\amd\run.py", line 725, in _run_simulation
    res = run_tool('simulation', model=model, path=subctx.path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\run.py", line 244, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask\run.py", line 85, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py", line 3483, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py", line 2556, in gather
    return self.sync(
           ^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\simulation\tool.py", line 46, in run_simulations
    modelentry_simulation = context.call_workflow(Workflow(wb), 'results_remaining')[0]
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\contexts\baseclass.py", line 237, in call_workflow
    res = call_workflow(workflow, unique_name, self)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask\call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\modelfit\tool.py", line 107, in task
    me = execute_model(model_entry, context)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 109, in execute_model
    simulation_results = parse_simulation_results(model, model_path / basename)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\results.py", line 889, in parse_simulation_results
    table = _parse_table_file(model, path=path, subproblem=subproblem)
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\results.py", line 882, in _parse_table_file
    df = df.set_index(['SIM', 'index'])
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 6122, in set_index
    raise KeyError(f"None of {missing} are in the columns")
^^^^^^^^^^^^^^^
KeyError: "None of ['SIM', 'index'] are in the columns"
PS C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages>

**Comment by Jay-Kuang** [comment]
> Thanks for your interest and for reporting this. This issue is related to reading in the simulation results from NONMEM and we would very much like to fix this. We might get back to you next week with some follow up questions if needed.

I really appreciate your help,

**Comment by Jay-Kuang** [comment]
> Thanks for your interest and for reporting this. This issue is related to reading in the simulation results from NONMEM and we would very much like to fix this. We might get back to you next week with some follow up questions if needed.

I really appreciate your help,I think AMD is a tool with unlimited potential,and easy to get started.It helped me a lot!

**Comment by Jay-Kuang** [comment]
Yes，I ran the model in nonmem in order to get a reference to the initial value of parameters. The model ran in nonmem without problems, and here are nonmem output files. I adjust the file format in order to uploading to the website.
[lst file.txt](https://github.com/user-attachments/files/17838509/lst.file.txt)
[table files.txt](https://github.com/user-attachments/files/17838510/table.files.txt)

**Comment by Jay-Kuang** [comment]
The same problem still occurs in Pharmpy-version 1.4, I really want to find the reason, and I sincerelly thank you for your effort!
KeyError("None of [\'SIM\', \'index\'] are in the columns"

**Comment by rikardn** [comment]
Not directly related to the issue but it isn't possible to run simulation with an estimation model. You would first need to change to model either manually or using `set_simulation()`. This is done internally in the amd tool, but I see that you also simulate outside of amd.

**Comment by rikardn** [comment]
Should not fail any longer with 926a31b2a306c7873c21a89bc147ad926a249d43. Will still not get a vpc though. Even before this fix you should be able to find the final model in the amd run directory under `models/final`.

**Comment by Jay-Kuang** [comment]
> The problem seems to happen when the simulation failed for some reason. Could you check the simulation run lst-file in the amd run directory? Should be under `subcontexts/simulation/models` or `models/simulation`

I'm sorry that before I  fix 926a31b, the simulation run lst-file is empty.I've found no file under subcontexts/simulation/models

**Comment by rikardn** [comment]
Ok, can you see any error messages in the files from NONMEM? If not what happens if you try to simulate using that model with NONMEM directly?

**Comment by Jay-Kuang** [comment]
[single_Ascending_Code .txt](https://github.com/user-attachments/files/18158832/single_Ascending_Code.txt)
No，The model runs smoothly with NONMEM,no boundary problem,no etabar. Anyway, here's the lst file after NONMEM running,I converted it to txt format in order to upload it.

**Comment by rikardn** [comment]
I mean the simulation model as created by Pharmpy in amd. I think it should be possible to reproduce the same as amd does by doing the following using your original estimation model:

```python
model = read_model("C:/Users/asus/Desktop/暂存数据/Dataset/Dataset/single_Ascending_Code.mod")
sim_model = set_simulation(model, samples=300)
res = run_simulation(model)
print(res.table)
```

**Comment by Jay-Kuang** [comment]
I've applied 926a31b,but amd still can't run simulation, the error message is as follows:simulation3                                             2024-12-18 09:29:01                   INFO               Dispatching workflow: <Client: 'inproc://192.168.1.102/27544/1' processes=1 threads=20,     
                                                                                                                 memory=15.63 GiB>
simulation3                                             2024-12-18 09:29:12                   INFO               End dispatch
None

When running AMD, KeyError("None of [\'SIM\', \'index\'] are in the columns" still exists
2024-12-18 10:24:19,732 - distributed.worker - ERROR - Compute Failed
Key:       run-results_remaining
State:     executing
Function:  execute_task
args:      ((<function bundle_results at 0x000001C6597625C0>, (<function retrieve_from_database_or_execute_model_with_tool.<locals>.task at 0x000001C66955C2C0>, <pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x000001C668074980>, <pharmpy.workflows.model_entry.ModelEntry object at 0x000001C667F054F0>)))
kwargs:    {}
Exception: 'KeyError("None of [\'SIM\', \'index\'] are in the columns")'
Traceback: '  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\modelfit\\tool.py", line 107, in task\n    me = execute_model(model_entry, context)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py", line 112, in execute_model\n    simulation_results = parse_simulation_results(model, model_path / basename)\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 891, in parse_simulation_results\n    table = _parse_table_file(model, path=path, subproblem=subproblem)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 884, in _parse_table_file\n    df = df.set_index([\'SIM\', \'index\'])\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py", line 6122, in set_index\n    raise KeyError(f"None of {missing} are in the columns")\n'

2024-12-18 10:24:19,743 - distributed.worker - ERROR - Compute Failed
Key:       results
State:     long-running
Function:  run_simulations
args:      (<pharmpy.workflows.contexts.local_directory.LocalDirectoryContext object at 0x000001C668074980>, <Pharmpy model object final_residual_retries>)
kwargs:    {}
Exception: 'KeyError("None of [\'SIM\', \'index\'] are in the columns")'
Traceback: '  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\simulation\\tool.py", line 46, in run_simulations\n    modelentry_simulation = context.call_workflow(Workflow(wb), \'results_remaining\')[0]\n                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\workflows\\contexts\\baseclass.py", line 237, in call_workflow\n    res = call_workflow(workflow, unique_name, self)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\workflows\\dispatchers\\local_dask\\call.py", line 41, in call_workflow\n    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]\n             
^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\distributed\\client.py", line 2556, in gather\n    return self.sync(\n           ^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\modelfit\\tool.py", line 107, in task\n    me = execute_model(model_entry, context)\n    ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\run.py", line 112, in execute_model\n    simulation_results = parse_simulation_results(model, model_path / basename)\n    ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 891, in parse_simulation_results\n    table = _parse_table_file(model, path=path, subproblem=subproblem)\n      ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pharmpy\\tools\\external\\nonmem\\results.py", line 884, in _parse_table_file\n    df = df.set_index([\'SIM\', \'index\'])\n    ^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\asus\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pandas\\core\\frame.py", line 6122, in set_index\n    raise KeyError(f"None of {missing} are in the columns")\n    ^^^^^^^^^^^^^^^^^\n'

Traceback (most recent call last):
  File "c:\Users\asus\Desktop\暂存数据\Dataset\Dataset\Warfarintest.py", line 7, in <module>
    results = run_amd(input=file_path,
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\amd\run.py", line 587, in run_amd
    sim_res = _run_simulation(sim_model, ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\amd\run.py", line 734, in _run_simulation
    res = run_tool('simulation', model=model, path=subctx.path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\run.py", line 189, in run_tool
    return run_tool_with_name(name, tool, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\run.py", line 244, in run_tool_with_name
    res = execute_workflow(wf, dispatcher=dispatcher, context=ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\execute.py", line 73, in execute_workflow
    res: T = dispatcher.run(workflow, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask\run.py", line 85, in run
    res = client.get(dsk_optimized, 'results')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py", line 3483, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\distributed\client.py", line 2556, in gather
    return self.sync(
           ^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\simulation\tool.py", line 46, in run_simulations
    modelentry_simulation = context.call_workflow(Workflow(wb), 'results_remaining')[0]
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\contexts\baseclass.py", line 237, in call_workflow
    res = call_workflow(workflow, unique_name, self)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\workflows\dispatchers\local_dask\call.py", line 41, in call_workflow
    res: T = client.gather(futures)  # pyright: ignore [reportGeneralTypeIssues]
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\modelfit\tool.py", line 107, in task
    me = execute_model(model_entry, context)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\run.py", line 112, in execute_model
    simulation_results = parse_simulation_results(model, model_path / basename)
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\results.py", line 891, in parse_simulation_results
    table = _parse_table_file(model, path=path, subproblem=subproblem)
      ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pharmpy\tools\external\nonmem\results.py", line 884, in _parse_table_file
    df = df.set_index(['SIM', 'index'])
  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 6122, in set_index
    raise KeyError(f"None of {missing} are in the columns")
^^^^^^^^^^^^^^^
KeyError: "None of ['SIM', 'index'] are in the columns"

**Comment by Jay-Kuang** [comment]
And here's problem messages while running amd

**Comment by Jay-Kuang** [comment]
And here's problems while running amd 
Variable not allowed in type expression, Type arguments for "Literal" must be None, a literal value (int, bool, str, or bytes), or an enum value   [The variable is (DV_TYPES)]
I want to upload the screen shot, but it failed

**Comment by rikardn** [comment]
I would need a way of reproducing this. Would it be possible to create a small example where this happens that I can run on my side?
