### ISSUE TITLE
 CommClosedError() in run_amd after retries step

### ISSUE THREAD

**Issue by yahanhsutw** [pharmpy/pharmpy#3473]
### Bug report

**Pharmpy version**: 1.3.0 (dev#237)

**Issue**: An error raise after residual_retries step in `run_amd()`, though it did not terminate the run.
**Error message**: 
2024-11-25 10:56:31,182 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/domus/h1/yahs1790/.virtualenvs/pharmpy_test/lib/python3.12/site-packages/distributed/comm/inproc.py", line 224, in read
    raise CommClosedError()
distributed.comm.core.CommClosedError
(Full message in /crex/proj/pmgroup_active_storage/private/users/yahan/AMD/Barbara/amd_sse_100_structural/failed/group1/amd_g1.Rout)
 
**Run directory**: 
/crex/proj/pmgroup_active_storage/private/users/yahan/AMD/Barbara/amd_sse_100_structural/failed/group1/amd7

**Comment by rikardn** [comment]
This doesn't seem to appear in the reruns. I'll close now. We can reopen if it appears again.
