### ISSUE TITLE
Eta maps not generated for additive error model

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#59]
For some models you get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devel/pharmpy/pharmpy/venv_batch/lib/python3.8/site-packages/pharmpy_core-0.11.0-py3.8.egg/pharmpy/plugins/nonmem/model.py", line 98, in update_source
    update_random_variables(self, self._old_random_variables, self._random_variables)
  File "/home/devel/pharmpy/pharmpy/venv_batch/lib/python3.8/site-packages/pharmpy_core-0.11.0-py3.8.egg/pharmpy/plugins/nonmem/update.py", line 89, in update_random_variables
    current_names = omega_record.eta_map.keys()
AttributeError: 'OmegaRecord' object has no attribute 'eta_map'
```
See run3ab.mod.

**Comment by rikardn** [comment]
What was done to the model to trigger the error?

**Comment by stellabelin** [comment]
First removing error model, changing to additive error model, the error occurs during the subsequent update_source()
