### ISSUE TITLE
Crash when updating statements after adding an eta

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#63]
When adding etas, some models crash when updating statements. For example for run678.mod, when running:

```
add_etas(model, 'TVMTT', 'exp')
model.update_source()
```

The following error occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/devel/pharmpy/pharmpy/venv_batch/lib/python3.8/site-packages/pharmpy_core-0.11.0-py3.8.egg/pharmpy/plugins/nonmem/model.py", line 109, in update_source
    update_statements(self, self._old_statements, self._statements, trans)
  File "/home/devel/pharmpy/pharmpy/venv_batch/lib/python3.8/site-packages/pharmpy_core-0.11.0-py3.8.egg/pharmpy/plugins/nonmem/update.py", line 378, in update_statements
    rec.statements = main_statements
  File "/home/devel/pharmpy/pharmpy/venv_batch/lib/python3.8/site-packages/pharmpy_core-0.11.0-py3.8.egg/pharmpy/plugins/nonmem/records/code_record.py", line 279, in statements
    kept.append(self.root.children[node_index])
IndexError: list index out of range

```

**Comment by rikardn** [comment]
I can confirm that this is due to a problem in the mapping between AST nodes and statements. For more complex IF-statements there is no 1to1 mapping.

I debugprint 

```python
                print(node_index, str(self.root.children[node_index]).strip(), "<->", s)
```

for the do-not-update case and get:

```
77 TADW = TAD/(24*7) <->         TAD
        ───
TADW := 168

81 IF (NEWIND.NE.2.OR.EVID.GE.3) THEN ; beginning of dataset, or new individual
TNXD=TIME ; TIME will be the time of the first record of that subject even if it's not a dose, but...
PNXD=AMT ; ...the amount will be 0 if the first record is not a dose, so no problem.
NDOS = 0
ENDIF <-> TNXD := {TIME  for EVID ≥ 3 ∨ NEWIND ≠ 2

83 IF(ID.NE.3038) THEN
TDOS=TNXD ; This will either save here the temporary values if it's a new individual...
PD=PNXD ; ...or the values which were read one record ahead during the execution of the previous record.
ENDIF <-> PNXD := {AMT  for EVID ≥ 3 ∨ NEWIND ≠ 2
```

Up to index 77 everything is fine, but then comes an if-statement that gets translated into multiple `Assignments`.
